/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.spisoklotov.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Spisoklotov service. Represents a row in the &quot;sapp.spisok_lotov&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.spisoklotov.model.impl.SpisoklotovModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.spisoklotov.model.impl.SpisoklotovImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Spisoklotov
 * @see tj.spisoklotov.model.impl.SpisoklotovImpl
 * @see tj.spisoklotov.model.impl.SpisoklotovModelImpl
 * @generated
 */
@ProviderType
public interface SpisoklotovModel extends BaseModel<Spisoklotov> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a spisoklotov model instance should use the {@link Spisoklotov} interface instead.
	 */

	/**
	 * Returns the primary key of this spisoklotov.
	 *
	 * @return the primary key of this spisoklotov
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this spisoklotov.
	 *
	 * @param primaryKey the primary key of this spisoklotov
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cena_kontrakta of this spisoklotov.
	 *
	 * @return the cena_kontrakta of this spisoklotov
	 */
	public double getCena_kontrakta();

	/**
	 * Sets the cena_kontrakta of this spisoklotov.
	 *
	 * @param cena_kontrakta the cena_kontrakta of this spisoklotov
	 */
	public void setCena_kontrakta(double cena_kontrakta);

	/**
	 * Returns the cena_postavki of this spisoklotov.
	 *
	 * @return the cena_postavki of this spisoklotov
	 */
	@AutoEscape
	public String getCena_postavki();

	/**
	 * Sets the cena_postavki of this spisoklotov.
	 *
	 * @param cena_postavki the cena_postavki of this spisoklotov
	 */
	public void setCena_postavki(String cena_postavki);

	/**
	 * Returns the data_izmenenija of this spisoklotov.
	 *
	 * @return the data_izmenenija of this spisoklotov
	 */
	public Date getData_izmenenija();

	/**
	 * Sets the data_izmenenija of this spisoklotov.
	 *
	 * @param data_izmenenija the data_izmenenija of this spisoklotov
	 */
	public void setData_izmenenija(Date data_izmenenija);

	/**
	 * Returns the data_sozdanija of this spisoklotov.
	 *
	 * @return the data_sozdanija of this spisoklotov
	 */
	public Date getData_sozdanija();

	/**
	 * Sets the data_sozdanija of this spisoklotov.
	 *
	 * @param data_sozdanija the data_sozdanija of this spisoklotov
	 */
	public void setData_sozdanija(Date data_sozdanija);

	/**
	 * Returns the id_jebk of this spisoklotov.
	 *
	 * @return the id_jebk of this spisoklotov
	 */
	public long getId_jebk();

	/**
	 * Sets the id_jebk of this spisoklotov.
	 *
	 * @param id_jebk the id_jebk of this spisoklotov
	 */
	public void setId_jebk(long id_jebk);

	/**
	 * Returns the istochnik_finansirovanija_id of this spisoklotov.
	 *
	 * @return the istochnik_finansirovanija_id of this spisoklotov
	 */
	public long getIstochnik_finansirovanija_id();

	/**
	 * Sets the istochnik_finansirovanija_id of this spisoklotov.
	 *
	 * @param istochnik_finansirovanija_id the istochnik_finansirovanija_id of this spisoklotov
	 */
	public void setIstochnik_finansirovanija_id(
		long istochnik_finansirovanija_id);

	/**
	 * Returns the izmenil of this spisoklotov.
	 *
	 * @return the izmenil of this spisoklotov
	 */
	public long getIzmenil();

	/**
	 * Sets the izmenil of this spisoklotov.
	 *
	 * @param izmenil the izmenil of this spisoklotov
	 */
	public void setIzmenil(long izmenil);

	/**
	 * Returns the izvewenie_id of this spisoklotov.
	 *
	 * @return the izvewenie_id of this spisoklotov
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this spisoklotov.
	 *
	 * @param izvewenie_id the izvewenie_id of this spisoklotov
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the klassifikacija_po_jekb of this spisoklotov.
	 *
	 * @return the klassifikacija_po_jekb of this spisoklotov
	 */
	@AutoEscape
	public String getKlassifikacija_po_jekb();

	/**
	 * Sets the klassifikacija_po_jekb of this spisoklotov.
	 *
	 * @param klassifikacija_po_jekb the klassifikacija_po_jekb of this spisoklotov
	 */
	public void setKlassifikacija_po_jekb(String klassifikacija_po_jekb);

	/**
	 * Returns the kod_jekb of this spisoklotov.
	 *
	 * @return the kod_jekb of this spisoklotov
	 */
	@AutoEscape
	public String getKod_jekb();

	/**
	 * Sets the kod_jekb of this spisoklotov.
	 *
	 * @param kod_jekb the kod_jekb of this spisoklotov
	 */
	public void setKod_jekb(String kod_jekb);

	/**
	 * Returns the kod_zakazchika of this spisoklotov.
	 *
	 * @return the kod_zakazchika of this spisoklotov
	 */
	@AutoEscape
	public String getKod_zakazchika();

	/**
	 * Sets the kod_zakazchika of this spisoklotov.
	 *
	 * @param kod_zakazchika the kod_zakazchika of this spisoklotov
	 */
	public void setKod_zakazchika(String kod_zakazchika);

	/**
	 * Returns the mesto_postavki of this spisoklotov.
	 *
	 * @return the mesto_postavki of this spisoklotov
	 */
	@AutoEscape
	public String getMesto_postavki();

	/**
	 * Sets the mesto_postavki of this spisoklotov.
	 *
	 * @param mesto_postavki the mesto_postavki of this spisoklotov
	 */
	public void setMesto_postavki(String mesto_postavki);

	/**
	 * Returns the naimenovanie_lota of this spisoklotov.
	 *
	 * @return the naimenovanie_lota of this spisoklotov
	 */
	@AutoEscape
	public String getNaimenovanie_lota();

	/**
	 * Sets the naimenovanie_lota of this spisoklotov.
	 *
	 * @param naimenovanie_lota the naimenovanie_lota of this spisoklotov
	 */
	public void setNaimenovanie_lota(String naimenovanie_lota);

	/**
	 * Returns the nomer_lota of this spisoklotov.
	 *
	 * @return the nomer_lota of this spisoklotov
	 */
	public long getNomer_lota();

	/**
	 * Sets the nomer_lota of this spisoklotov.
	 *
	 * @param nomer_lota the nomer_lota of this spisoklotov
	 */
	public void setNomer_lota(long nomer_lota);

	/**
	 * Returns the obespechenie_ispolnenija of this spisoklotov.
	 *
	 * @return the obespechenie_ispolnenija of this spisoklotov
	 */
	public long getObespechenie_ispolnenija();

	/**
	 * Sets the obespechenie_ispolnenija of this spisoklotov.
	 *
	 * @param obespechenie_ispolnenija the obespechenie_ispolnenija of this spisoklotov
	 */
	public void setObespechenie_ispolnenija(long obespechenie_ispolnenija);

	/**
	 * Returns the obespechenie_ispolnenija_v_procentah of this spisoklotov.
	 *
	 * @return the obespechenie_ispolnenija_v_procentah of this spisoklotov
	 */
	public double getObespechenie_ispolnenija_v_procentah();

	/**
	 * Sets the obespechenie_ispolnenija_v_procentah of this spisoklotov.
	 *
	 * @param obespechenie_ispolnenija_v_procentah the obespechenie_ispolnenija_v_procentah of this spisoklotov
	 */
	public void setObespechenie_ispolnenija_v_procentah(
		double obespechenie_ispolnenija_v_procentah);

	/**
	 * Returns the obespechenie_v_procentah of this spisoklotov.
	 *
	 * @return the obespechenie_v_procentah of this spisoklotov
	 */
	public double getObespechenie_v_procentah();

	/**
	 * Sets the obespechenie_v_procentah of this spisoklotov.
	 *
	 * @param obespechenie_v_procentah the obespechenie_v_procentah of this spisoklotov
	 */
	public void setObespechenie_v_procentah(double obespechenie_v_procentah);

	/**
	 * Returns the obespechenie_zajavki of this spisoklotov.
	 *
	 * @return the obespechenie_zajavki of this spisoklotov
	 */
	public long getObespechenie_zajavki();

	/**
	 * Sets the obespechenie_zajavki of this spisoklotov.
	 *
	 * @param obespechenie_zajavki the obespechenie_zajavki of this spisoklotov
	 */
	public void setObespechenie_zajavki(long obespechenie_zajavki);

	/**
	 * Returns the oplata of this spisoklotov.
	 *
	 * @return the oplata of this spisoklotov
	 */
	@AutoEscape
	public String getOplata();

	/**
	 * Sets the oplata of this spisoklotov.
	 *
	 * @param oplata the oplata of this spisoklotov
	 */
	public void setOplata(String oplata);

	/**
	 * Returns the soputstvujuwie_uslovija of this spisoklotov.
	 *
	 * @return the soputstvujuwie_uslovija of this spisoklotov
	 */
	@AutoEscape
	public String getSoputstvujuwie_uslovija();

	/**
	 * Sets the soputstvujuwie_uslovija of this spisoklotov.
	 *
	 * @param soputstvujuwie_uslovija the soputstvujuwie_uslovija of this spisoklotov
	 */
	public void setSoputstvujuwie_uslovija(String soputstvujuwie_uslovija);

	/**
	 * Returns the sozdal of this spisoklotov.
	 *
	 * @return the sozdal of this spisoklotov
	 */
	public long getSozdal();

	/**
	 * Sets the sozdal of this spisoklotov.
	 *
	 * @param sozdal the sozdal of this spisoklotov
	 */
	public void setSozdal(long sozdal);

	/**
	 * Returns the spisok_lotov_id of this spisoklotov.
	 *
	 * @return the spisok_lotov_id of this spisoklotov
	 */
	public long getSpisok_lotov_id();

	/**
	 * Sets the spisok_lotov_id of this spisoklotov.
	 *
	 * @param spisok_lotov_id the spisok_lotov_id of this spisoklotov
	 */
	public void setSpisok_lotov_id(long spisok_lotov_id);

	/**
	 * Returns the srok_dejstvija of this spisoklotov.
	 *
	 * @return the srok_dejstvija of this spisoklotov
	 */
	@AutoEscape
	public String getSrok_dejstvija();

	/**
	 * Sets the srok_dejstvija of this spisoklotov.
	 *
	 * @param srok_dejstvija the srok_dejstvija of this spisoklotov
	 */
	public void setSrok_dejstvija(String srok_dejstvija);

	/**
	 * Returns the srok_ispolnenija_zajavki of this spisoklotov.
	 *
	 * @return the srok_ispolnenija_zajavki of this spisoklotov
	 */
	@AutoEscape
	public String getSrok_ispolnenija_zajavki();

	/**
	 * Sets the srok_ispolnenija_zajavki of this spisoklotov.
	 *
	 * @param srok_ispolnenija_zajavki the srok_ispolnenija_zajavki of this spisoklotov
	 */
	public void setSrok_ispolnenija_zajavki(String srok_ispolnenija_zajavki);

	/**
	 * Returns the srok_obespechenija_zajavki of this spisoklotov.
	 *
	 * @return the srok_obespechenija_zajavki of this spisoklotov
	 */
	@AutoEscape
	public String getSrok_obespechenija_zajavki();

	/**
	 * Sets the srok_obespechenija_zajavki of this spisoklotov.
	 *
	 * @param srok_obespechenija_zajavki the srok_obespechenija_zajavki of this spisoklotov
	 */
	public void setSrok_obespechenija_zajavki(String srok_obespechenija_zajavki);

	/**
	 * Returns the srok_postavki of this spisoklotov.
	 *
	 * @return the srok_postavki of this spisoklotov
	 */
	@AutoEscape
	public String getSrok_postavki();

	/**
	 * Sets the srok_postavki of this spisoklotov.
	 *
	 * @param srok_postavki the srok_postavki of this spisoklotov
	 */
	public void setSrok_postavki(String srok_postavki);

	/**
	 * Returns the zakazchik of this spisoklotov.
	 *
	 * @return the zakazchik of this spisoklotov
	 */
	@AutoEscape
	public String getZakazchik();

	/**
	 * Sets the zakazchik of this spisoklotov.
	 *
	 * @param zakazchik the zakazchik of this spisoklotov
	 */
	public void setZakazchik(String zakazchik);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.spisoklotov.model.Spisoklotov spisoklotov);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.spisoklotov.model.Spisoklotov> toCacheModel();

	@Override
	public tj.spisoklotov.model.Spisoklotov toEscapedModel();

	@Override
	public tj.spisoklotov.model.Spisoklotov toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}