/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.bid.queue.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Bidqueue service. Represents a row in the &quot;sapp.bid_queue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.bid.queue.model.impl.BidqueueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.bid.queue.model.impl.BidqueueImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Bidqueue
 * @see tj.bid.queue.model.impl.BidqueueImpl
 * @see tj.bid.queue.model.impl.BidqueueModelImpl
 * @generated
 */
@ProviderType
public interface BidqueueModel extends BaseModel<Bidqueue> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bidqueue model instance should use the {@link Bidqueue} interface instead.
	 */

	/**
	 * Returns the primary key of this bidqueue.
	 *
	 * @return the primary key of this bidqueue
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bidqueue.
	 *
	 * @param primaryKey the primary key of this bidqueue
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bid_queue_id of this bidqueue.
	 *
	 * @return the bid_queue_id of this bidqueue
	 */
	public long getBid_queue_id();

	/**
	 * Sets the bid_queue_id of this bidqueue.
	 *
	 * @param bid_queue_id the bid_queue_id of this bidqueue
	 */
	public void setBid_queue_id(long bid_queue_id);

	/**
	 * Returns the izvewenija_id of this bidqueue.
	 *
	 * @return the izvewenija_id of this bidqueue
	 */
	public long getIzvewenija_id();

	/**
	 * Sets the izvewenija_id of this bidqueue.
	 *
	 * @param izvewenija_id the izvewenija_id of this bidqueue
	 */
	public void setIzvewenija_id(long izvewenija_id);

	/**
	 * Returns the closing_date of this bidqueue.
	 *
	 * @return the closing_date of this bidqueue
	 */
	public Date getClosing_date();

	/**
	 * Sets the closing_date of this bidqueue.
	 *
	 * @param closing_date the closing_date of this bidqueue
	 */
	public void setClosing_date(Date closing_date);

	/**
	 * Returns the closing_by_minutes of this bidqueue.
	 *
	 * @return the closing_by_minutes of this bidqueue
	 */
	public long getClosing_by_minutes();

	/**
	 * Sets the closing_by_minutes of this bidqueue.
	 *
	 * @param closing_by_minutes the closing_by_minutes of this bidqueue
	 */
	public void setClosing_by_minutes(long closing_by_minutes);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.bid.queue.model.Bidqueue bidqueue);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.bid.queue.model.Bidqueue> toCacheModel();

	@Override
	public tj.bid.queue.model.Bidqueue toEscapedModel();

	@Override
	public tj.bid.queue.model.Bidqueue toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}