/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.spisok.tovarov.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SpisokTovarov service. Represents a row in the &quot;sapp.spisok_tovarov&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.spisok.tovarov.model.impl.SpisokTovarovModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.spisok.tovarov.model.impl.SpisokTovarovImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SpisokTovarov
 * @see tj.spisok.tovarov.model.impl.SpisokTovarovImpl
 * @see tj.spisok.tovarov.model.impl.SpisokTovarovModelImpl
 * @generated
 */
@ProviderType
public interface SpisokTovarovModel extends BaseModel<SpisokTovarov> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a spisok tovarov model instance should use the {@link SpisokTovarov} interface instead.
	 */

	/**
	 * Returns the primary key of this spisok tovarov.
	 *
	 * @return the primary key of this spisok tovarov
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this spisok tovarov.
	 *
	 * @param primaryKey the primary key of this spisok tovarov
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data_izmenenija of this spisok tovarov.
	 *
	 * @return the data_izmenenija of this spisok tovarov
	 */
	public Date getData_izmenenija();

	/**
	 * Sets the data_izmenenija of this spisok tovarov.
	 *
	 * @param data_izmenenija the data_izmenenija of this spisok tovarov
	 */
	public void setData_izmenenija(Date data_izmenenija);

	/**
	 * Returns the data_sozdanija of this spisok tovarov.
	 *
	 * @return the data_sozdanija of this spisok tovarov
	 */
	public Date getData_sozdanija();

	/**
	 * Sets the data_sozdanija of this spisok tovarov.
	 *
	 * @param data_sozdanija the data_sozdanija of this spisok tovarov
	 */
	public void setData_sozdanija(Date data_sozdanija);

	/**
	 * Returns the edinica_izmerenija_id of this spisok tovarov.
	 *
	 * @return the edinica_izmerenija_id of this spisok tovarov
	 */
	public long getEdinica_izmerenija_id();

	/**
	 * Sets the edinica_izmerenija_id of this spisok tovarov.
	 *
	 * @param edinica_izmerenija_id the edinica_izmerenija_id of this spisok tovarov
	 */
	public void setEdinica_izmerenija_id(long edinica_izmerenija_id);

	/**
	 * Returns the izmenil of this spisok tovarov.
	 *
	 * @return the izmenil of this spisok tovarov
	 */
	public long getIzmenil();

	/**
	 * Sets the izmenil of this spisok tovarov.
	 *
	 * @param izmenil the izmenil of this spisok tovarov
	 */
	public void setIzmenil(long izmenil);

	/**
	 * Returns the izvewenie_id of this spisok tovarov.
	 *
	 * @return the izvewenie_id of this spisok tovarov
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this spisok tovarov.
	 *
	 * @param izvewenie_id the izvewenie_id of this spisok tovarov
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the klassifikacija_po_okdp of this spisok tovarov.
	 *
	 * @return the klassifikacija_po_okdp of this spisok tovarov
	 */
	@AutoEscape
	public String getKlassifikacija_po_okdp();

	/**
	 * Sets the klassifikacija_po_okdp of this spisok tovarov.
	 *
	 * @param klassifikacija_po_okdp the klassifikacija_po_okdp of this spisok tovarov
	 */
	public void setKlassifikacija_po_okdp(String klassifikacija_po_okdp);

	/**
	 * Returns the kod_po_okdp of this spisok tovarov.
	 *
	 * @return the kod_po_okdp of this spisok tovarov
	 */
	@AutoEscape
	public String getKod_po_okdp();

	/**
	 * Sets the kod_po_okdp of this spisok tovarov.
	 *
	 * @param kod_po_okdp the kod_po_okdp of this spisok tovarov
	 */
	public void setKod_po_okdp(String kod_po_okdp);

	/**
	 * Returns the kod_po_spravochniku_naimenovanij of this spisok tovarov.
	 *
	 * @return the kod_po_spravochniku_naimenovanij of this spisok tovarov
	 */
	public long getKod_po_spravochniku_naimenovanij();

	/**
	 * Sets the kod_po_spravochniku_naimenovanij of this spisok tovarov.
	 *
	 * @param kod_po_spravochniku_naimenovanij the kod_po_spravochniku_naimenovanij of this spisok tovarov
	 */
	public void setKod_po_spravochniku_naimenovanij(
		long kod_po_spravochniku_naimenovanij);

	/**
	 * Returns the kod_strany_proizvoditelja of this spisok tovarov.
	 *
	 * @return the kod_strany_proizvoditelja of this spisok tovarov
	 */
	public long getKod_strany_proizvoditelja();

	/**
	 * Sets the kod_strany_proizvoditelja of this spisok tovarov.
	 *
	 * @param kod_strany_proizvoditelja the kod_strany_proizvoditelja of this spisok tovarov
	 */
	public void setKod_strany_proizvoditelja(long kod_strany_proizvoditelja);

	/**
	 * Returns the kolichestvo of this spisok tovarov.
	 *
	 * @return the kolichestvo of this spisok tovarov
	 */
	public long getKolichestvo();

	/**
	 * Sets the kolichestvo of this spisok tovarov.
	 *
	 * @param kolichestvo the kolichestvo of this spisok tovarov
	 */
	public void setKolichestvo(long kolichestvo);

	/**
	 * Returns the lot_id of this spisok tovarov.
	 *
	 * @return the lot_id of this spisok tovarov
	 */
	public long getLot_id();

	/**
	 * Sets the lot_id of this spisok tovarov.
	 *
	 * @param lot_id the lot_id of this spisok tovarov
	 */
	public void setLot_id(long lot_id);

	/**
	 * Returns the naimenovanie_tovara of this spisok tovarov.
	 *
	 * @return the naimenovanie_tovara of this spisok tovarov
	 */
	@AutoEscape
	public String getNaimenovanie_tovara();

	/**
	 * Sets the naimenovanie_tovara of this spisok tovarov.
	 *
	 * @param naimenovanie_tovara the naimenovanie_tovara of this spisok tovarov
	 */
	public void setNaimenovanie_tovara(String naimenovanie_tovara);

	/**
	 * Returns the opisanie_tovara of this spisok tovarov.
	 *
	 * @return the opisanie_tovara of this spisok tovarov
	 */
	@AutoEscape
	public String getOpisanie_tovara();

	/**
	 * Sets the opisanie_tovara of this spisok tovarov.
	 *
	 * @param opisanie_tovara the opisanie_tovara of this spisok tovarov
	 */
	public void setOpisanie_tovara(String opisanie_tovara);

	/**
	 * Returns the sozdal of this spisok tovarov.
	 *
	 * @return the sozdal of this spisok tovarov
	 */
	public long getSozdal();

	/**
	 * Sets the sozdal of this spisok tovarov.
	 *
	 * @param sozdal the sozdal of this spisok tovarov
	 */
	public void setSozdal(long sozdal);

	/**
	 * Returns the spisok_tovarov_id of this spisok tovarov.
	 *
	 * @return the spisok_tovarov_id of this spisok tovarov
	 */
	public long getSpisok_tovarov_id();

	/**
	 * Sets the spisok_tovarov_id of this spisok tovarov.
	 *
	 * @param spisok_tovarov_id the spisok_tovarov_id of this spisok tovarov
	 */
	public void setSpisok_tovarov_id(long spisok_tovarov_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.spisok.tovarov.model.SpisokTovarov spisokTovarov);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.spisok.tovarov.model.SpisokTovarov> toCacheModel();

	@Override
	public tj.spisok.tovarov.model.SpisokTovarov toEscapedModel();

	@Override
	public tj.spisok.tovarov.model.SpisokTovarov toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}