/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.supplier.request.lot.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the SupplierRequestLot service. Represents a row in the &quot;sapp.supplier_request_lot&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.supplier.request.lot.model.impl.SupplierRequestLotModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.supplier.request.lot.model.impl.SupplierRequestLotImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupplierRequestLot
 * @see tj.supplier.request.lot.model.impl.SupplierRequestLotImpl
 * @see tj.supplier.request.lot.model.impl.SupplierRequestLotModelImpl
 * @generated
 */
@ProviderType
public interface SupplierRequestLotModel extends BaseModel<SupplierRequestLot> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a supplier request lot model instance should use the {@link SupplierRequestLot} interface instead.
	 */

	/**
	 * Returns the primary key of this supplier request lot.
	 *
	 * @return the primary key of this supplier request lot
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this supplier request lot.
	 *
	 * @param primaryKey the primary key of this supplier request lot
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the supplier_request_lot_id of this supplier request lot.
	 *
	 * @return the supplier_request_lot_id of this supplier request lot
	 */
	public long getSupplier_request_lot_id();

	/**
	 * Sets the supplier_request_lot_id of this supplier request lot.
	 *
	 * @param supplier_request_lot_id the supplier_request_lot_id of this supplier request lot
	 */
	public void setSupplier_request_lot_id(long supplier_request_lot_id);

	/**
	 * Returns the organization_id of this supplier request lot.
	 *
	 * @return the organization_id of this supplier request lot
	 */
	public long getOrganization_id();

	/**
	 * Sets the organization_id of this supplier request lot.
	 *
	 * @param organization_id the organization_id of this supplier request lot
	 */
	public void setOrganization_id(long organization_id);

	/**
	 * Returns the spisok_lotov_id of this supplier request lot.
	 *
	 * @return the spisok_lotov_id of this supplier request lot
	 */
	public long getSpisok_lotov_id();

	/**
	 * Sets the spisok_lotov_id of this supplier request lot.
	 *
	 * @param spisok_lotov_id the spisok_lotov_id of this supplier request lot
	 */
	public void setSpisok_lotov_id(long spisok_lotov_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.supplier.request.lot.model.SupplierRequestLot supplierRequestLot);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.supplier.request.lot.model.SupplierRequestLot> toCacheModel();

	@Override
	public tj.supplier.request.lot.model.SupplierRequestLot toEscapedModel();

	@Override
	public tj.supplier.request.lot.model.SupplierRequestLot toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}