/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.vbk.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.vbk.model.Vbk;
import tj.vbk.model.VbkModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Vbk service. Represents a row in the &quot;klassifikatory.vbk&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VbkModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VbkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VbkImpl
 * @see Vbk
 * @see VbkModel
 * @generated
 */
@ProviderType
public class VbkModelImpl extends BaseModelImpl<Vbk> implements VbkModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vbk model instance should use the {@link Vbk} interface instead.
	 */
	public static final String TABLE_NAME = "klassifikatory.vbk";
	public static final Object[][] TABLE_COLUMNS = {
			{ "vbk_id", Types.BIGINT },
			{ "kod", Types.VARCHAR },
			{ "nazvanie_tj", Types.VARCHAR },
			{ "nazvanie_ru", Types.VARCHAR },
			{ "organizationid", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("vbk_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("kod", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nazvanie_tj", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nazvanie_ru", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("organizationid", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table klassifikatory.vbk (vbk_id LONG not null primary key,kod VARCHAR(75) null,nazvanie_tj VARCHAR(75) null,nazvanie_ru VARCHAR(75) null,organizationid LONG)";
	public static final String TABLE_SQL_DROP = "drop table klassifikatory.vbk";
	public static final String ORDER_BY_JPQL = " ORDER BY vbk.vbk_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY klassifikatory.vbk.vbk_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.vbk.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.vbk.model.Vbk"), true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.vbk.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.vbk.model.Vbk"), true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.vbk.service.util.ServiceProps.get(
				"lock.expiration.time.tj.vbk.model.Vbk"));

	public VbkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _vbk_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVbk_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _vbk_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Vbk.class;
	}

	@Override
	public String getModelClassName() {
		return Vbk.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("vbk_id", getVbk_id());
		attributes.put("kod", getKod());
		attributes.put("nazvanie_tj", getNazvanie_tj());
		attributes.put("nazvanie_ru", getNazvanie_ru());
		attributes.put("organizationid", getOrganizationid());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long vbk_id = (Long)attributes.get("vbk_id");

		if (vbk_id != null) {
			setVbk_id(vbk_id);
		}

		String kod = (String)attributes.get("kod");

		if (kod != null) {
			setKod(kod);
		}

		String nazvanie_tj = (String)attributes.get("nazvanie_tj");

		if (nazvanie_tj != null) {
			setNazvanie_tj(nazvanie_tj);
		}

		String nazvanie_ru = (String)attributes.get("nazvanie_ru");

		if (nazvanie_ru != null) {
			setNazvanie_ru(nazvanie_ru);
		}

		Long organizationid = (Long)attributes.get("organizationid");

		if (organizationid != null) {
			setOrganizationid(organizationid);
		}
	}

	@Override
	public long getVbk_id() {
		return _vbk_id;
	}

	@Override
	public void setVbk_id(long vbk_id) {
		_vbk_id = vbk_id;
	}

	@Override
	public String getKod() {
		if (_kod == null) {
			return StringPool.BLANK;
		}
		else {
			return _kod;
		}
	}

	@Override
	public void setKod(String kod) {
		_kod = kod;
	}

	@Override
	public String getNazvanie_tj() {
		if (_nazvanie_tj == null) {
			return StringPool.BLANK;
		}
		else {
			return _nazvanie_tj;
		}
	}

	@Override
	public void setNazvanie_tj(String nazvanie_tj) {
		_nazvanie_tj = nazvanie_tj;
	}

	@Override
	public String getNazvanie_ru() {
		if (_nazvanie_ru == null) {
			return StringPool.BLANK;
		}
		else {
			return _nazvanie_ru;
		}
	}

	@Override
	public void setNazvanie_ru(String nazvanie_ru) {
		_nazvanie_ru = nazvanie_ru;
	}

	@Override
	public long getOrganizationid() {
		return _organizationid;
	}

	@Override
	public void setOrganizationid(long organizationid) {
		_organizationid = organizationid;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Vbk.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Vbk toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Vbk)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VbkImpl vbkImpl = new VbkImpl();

		vbkImpl.setVbk_id(getVbk_id());
		vbkImpl.setKod(getKod());
		vbkImpl.setNazvanie_tj(getNazvanie_tj());
		vbkImpl.setNazvanie_ru(getNazvanie_ru());
		vbkImpl.setOrganizationid(getOrganizationid());

		vbkImpl.resetOriginalValues();

		return vbkImpl;
	}

	@Override
	public int compareTo(Vbk vbk) {
		long primaryKey = vbk.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Vbk)) {
			return false;
		}

		Vbk vbk = (Vbk)obj;

		long primaryKey = vbk.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Vbk> toCacheModel() {
		VbkCacheModel vbkCacheModel = new VbkCacheModel();

		vbkCacheModel.vbk_id = getVbk_id();

		vbkCacheModel.kod = getKod();

		String kod = vbkCacheModel.kod;

		if ((kod != null) && (kod.length() == 0)) {
			vbkCacheModel.kod = null;
		}

		vbkCacheModel.nazvanie_tj = getNazvanie_tj();

		String nazvanie_tj = vbkCacheModel.nazvanie_tj;

		if ((nazvanie_tj != null) && (nazvanie_tj.length() == 0)) {
			vbkCacheModel.nazvanie_tj = null;
		}

		vbkCacheModel.nazvanie_ru = getNazvanie_ru();

		String nazvanie_ru = vbkCacheModel.nazvanie_ru;

		if ((nazvanie_ru != null) && (nazvanie_ru.length() == 0)) {
			vbkCacheModel.nazvanie_ru = null;
		}

		vbkCacheModel.organizationid = getOrganizationid();

		return vbkCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{vbk_id=");
		sb.append(getVbk_id());
		sb.append(", kod=");
		sb.append(getKod());
		sb.append(", nazvanie_tj=");
		sb.append(getNazvanie_tj());
		sb.append(", nazvanie_ru=");
		sb.append(getNazvanie_ru());
		sb.append(", organizationid=");
		sb.append(getOrganizationid());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("tj.vbk.model.Vbk");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>vbk_id</column-name><column-value><![CDATA[");
		sb.append(getVbk_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kod</column-name><column-value><![CDATA[");
		sb.append(getKod());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nazvanie_tj</column-name><column-value><![CDATA[");
		sb.append(getNazvanie_tj());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nazvanie_ru</column-name><column-value><![CDATA[");
		sb.append(getNazvanie_ru());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizationid</column-name><column-value><![CDATA[");
		sb.append(getOrganizationid());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Vbk.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Vbk.class
		};
	private long _vbk_id;
	private String _kod;
	private String _nazvanie_tj;
	private String _nazvanie_ru;
	private long _organizationid;
	private Vbk _escapedModel;
}