/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.criterias.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CriteriaTemplate service. Represents a row in the &quot;sapp.criteria_template&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.criterias.model.impl.CriteriaTemplateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.criterias.model.impl.CriteriaTemplateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CriteriaTemplate
 * @see tj.criterias.model.impl.CriteriaTemplateImpl
 * @see tj.criterias.model.impl.CriteriaTemplateModelImpl
 * @generated
 */
@ProviderType
public interface CriteriaTemplateModel extends BaseModel<CriteriaTemplate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a criteria template model instance should use the {@link CriteriaTemplate} interface instead.
	 */

	/**
	 * Returns the primary key of this criteria template.
	 *
	 * @return the primary key of this criteria template
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this criteria template.
	 *
	 * @param primaryKey the primary key of this criteria template
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this criteria template.
	 *
	 * @return the uuid of this criteria template
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this criteria template.
	 *
	 * @param uuid the uuid of this criteria template
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the criteria_template_id of this criteria template.
	 *
	 * @return the criteria_template_id of this criteria template
	 */
	public long getCriteria_template_id();

	/**
	 * Sets the criteria_template_id of this criteria template.
	 *
	 * @param criteria_template_id the criteria_template_id of this criteria template
	 */
	public void setCriteria_template_id(long criteria_template_id);

	/**
	 * Returns the criteria_name of this criteria template.
	 *
	 * @return the criteria_name of this criteria template
	 */
	@AutoEscape
	public String getCriteria_name();

	/**
	 * Sets the criteria_name of this criteria template.
	 *
	 * @param criteria_name the criteria_name of this criteria template
	 */
	public void setCriteria_name(String criteria_name);

	/**
	 * Returns the criteria_category_id of this criteria template.
	 *
	 * @return the criteria_category_id of this criteria template
	 */
	public int getCriteria_category_id();

	/**
	 * Sets the criteria_category_id of this criteria template.
	 *
	 * @param criteria_category_id the criteria_category_id of this criteria template
	 */
	public void setCriteria_category_id(int criteria_category_id);

	/**
	 * Returns the created of this criteria template.
	 *
	 * @return the created of this criteria template
	 */
	public Date getCreated();

	/**
	 * Sets the created of this criteria template.
	 *
	 * @param created the created of this criteria template
	 */
	public void setCreated(Date created);

	/**
	 * Returns the updated of this criteria template.
	 *
	 * @return the updated of this criteria template
	 */
	public Date getUpdated();

	/**
	 * Sets the updated of this criteria template.
	 *
	 * @param updated the updated of this criteria template
	 */
	public void setUpdated(Date updated);

	/**
	 * Returns the createdby of this criteria template.
	 *
	 * @return the createdby of this criteria template
	 */
	public long getCreatedby();

	/**
	 * Sets the createdby of this criteria template.
	 *
	 * @param createdby the createdby of this criteria template
	 */
	public void setCreatedby(long createdby);

	/**
	 * Returns the updatedby of this criteria template.
	 *
	 * @return the updatedby of this criteria template
	 */
	public long getUpdatedby();

	/**
	 * Sets the updatedby of this criteria template.
	 *
	 * @param updatedby the updatedby of this criteria template
	 */
	public void setUpdatedby(long updatedby);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.criterias.model.CriteriaTemplate criteriaTemplate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.criterias.model.CriteriaTemplate> toCacheModel();

	@Override
	public tj.criterias.model.CriteriaTemplate toEscapedModel();

	@Override
	public tj.criterias.model.CriteriaTemplate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}