/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.criterias.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CriteriasWeight service. Represents a row in the &quot;sapp.criterias_weight&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.criterias.model.impl.CriteriasWeightModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.criterias.model.impl.CriteriasWeightImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CriteriasWeight
 * @see tj.criterias.model.impl.CriteriasWeightImpl
 * @see tj.criterias.model.impl.CriteriasWeightModelImpl
 * @generated
 */
@ProviderType
public interface CriteriasWeightModel extends BaseModel<CriteriasWeight> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a criterias weight model instance should use the {@link CriteriasWeight} interface instead.
	 */

	/**
	 * Returns the primary key of this criterias weight.
	 *
	 * @return the primary key of this criterias weight
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this criterias weight.
	 *
	 * @param primaryKey the primary key of this criterias weight
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the criterias_weight_id of this criterias weight.
	 *
	 * @return the criterias_weight_id of this criterias weight
	 */
	public long getCriterias_weight_id();

	/**
	 * Sets the criterias_weight_id of this criterias weight.
	 *
	 * @param criterias_weight_id the criterias_weight_id of this criterias weight
	 */
	public void setCriterias_weight_id(long criterias_weight_id);

	/**
	 * Returns the spisok_lotov_id of this criterias weight.
	 *
	 * @return the spisok_lotov_id of this criterias weight
	 */
	public long getSpisok_lotov_id();

	/**
	 * Sets the spisok_lotov_id of this criterias weight.
	 *
	 * @param spisok_lotov_id the spisok_lotov_id of this criterias weight
	 */
	public void setSpisok_lotov_id(long spisok_lotov_id);

	/**
	 * Returns the criteria_category_id of this criterias weight.
	 *
	 * @return the criteria_category_id of this criterias weight
	 */
	public int getCriteria_category_id();

	/**
	 * Sets the criteria_category_id of this criterias weight.
	 *
	 * @param criteria_category_id the criteria_category_id of this criterias weight
	 */
	public void setCriteria_category_id(int criteria_category_id);

	/**
	 * Returns the criterias_weight of this criterias weight.
	 *
	 * @return the criterias_weight of this criterias weight
	 */
	public double getCriterias_weight();

	/**
	 * Sets the criterias_weight of this criterias weight.
	 *
	 * @param criterias_weight the criterias_weight of this criterias weight
	 */
	public void setCriterias_weight(double criterias_weight);

	/**
	 * Returns the created of this criterias weight.
	 *
	 * @return the created of this criterias weight
	 */
	public Date getCreated();

	/**
	 * Sets the created of this criterias weight.
	 *
	 * @param created the created of this criterias weight
	 */
	public void setCreated(Date created);

	/**
	 * Returns the updated of this criterias weight.
	 *
	 * @return the updated of this criterias weight
	 */
	public Date getUpdated();

	/**
	 * Sets the updated of this criterias weight.
	 *
	 * @param updated the updated of this criterias weight
	 */
	public void setUpdated(Date updated);

	/**
	 * Returns the createdby of this criterias weight.
	 *
	 * @return the createdby of this criterias weight
	 */
	public long getCreatedby();

	/**
	 * Sets the createdby of this criterias weight.
	 *
	 * @param createdby the createdby of this criterias weight
	 */
	public void setCreatedby(long createdby);

	/**
	 * Returns the updatedby of this criterias weight.
	 *
	 * @return the updatedby of this criterias weight
	 */
	public long getUpdatedby();

	/**
	 * Sets the updatedby of this criterias weight.
	 *
	 * @param updatedby the updatedby of this criterias weight
	 */
	public void setUpdatedby(long updatedby);

	/**
	 * Returns the passing_score of this criterias weight.
	 *
	 * @return the passing_score of this criterias weight
	 */
	public double getPassing_score();

	/**
	 * Sets the passing_score of this criterias weight.
	 *
	 * @param passing_score the passing_score of this criterias weight
	 */
	public void setPassing_score(double passing_score);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.criterias.model.CriteriasWeight criteriasWeight);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.criterias.model.CriteriasWeight> toCacheModel();

	@Override
	public tj.criterias.model.CriteriasWeight toEscapedModel();

	@Override
	public tj.criterias.model.CriteriasWeight toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}