/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.criterias.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Criteria service. Represents a row in the &quot;sapp.criteria&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.criterias.model.impl.CriteriaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.criterias.model.impl.CriteriaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Criteria
 * @see tj.criterias.model.impl.CriteriaImpl
 * @see tj.criterias.model.impl.CriteriaModelImpl
 * @generated
 */
@ProviderType
public interface CriteriaModel extends BaseModel<Criteria> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a criteria model instance should use the {@link Criteria} interface instead.
	 */

	/**
	 * Returns the primary key of this criteria.
	 *
	 * @return the primary key of this criteria
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this criteria.
	 *
	 * @param primaryKey the primary key of this criteria
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the criteria_id of this criteria.
	 *
	 * @return the criteria_id of this criteria
	 */
	public long getCriteria_id();

	/**
	 * Sets the criteria_id of this criteria.
	 *
	 * @param criteria_id the criteria_id of this criteria
	 */
	public void setCriteria_id(long criteria_id);

	/**
	 * Returns the criteria_name of this criteria.
	 *
	 * @return the criteria_name of this criteria
	 */
	@AutoEscape
	public String getCriteria_name();

	/**
	 * Sets the criteria_name of this criteria.
	 *
	 * @param criteria_name the criteria_name of this criteria
	 */
	public void setCriteria_name(String criteria_name);

	/**
	 * Returns the criteria_weight of this criteria.
	 *
	 * @return the criteria_weight of this criteria
	 */
	public double getCriteria_weight();

	/**
	 * Sets the criteria_weight of this criteria.
	 *
	 * @param criteria_weight the criteria_weight of this criteria
	 */
	public void setCriteria_weight(double criteria_weight);

	/**
	 * Returns the criteria_category_id of this criteria.
	 *
	 * @return the criteria_category_id of this criteria
	 */
	public int getCriteria_category_id();

	/**
	 * Sets the criteria_category_id of this criteria.
	 *
	 * @param criteria_category_id the criteria_category_id of this criteria
	 */
	public void setCriteria_category_id(int criteria_category_id);

	/**
	 * Returns the criteria_description of this criteria.
	 *
	 * @return the criteria_description of this criteria
	 */
	@AutoEscape
	public String getCriteria_description();

	/**
	 * Sets the criteria_description of this criteria.
	 *
	 * @param criteria_description the criteria_description of this criteria
	 */
	public void setCriteria_description(String criteria_description);

	/**
	 * Returns the spisok_lotov_id of this criteria.
	 *
	 * @return the spisok_lotov_id of this criteria
	 */
	public long getSpisok_lotov_id();

	/**
	 * Sets the spisok_lotov_id of this criteria.
	 *
	 * @param spisok_lotov_id the spisok_lotov_id of this criteria
	 */
	public void setSpisok_lotov_id(long spisok_lotov_id);

	/**
	 * Returns the created of this criteria.
	 *
	 * @return the created of this criteria
	 */
	public Date getCreated();

	/**
	 * Sets the created of this criteria.
	 *
	 * @param created the created of this criteria
	 */
	public void setCreated(Date created);

	/**
	 * Returns the updated of this criteria.
	 *
	 * @return the updated of this criteria
	 */
	public Date getUpdated();

	/**
	 * Sets the updated of this criteria.
	 *
	 * @param updated the updated of this criteria
	 */
	public void setUpdated(Date updated);

	/**
	 * Returns the createdby of this criteria.
	 *
	 * @return the createdby of this criteria
	 */
	public long getCreatedby();

	/**
	 * Sets the createdby of this criteria.
	 *
	 * @param createdby the createdby of this criteria
	 */
	public void setCreatedby(long createdby);

	/**
	 * Returns the updatedby of this criteria.
	 *
	 * @return the updatedby of this criteria
	 */
	public long getUpdatedby();

	/**
	 * Sets the updatedby of this criteria.
	 *
	 * @param updatedby the updatedby of this criteria
	 */
	public void setUpdatedby(long updatedby);

	/**
	 * Returns the max_weight of this criteria.
	 *
	 * @return the max_weight of this criteria
	 */
	public int getMax_weight();

	/**
	 * Sets the max_weight of this criteria.
	 *
	 * @param max_weight the max_weight of this criteria
	 */
	public void setMax_weight(int max_weight);

	/**
	 * Returns the min_weight of this criteria.
	 *
	 * @return the min_weight of this criteria
	 */
	public int getMin_weight();

	/**
	 * Sets the min_weight of this criteria.
	 *
	 * @param min_weight the min_weight of this criteria
	 */
	public void setMin_weight(int min_weight);

	/**
	 * Returns the criteria_type_id of this criteria.
	 *
	 * @return the criteria_type_id of this criteria
	 */
	public int getCriteria_type_id();

	/**
	 * Sets the criteria_type_id of this criteria.
	 *
	 * @param criteria_type_id the criteria_type_id of this criteria
	 */
	public void setCriteria_type_id(int criteria_type_id);

	/**
	 * Returns the doc_mandatory of this criteria.
	 *
	 * @return the doc_mandatory of this criteria
	 */
	public boolean getDoc_mandatory();

	/**
	 * Returns <code>true</code> if this criteria is doc_mandatory.
	 *
	 * @return <code>true</code> if this criteria is doc_mandatory; <code>false</code> otherwise
	 */
	public boolean isDoc_mandatory();

	/**
	 * Sets whether this criteria is doc_mandatory.
	 *
	 * @param doc_mandatory the doc_mandatory of this criteria
	 */
	public void setDoc_mandatory(boolean doc_mandatory);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.criterias.model.Criteria criteria);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.criterias.model.Criteria> toCacheModel();

	@Override
	public tj.criterias.model.Criteria toEscapedModel();

	@Override
	public tj.criterias.model.Criteria toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}