/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.criterias.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CriteriaValue service. Represents a row in the &quot;sapp.criteria_value&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.criterias.model.impl.CriteriaValueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.criterias.model.impl.CriteriaValueImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CriteriaValue
 * @see tj.criterias.model.impl.CriteriaValueImpl
 * @see tj.criterias.model.impl.CriteriaValueModelImpl
 * @generated
 */
@ProviderType
public interface CriteriaValueModel extends BaseModel<CriteriaValue> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a criteria value model instance should use the {@link CriteriaValue} interface instead.
	 */

	/**
	 * Returns the primary key of this criteria value.
	 *
	 * @return the primary key of this criteria value
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this criteria value.
	 *
	 * @param primaryKey the primary key of this criteria value
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the criteria_value_id of this criteria value.
	 *
	 * @return the criteria_value_id of this criteria value
	 */
	public long getCriteria_value_id();

	/**
	 * Sets the criteria_value_id of this criteria value.
	 *
	 * @param criteria_value_id the criteria_value_id of this criteria value
	 */
	public void setCriteria_value_id(long criteria_value_id);

	/**
	 * Returns the criteria_id of this criteria value.
	 *
	 * @return the criteria_id of this criteria value
	 */
	public long getCriteria_id();

	/**
	 * Sets the criteria_id of this criteria value.
	 *
	 * @param criteria_id the criteria_id of this criteria value
	 */
	public void setCriteria_id(long criteria_id);

	/**
	 * Returns the userid of this criteria value.
	 *
	 * @return the userid of this criteria value
	 */
	public long getUserid();

	/**
	 * Sets the userid of this criteria value.
	 *
	 * @param userid the userid of this criteria value
	 */
	public void setUserid(long userid);

	/**
	 * Returns the value of this criteria value.
	 *
	 * @return the value of this criteria value
	 */
	public double getValue();

	/**
	 * Sets the value of this criteria value.
	 *
	 * @param value the value of this criteria value
	 */
	public void setValue(double value);

	/**
	 * Returns the description of this criteria value.
	 *
	 * @return the description of this criteria value
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this criteria value.
	 *
	 * @param description the description of this criteria value
	 */
	public void setDescription(String description);

	/**
	 * Returns the created of this criteria value.
	 *
	 * @return the created of this criteria value
	 */
	public Date getCreated();

	/**
	 * Sets the created of this criteria value.
	 *
	 * @param created the created of this criteria value
	 */
	public void setCreated(Date created);

	/**
	 * Returns the updated of this criteria value.
	 *
	 * @return the updated of this criteria value
	 */
	public Date getUpdated();

	/**
	 * Sets the updated of this criteria value.
	 *
	 * @param updated the updated of this criteria value
	 */
	public void setUpdated(Date updated);

	/**
	 * Returns the createdby of this criteria value.
	 *
	 * @return the createdby of this criteria value
	 */
	public long getCreatedby();

	/**
	 * Sets the createdby of this criteria value.
	 *
	 * @param createdby the createdby of this criteria value
	 */
	public void setCreatedby(long createdby);

	/**
	 * Returns the updatedby of this criteria value.
	 *
	 * @return the updatedby of this criteria value
	 */
	public long getUpdatedby();

	/**
	 * Sets the updatedby of this criteria value.
	 *
	 * @param updatedby the updatedby of this criteria value
	 */
	public void setUpdatedby(long updatedby);

	/**
	 * Returns the organization_id of this criteria value.
	 *
	 * @return the organization_id of this criteria value
	 */
	public long getOrganization_id();

	/**
	 * Sets the organization_id of this criteria value.
	 *
	 * @param organization_id the organization_id of this criteria value
	 */
	public void setOrganization_id(long organization_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.criterias.model.CriteriaValue criteriaValue);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.criterias.model.CriteriaValue> toCacheModel();

	@Override
	public tj.criterias.model.CriteriaValue toEscapedModel();

	@Override
	public tj.criterias.model.CriteriaValue toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}