/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.supplier.criteria.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the SupplirCriteria service. Represents a row in the &quot;sapp.supplier_criteria&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.supplier.criteria.model.impl.SupplirCriteriaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.supplier.criteria.model.impl.SupplirCriteriaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupplirCriteria
 * @see tj.supplier.criteria.model.impl.SupplirCriteriaImpl
 * @see tj.supplier.criteria.model.impl.SupplirCriteriaModelImpl
 * @generated
 */
@ProviderType
public interface SupplirCriteriaModel extends BaseModel<SupplirCriteria> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a supplir criteria model instance should use the {@link SupplirCriteria} interface instead.
	 */

	/**
	 * Returns the primary key of this supplir criteria.
	 *
	 * @return the primary key of this supplir criteria
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this supplir criteria.
	 *
	 * @param primaryKey the primary key of this supplir criteria
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the supplier_criteria_id of this supplir criteria.
	 *
	 * @return the supplier_criteria_id of this supplir criteria
	 */
	public long getSupplier_criteria_id();

	/**
	 * Sets the supplier_criteria_id of this supplir criteria.
	 *
	 * @param supplier_criteria_id the supplier_criteria_id of this supplir criteria
	 */
	public void setSupplier_criteria_id(long supplier_criteria_id);

	/**
	 * Returns the criteria_id of this supplir criteria.
	 *
	 * @return the criteria_id of this supplir criteria
	 */
	public long getCriteria_id();

	/**
	 * Sets the criteria_id of this supplir criteria.
	 *
	 * @param criteria_id the criteria_id of this supplir criteria
	 */
	public void setCriteria_id(long criteria_id);

	/**
	 * Returns the organization_id of this supplir criteria.
	 *
	 * @return the organization_id of this supplir criteria
	 */
	public long getOrganization_id();

	/**
	 * Sets the organization_id of this supplir criteria.
	 *
	 * @param organization_id the organization_id of this supplir criteria
	 */
	public void setOrganization_id(long organization_id);

	/**
	 * Returns the description of this supplir criteria.
	 *
	 * @return the description of this supplir criteria
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this supplir criteria.
	 *
	 * @param description the description of this supplir criteria
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.supplier.criteria.model.SupplirCriteria supplirCriteria);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.supplier.criteria.model.SupplirCriteria> toCacheModel();

	@Override
	public tj.supplier.criteria.model.SupplirCriteria toEscapedModel();

	@Override
	public tj.supplier.criteria.model.SupplirCriteria toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}