/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.status.izvewenij.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the StatusIzvewenij service. Represents a row in the &quot;sapp.status_izvewenij&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.status.izvewenij.model.impl.StatusIzvewenijModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.status.izvewenij.model.impl.StatusIzvewenijImpl}.
 * </p>
 *
 * @author falko
 * @see StatusIzvewenij
 * @see tj.status.izvewenij.model.impl.StatusIzvewenijImpl
 * @see tj.status.izvewenij.model.impl.StatusIzvewenijModelImpl
 * @generated
 */
@ProviderType
public interface StatusIzvewenijModel extends BaseModel<StatusIzvewenij> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a status izvewenij model instance should use the {@link StatusIzvewenij} interface instead.
	 */

	/**
	 * Returns the primary key of this status izvewenij.
	 *
	 * @return the primary key of this status izvewenij
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this status izvewenij.
	 *
	 * @param primaryKey the primary key of this status izvewenij
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the status_izvewenij_id of this status izvewenij.
	 *
	 * @return the status_izvewenij_id of this status izvewenij
	 */
	public long getStatus_izvewenij_id();

	/**
	 * Sets the status_izvewenij_id of this status izvewenij.
	 *
	 * @param status_izvewenij_id the status_izvewenij_id of this status izvewenij
	 */
	public void setStatus_izvewenij_id(long status_izvewenij_id);

	/**
	 * Returns the status of this status izvewenij.
	 *
	 * @return the status of this status izvewenij
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this status izvewenij.
	 *
	 * @param status the status of this status izvewenij
	 */
	public void setStatus(String status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.status.izvewenij.model.StatusIzvewenij statusIzvewenij);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.status.izvewenij.model.StatusIzvewenij> toCacheModel();

	@Override
	public tj.status.izvewenij.model.StatusIzvewenij toEscapedModel();

	@Override
	public tj.status.izvewenij.model.StatusIzvewenij toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}