/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.zajavki.ot.postavwikov.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ZajavkiOtPostavwikovTemp service. Represents a row in the &quot;sapp.zajavki_ot_postavwikov_temp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.zajavki.ot.postavwikov.model.impl.ZajavkiOtPostavwikovTempModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.zajavki.ot.postavwikov.model.impl.ZajavkiOtPostavwikovTempImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ZajavkiOtPostavwikovTemp
 * @see tj.zajavki.ot.postavwikov.model.impl.ZajavkiOtPostavwikovTempImpl
 * @see tj.zajavki.ot.postavwikov.model.impl.ZajavkiOtPostavwikovTempModelImpl
 * @generated
 */
@ProviderType
public interface ZajavkiOtPostavwikovTempModel extends BaseModel<ZajavkiOtPostavwikovTemp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a zajavki ot postavwikov temp model instance should use the {@link ZajavkiOtPostavwikovTemp} interface instead.
	 */

	/**
	 * Returns the primary key of this zajavki ot postavwikov temp.
	 *
	 * @return the primary key of this zajavki ot postavwikov temp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this zajavki ot postavwikov temp.
	 *
	 * @param primaryKey the primary key of this zajavki ot postavwikov temp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the zajavki_ot_postavwikov_temp_id of this zajavki ot postavwikov temp.
	 *
	 * @return the zajavki_ot_postavwikov_temp_id of this zajavki ot postavwikov temp
	 */
	public long getZajavki_ot_postavwikov_temp_id();

	/**
	 * Sets the zajavki_ot_postavwikov_temp_id of this zajavki ot postavwikov temp.
	 *
	 * @param zajavki_ot_postavwikov_temp_id the zajavki_ot_postavwikov_temp_id of this zajavki ot postavwikov temp
	 */
	public void setZajavki_ot_postavwikov_temp_id(
		long zajavki_ot_postavwikov_temp_id);

	/**
	 * Returns the izvewenie_id of this zajavki ot postavwikov temp.
	 *
	 * @return the izvewenie_id of this zajavki ot postavwikov temp
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this zajavki ot postavwikov temp.
	 *
	 * @param izvewenie_id the izvewenie_id of this zajavki ot postavwikov temp
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the lot_id of this zajavki ot postavwikov temp.
	 *
	 * @return the lot_id of this zajavki ot postavwikov temp
	 */
	public long getLot_id();

	/**
	 * Sets the lot_id of this zajavki ot postavwikov temp.
	 *
	 * @param lot_id the lot_id of this zajavki ot postavwikov temp
	 */
	public void setLot_id(long lot_id);

	/**
	 * Returns the tovar_id of this zajavki ot postavwikov temp.
	 *
	 * @return the tovar_id of this zajavki ot postavwikov temp
	 */
	public long getTovar_id();

	/**
	 * Sets the tovar_id of this zajavki ot postavwikov temp.
	 *
	 * @param tovar_id the tovar_id of this zajavki ot postavwikov temp
	 */
	public void setTovar_id(long tovar_id);

	/**
	 * Returns the postavwik_id of this zajavki ot postavwikov temp.
	 *
	 * @return the postavwik_id of this zajavki ot postavwikov temp
	 */
	public long getPostavwik_id();

	/**
	 * Sets the postavwik_id of this zajavki ot postavwikov temp.
	 *
	 * @param postavwik_id the postavwik_id of this zajavki ot postavwikov temp
	 */
	public void setPostavwik_id(long postavwik_id);

	/**
	 * Returns the kolichestvo of this zajavki ot postavwikov temp.
	 *
	 * @return the kolichestvo of this zajavki ot postavwikov temp
	 */
	public int getKolichestvo();

	/**
	 * Sets the kolichestvo of this zajavki ot postavwikov temp.
	 *
	 * @param kolichestvo the kolichestvo of this zajavki ot postavwikov temp
	 */
	public void setKolichestvo(int kolichestvo);

	/**
	 * Returns the summa_za_edinicu_tovara of this zajavki ot postavwikov temp.
	 *
	 * @return the summa_za_edinicu_tovara of this zajavki ot postavwikov temp
	 */
	public double getSumma_za_edinicu_tovara();

	/**
	 * Sets the summa_za_edinicu_tovara of this zajavki ot postavwikov temp.
	 *
	 * @param summa_za_edinicu_tovara the summa_za_edinicu_tovara of this zajavki ot postavwikov temp
	 */
	public void setSumma_za_edinicu_tovara(double summa_za_edinicu_tovara);

	/**
	 * Returns the itogo_za_tovar of this zajavki ot postavwikov temp.
	 *
	 * @return the itogo_za_tovar of this zajavki ot postavwikov temp
	 */
	public double getItogo_za_tovar();

	/**
	 * Sets the itogo_za_tovar of this zajavki ot postavwikov temp.
	 *
	 * @param itogo_za_tovar the itogo_za_tovar of this zajavki ot postavwikov temp
	 */
	public void setItogo_za_tovar(double itogo_za_tovar);

	/**
	 * Returns the sozdal of this zajavki ot postavwikov temp.
	 *
	 * @return the sozdal of this zajavki ot postavwikov temp
	 */
	public long getSozdal();

	/**
	 * Sets the sozdal of this zajavki ot postavwikov temp.
	 *
	 * @param sozdal the sozdal of this zajavki ot postavwikov temp
	 */
	public void setSozdal(long sozdal);

	/**
	 * Returns the izmenil of this zajavki ot postavwikov temp.
	 *
	 * @return the izmenil of this zajavki ot postavwikov temp
	 */
	public long getIzmenil();

	/**
	 * Sets the izmenil of this zajavki ot postavwikov temp.
	 *
	 * @param izmenil the izmenil of this zajavki ot postavwikov temp
	 */
	public void setIzmenil(long izmenil);

	/**
	 * Returns the data_sozdanija of this zajavki ot postavwikov temp.
	 *
	 * @return the data_sozdanija of this zajavki ot postavwikov temp
	 */
	public Date getData_sozdanija();

	/**
	 * Sets the data_sozdanija of this zajavki ot postavwikov temp.
	 *
	 * @param data_sozdanija the data_sozdanija of this zajavki ot postavwikov temp
	 */
	public void setData_sozdanija(Date data_sozdanija);

	/**
	 * Returns the data_izmenenija of this zajavki ot postavwikov temp.
	 *
	 * @return the data_izmenenija of this zajavki ot postavwikov temp
	 */
	public Date getData_izmenenija();

	/**
	 * Sets the data_izmenenija of this zajavki ot postavwikov temp.
	 *
	 * @param data_izmenenija the data_izmenenija of this zajavki ot postavwikov temp
	 */
	public void setData_izmenenija(Date data_izmenenija);

	/**
	 * Returns the kod_po_obshhemu_klassifikatoru of this zajavki ot postavwikov temp.
	 *
	 * @return the kod_po_obshhemu_klassifikatoru of this zajavki ot postavwikov temp
	 */
	public long getKod_po_obshhemu_klassifikatoru();

	/**
	 * Sets the kod_po_obshhemu_klassifikatoru of this zajavki ot postavwikov temp.
	 *
	 * @param kod_po_obshhemu_klassifikatoru the kod_po_obshhemu_klassifikatoru of this zajavki ot postavwikov temp
	 */
	public void setKod_po_obshhemu_klassifikatoru(
		long kod_po_obshhemu_klassifikatoru);

	/**
	 * Returns the kod_strany_proizvoditelja of this zajavki ot postavwikov temp.
	 *
	 * @return the kod_strany_proizvoditelja of this zajavki ot postavwikov temp
	 */
	public long getKod_strany_proizvoditelja();

	/**
	 * Sets the kod_strany_proizvoditelja of this zajavki ot postavwikov temp.
	 *
	 * @param kod_strany_proizvoditelja the kod_strany_proizvoditelja of this zajavki ot postavwikov temp
	 */
	public void setKod_strany_proizvoditelja(long kod_strany_proizvoditelja);

	/**
	 * Returns the opisanie_tovara of this zajavki ot postavwikov temp.
	 *
	 * @return the opisanie_tovara of this zajavki ot postavwikov temp
	 */
	@AutoEscape
	public String getOpisanie_tovara();

	/**
	 * Sets the opisanie_tovara of this zajavki ot postavwikov temp.
	 *
	 * @param opisanie_tovara the opisanie_tovara of this zajavki ot postavwikov temp
	 */
	public void setOpisanie_tovara(String opisanie_tovara);

	/**
	 * Returns the predlozhenie_postavwika of this zajavki ot postavwikov temp.
	 *
	 * @return the predlozhenie_postavwika of this zajavki ot postavwikov temp
	 */
	@AutoEscape
	public String getPredlozhenie_postavwika();

	/**
	 * Sets the predlozhenie_postavwika of this zajavki ot postavwikov temp.
	 *
	 * @param predlozhenie_postavwika the predlozhenie_postavwika of this zajavki ot postavwikov temp
	 */
	public void setPredlozhenie_postavwika(String predlozhenie_postavwika);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.zajavki.ot.postavwikov.model.ZajavkiOtPostavwikovTemp zajavkiOtPostavwikovTemp);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.zajavki.ot.postavwikov.model.ZajavkiOtPostavwikovTemp> toCacheModel();

	@Override
	public tj.zajavki.ot.postavwikov.model.ZajavkiOtPostavwikovTemp toEscapedModel();

	@Override
	public tj.zajavki.ot.postavwikov.model.ZajavkiOtPostavwikovTemp toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}