/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.profil.polzovatelej.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.profil.polzovatelej.model.profil_polzovatelej;
import tj.profil.polzovatelej.model.profil_polzovatelejModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the profil_polzovatelej service. Represents a row in the &quot;sapp.profil_polzovatelej&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link profil_polzovatelejModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link profil_polzovatelejImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see profil_polzovatelejImpl
 * @see profil_polzovatelej
 * @see profil_polzovatelejModel
 * @generated
 */
@ProviderType
public class profil_polzovatelejModelImpl extends BaseModelImpl<profil_polzovatelej>
	implements profil_polzovatelejModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a profil_polzovatelej model instance should use the {@link profil_polzovatelej} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.profil_polzovatelej";
	public static final Object[][] TABLE_COLUMNS = {
			{ "profil_polzovatelej_id", Types.BIGINT },
			{ "polzovatel_id", Types.BIGINT },
			{ "inicialy", Types.VARCHAR },
			{ "kontaktnyj_telefon", Types.VARCHAR },
			{ "je_pochta", Types.VARCHAR },
			{ "sozdal", Types.BIGINT },
			{ "izmenil", Types.BIGINT },
			{ "data_sozdanija", Types.TIMESTAMP },
			{ "data_izmenenija", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("profil_polzovatelej_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("polzovatel_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("inicialy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("kontaktnyj_telefon", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("je_pochta", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sozdal", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("izmenil", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("data_sozdanija", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("data_izmenenija", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.profil_polzovatelej (profil_polzovatelej_id LONG not null primary key,polzovatel_id LONG,inicialy VARCHAR(75) null,kontaktnyj_telefon VARCHAR(75) null,je_pochta VARCHAR(75) null,sozdal LONG,izmenil LONG,data_sozdanija DATE null,data_izmenenija DATE null)";
	public static final String TABLE_SQL_DROP = "drop table sapp.profil_polzovatelej";
	public static final String ORDER_BY_JPQL = " ORDER BY profil_polzovatelej.profil_polzovatelej_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.profil_polzovatelej.profil_polzovatelej_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.profil.polzovatelej.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.profil.polzovatelej.model.profil_polzovatelej"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.profil.polzovatelej.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.profil.polzovatelej.model.profil_polzovatelej"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.profil.polzovatelej.service.util.ServiceProps.get(
				"lock.expiration.time.tj.profil.polzovatelej.model.profil_polzovatelej"));

	public profil_polzovatelejModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _profil_polzovatelej_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProfil_polzovatelej_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _profil_polzovatelej_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return profil_polzovatelej.class;
	}

	@Override
	public String getModelClassName() {
		return profil_polzovatelej.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("profil_polzovatelej_id", getProfil_polzovatelej_id());
		attributes.put("polzovatel_id", getPolzovatel_id());
		attributes.put("inicialy", getInicialy());
		attributes.put("kontaktnyj_telefon", getKontaktnyj_telefon());
		attributes.put("je_pochta", getJe_pochta());
		attributes.put("sozdal", getSozdal());
		attributes.put("izmenil", getIzmenil());
		attributes.put("data_sozdanija", getData_sozdanija());
		attributes.put("data_izmenenija", getData_izmenenija());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long profil_polzovatelej_id = (Long)attributes.get(
				"profil_polzovatelej_id");

		if (profil_polzovatelej_id != null) {
			setProfil_polzovatelej_id(profil_polzovatelej_id);
		}

		Long polzovatel_id = (Long)attributes.get("polzovatel_id");

		if (polzovatel_id != null) {
			setPolzovatel_id(polzovatel_id);
		}

		String inicialy = (String)attributes.get("inicialy");

		if (inicialy != null) {
			setInicialy(inicialy);
		}

		String kontaktnyj_telefon = (String)attributes.get("kontaktnyj_telefon");

		if (kontaktnyj_telefon != null) {
			setKontaktnyj_telefon(kontaktnyj_telefon);
		}

		String je_pochta = (String)attributes.get("je_pochta");

		if (je_pochta != null) {
			setJe_pochta(je_pochta);
		}

		Long sozdal = (Long)attributes.get("sozdal");

		if (sozdal != null) {
			setSozdal(sozdal);
		}

		Long izmenil = (Long)attributes.get("izmenil");

		if (izmenil != null) {
			setIzmenil(izmenil);
		}

		Date data_sozdanija = (Date)attributes.get("data_sozdanija");

		if (data_sozdanija != null) {
			setData_sozdanija(data_sozdanija);
		}

		Date data_izmenenija = (Date)attributes.get("data_izmenenija");

		if (data_izmenenija != null) {
			setData_izmenenija(data_izmenenija);
		}
	}

	@Override
	public long getProfil_polzovatelej_id() {
		return _profil_polzovatelej_id;
	}

	@Override
	public void setProfil_polzovatelej_id(long profil_polzovatelej_id) {
		_profil_polzovatelej_id = profil_polzovatelej_id;
	}

	@Override
	public long getPolzovatel_id() {
		return _polzovatel_id;
	}

	@Override
	public void setPolzovatel_id(long polzovatel_id) {
		_polzovatel_id = polzovatel_id;
	}

	@Override
	public String getInicialy() {
		if (_inicialy == null) {
			return StringPool.BLANK;
		}
		else {
			return _inicialy;
		}
	}

	@Override
	public void setInicialy(String inicialy) {
		_inicialy = inicialy;
	}

	@Override
	public String getKontaktnyj_telefon() {
		if (_kontaktnyj_telefon == null) {
			return StringPool.BLANK;
		}
		else {
			return _kontaktnyj_telefon;
		}
	}

	@Override
	public void setKontaktnyj_telefon(String kontaktnyj_telefon) {
		_kontaktnyj_telefon = kontaktnyj_telefon;
	}

	@Override
	public String getJe_pochta() {
		if (_je_pochta == null) {
			return StringPool.BLANK;
		}
		else {
			return _je_pochta;
		}
	}

	@Override
	public void setJe_pochta(String je_pochta) {
		_je_pochta = je_pochta;
	}

	@Override
	public long getSozdal() {
		return _sozdal;
	}

	@Override
	public void setSozdal(long sozdal) {
		_sozdal = sozdal;
	}

	@Override
	public long getIzmenil() {
		return _izmenil;
	}

	@Override
	public void setIzmenil(long izmenil) {
		_izmenil = izmenil;
	}

	@Override
	public Date getData_sozdanija() {
		return _data_sozdanija;
	}

	@Override
	public void setData_sozdanija(Date data_sozdanija) {
		_data_sozdanija = data_sozdanija;
	}

	@Override
	public Date getData_izmenenija() {
		return _data_izmenenija;
	}

	@Override
	public void setData_izmenenija(Date data_izmenenija) {
		_data_izmenenija = data_izmenenija;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			profil_polzovatelej.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public profil_polzovatelej toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (profil_polzovatelej)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		profil_polzovatelejImpl profil_polzovatelejImpl = new profil_polzovatelejImpl();

		profil_polzovatelejImpl.setProfil_polzovatelej_id(getProfil_polzovatelej_id());
		profil_polzovatelejImpl.setPolzovatel_id(getPolzovatel_id());
		profil_polzovatelejImpl.setInicialy(getInicialy());
		profil_polzovatelejImpl.setKontaktnyj_telefon(getKontaktnyj_telefon());
		profil_polzovatelejImpl.setJe_pochta(getJe_pochta());
		profil_polzovatelejImpl.setSozdal(getSozdal());
		profil_polzovatelejImpl.setIzmenil(getIzmenil());
		profil_polzovatelejImpl.setData_sozdanija(getData_sozdanija());
		profil_polzovatelejImpl.setData_izmenenija(getData_izmenenija());

		profil_polzovatelejImpl.resetOriginalValues();

		return profil_polzovatelejImpl;
	}

	@Override
	public int compareTo(profil_polzovatelej profil_polzovatelej) {
		long primaryKey = profil_polzovatelej.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof profil_polzovatelej)) {
			return false;
		}

		profil_polzovatelej profil_polzovatelej = (profil_polzovatelej)obj;

		long primaryKey = profil_polzovatelej.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<profil_polzovatelej> toCacheModel() {
		profil_polzovatelejCacheModel profil_polzovatelejCacheModel = new profil_polzovatelejCacheModel();

		profil_polzovatelejCacheModel.profil_polzovatelej_id = getProfil_polzovatelej_id();

		profil_polzovatelejCacheModel.polzovatel_id = getPolzovatel_id();

		profil_polzovatelejCacheModel.inicialy = getInicialy();

		String inicialy = profil_polzovatelejCacheModel.inicialy;

		if ((inicialy != null) && (inicialy.length() == 0)) {
			profil_polzovatelejCacheModel.inicialy = null;
		}

		profil_polzovatelejCacheModel.kontaktnyj_telefon = getKontaktnyj_telefon();

		String kontaktnyj_telefon = profil_polzovatelejCacheModel.kontaktnyj_telefon;

		if ((kontaktnyj_telefon != null) && (kontaktnyj_telefon.length() == 0)) {
			profil_polzovatelejCacheModel.kontaktnyj_telefon = null;
		}

		profil_polzovatelejCacheModel.je_pochta = getJe_pochta();

		String je_pochta = profil_polzovatelejCacheModel.je_pochta;

		if ((je_pochta != null) && (je_pochta.length() == 0)) {
			profil_polzovatelejCacheModel.je_pochta = null;
		}

		profil_polzovatelejCacheModel.sozdal = getSozdal();

		profil_polzovatelejCacheModel.izmenil = getIzmenil();

		Date data_sozdanija = getData_sozdanija();

		if (data_sozdanija != null) {
			profil_polzovatelejCacheModel.data_sozdanija = data_sozdanija.getTime();
		}
		else {
			profil_polzovatelejCacheModel.data_sozdanija = Long.MIN_VALUE;
		}

		Date data_izmenenija = getData_izmenenija();

		if (data_izmenenija != null) {
			profil_polzovatelejCacheModel.data_izmenenija = data_izmenenija.getTime();
		}
		else {
			profil_polzovatelejCacheModel.data_izmenenija = Long.MIN_VALUE;
		}

		return profil_polzovatelejCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{profil_polzovatelej_id=");
		sb.append(getProfil_polzovatelej_id());
		sb.append(", polzovatel_id=");
		sb.append(getPolzovatel_id());
		sb.append(", inicialy=");
		sb.append(getInicialy());
		sb.append(", kontaktnyj_telefon=");
		sb.append(getKontaktnyj_telefon());
		sb.append(", je_pochta=");
		sb.append(getJe_pochta());
		sb.append(", sozdal=");
		sb.append(getSozdal());
		sb.append(", izmenil=");
		sb.append(getIzmenil());
		sb.append(", data_sozdanija=");
		sb.append(getData_sozdanija());
		sb.append(", data_izmenenija=");
		sb.append(getData_izmenenija());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("tj.profil.polzovatelej.model.profil_polzovatelej");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>profil_polzovatelej_id</column-name><column-value><![CDATA[");
		sb.append(getProfil_polzovatelej_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>polzovatel_id</column-name><column-value><![CDATA[");
		sb.append(getPolzovatel_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inicialy</column-name><column-value><![CDATA[");
		sb.append(getInicialy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kontaktnyj_telefon</column-name><column-value><![CDATA[");
		sb.append(getKontaktnyj_telefon());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>je_pochta</column-name><column-value><![CDATA[");
		sb.append(getJe_pochta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sozdal</column-name><column-value><![CDATA[");
		sb.append(getSozdal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izmenil</column-name><column-value><![CDATA[");
		sb.append(getIzmenil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data_sozdanija</column-name><column-value><![CDATA[");
		sb.append(getData_sozdanija());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data_izmenenija</column-name><column-value><![CDATA[");
		sb.append(getData_izmenenija());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = profil_polzovatelej.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			profil_polzovatelej.class
		};
	private long _profil_polzovatelej_id;
	private long _polzovatel_id;
	private String _inicialy;
	private String _kontaktnyj_telefon;
	private String _je_pochta;
	private long _sozdal;
	private long _izmenil;
	private Date _data_sozdanija;
	private Date _data_izmenenija;
	private profil_polzovatelej _escapedModel;
}