/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.izvewenija.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Izvewenija service. Represents a row in the &quot;sapp.izvewenija&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.izvewenija.model.impl.IzvewenijaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.izvewenija.model.impl.IzvewenijaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Izvewenija
 * @see tj.izvewenija.model.impl.IzvewenijaImpl
 * @see tj.izvewenija.model.impl.IzvewenijaModelImpl
 * @generated
 */
@ProviderType
public interface IzvewenijaModel extends BaseModel<Izvewenija> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a izvewenija model instance should use the {@link Izvewenija} interface instead.
	 */

	/**
	 * Returns the primary key of this izvewenija.
	 *
	 * @return the primary key of this izvewenija
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this izvewenija.
	 *
	 * @param primaryKey the primary key of this izvewenija
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data_izmenenija of this izvewenija.
	 *
	 * @return the data_izmenenija of this izvewenija
	 */
	public Date getData_izmenenija();

	/**
	 * Sets the data_izmenenija of this izvewenija.
	 *
	 * @param data_izmenenija the data_izmenenija of this izvewenija
	 */
	public void setData_izmenenija(Date data_izmenenija);

	/**
	 * Returns the data_sozdanija of this izvewenija.
	 *
	 * @return the data_sozdanija of this izvewenija
	 */
	public Date getData_sozdanija();

	/**
	 * Sets the data_sozdanija of this izvewenija.
	 *
	 * @param data_sozdanija the data_sozdanija of this izvewenija
	 */
	public void setData_sozdanija(Date data_sozdanija);

	/**
	 * Returns the izmenil of this izvewenija.
	 *
	 * @return the izmenil of this izvewenija
	 */
	public long getIzmenil();

	/**
	 * Sets the izmenil of this izvewenija.
	 *
	 * @param izmenil the izmenil of this izvewenija
	 */
	public void setIzmenil(long izmenil);

	/**
	 * Returns the izvewenija_id of this izvewenija.
	 *
	 * @return the izvewenija_id of this izvewenija
	 */
	public long getIzvewenija_id();

	/**
	 * Sets the izvewenija_id of this izvewenija.
	 *
	 * @param izvewenija_id the izvewenija_id of this izvewenija
	 */
	public void setIzvewenija_id(long izvewenija_id);

	/**
	 * Returns the kod_id of this izvewenija.
	 *
	 * @return the kod_id of this izvewenija
	 */
	public long getKod_id();

	/**
	 * Sets the kod_id of this izvewenija.
	 *
	 * @param kod_id the kod_id of this izvewenija
	 */
	public void setKod_id(long kod_id);

	/**
	 * Returns the naimenovanie of this izvewenija.
	 *
	 * @return the naimenovanie of this izvewenija
	 */
	@AutoEscape
	public String getNaimenovanie();

	/**
	 * Sets the naimenovanie of this izvewenija.
	 *
	 * @param naimenovanie the naimenovanie of this izvewenija
	 */
	public void setNaimenovanie(String naimenovanie);

	/**
	 * Returns the organizacija_id of this izvewenija.
	 *
	 * @return the organizacija_id of this izvewenija
	 */
	public long getOrganizacija_id();

	/**
	 * Sets the organizacija_id of this izvewenija.
	 *
	 * @param organizacija_id the organizacija_id of this izvewenija
	 */
	public void setOrganizacija_id(long organizacija_id);

	/**
	 * Returns the sostojanie_id of this izvewenija.
	 *
	 * @return the sostojanie_id of this izvewenija
	 */
	public long getSostojanie_id();

	/**
	 * Sets the sostojanie_id of this izvewenija.
	 *
	 * @param sostojanie_id the sostojanie_id of this izvewenija
	 */
	public void setSostojanie_id(long sostojanie_id);

	/**
	 * Returns the sozdal of this izvewenija.
	 *
	 * @return the sozdal of this izvewenija
	 */
	public long getSozdal();

	/**
	 * Sets the sozdal of this izvewenija.
	 *
	 * @param sozdal the sozdal of this izvewenija
	 */
	public void setSozdal(long sozdal);

	/**
	 * Returns the status_id of this izvewenija.
	 *
	 * @return the status_id of this izvewenija
	 */
	public long getStatus_id();

	/**
	 * Sets the status_id of this izvewenija.
	 *
	 * @param status_id the status_id of this izvewenija
	 */
	public void setStatus_id(long status_id);

	/**
	 * Returns the tip_izvewenija_id of this izvewenija.
	 *
	 * @return the tip_izvewenija_id of this izvewenija
	 */
	public long getTip_izvewenija_id();

	/**
	 * Sets the tip_izvewenija_id of this izvewenija.
	 *
	 * @param tip_izvewenija_id the tip_izvewenija_id of this izvewenija
	 */
	public void setTip_izvewenija_id(long tip_izvewenija_id);

	/**
	 * Returns the vyshestojawaja_organizacija_id of this izvewenija.
	 *
	 * @return the vyshestojawaja_organizacija_id of this izvewenija
	 */
	public long getVyshestojawaja_organizacija_id();

	/**
	 * Sets the vyshestojawaja_organizacija_id of this izvewenija.
	 *
	 * @param vyshestojawaja_organizacija_id the vyshestojawaja_organizacija_id of this izvewenija
	 */
	public void setVyshestojawaja_organizacija_id(
		long vyshestojawaja_organizacija_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.izvewenija.model.Izvewenija izvewenija);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.izvewenija.model.Izvewenija> toCacheModel();

	@Override
	public tj.izvewenija.model.Izvewenija toEscapedModel();

	@Override
	public tj.izvewenija.model.Izvewenija toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}