/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.dokumenty.postavwika.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.dokumenty.postavwika.model.DokumentyPostavwika;
import tj.dokumenty.postavwika.model.DokumentyPostavwikaModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the DokumentyPostavwika service. Represents a row in the &quot;Dokumenty_postavwika_DokumentyPostavwika&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link DokumentyPostavwikaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DokumentyPostavwikaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DokumentyPostavwikaImpl
 * @see DokumentyPostavwika
 * @see DokumentyPostavwikaModel
 * @generated
 */
@ProviderType
public class DokumentyPostavwikaModelImpl extends BaseModelImpl<DokumentyPostavwika>
	implements DokumentyPostavwikaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dokumenty postavwika model instance should use the {@link DokumentyPostavwika} interface instead.
	 */
	public static final String TABLE_NAME = "Dokumenty_postavwika_DokumentyPostavwika";
	public static final Object[][] TABLE_COLUMNS = {
			{ "dokumenty_postavwika_id", Types.BIGINT },
			{ "postavwik_id", Types.BIGINT },
			{ "tip_dokumenta", Types.INTEGER },
			{ "nazvanie_dokumenta", Types.VARCHAR },
			{ "imja_fajla", Types.VARCHAR },
			{ "zagruzil", Types.BIGINT },
			{ "data_zagruzki", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("dokumenty_postavwika_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("postavwik_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tip_dokumenta", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("nazvanie_dokumenta", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imja_fajla", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("zagruzil", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("data_zagruzki", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table Dokumenty_postavwika_DokumentyPostavwika (dokumenty_postavwika_id LONG not null primary key,postavwik_id LONG,tip_dokumenta INTEGER,nazvanie_dokumenta VARCHAR(75) null,imja_fajla VARCHAR(75) null,zagruzil LONG,data_zagruzki DATE null)";
	public static final String TABLE_SQL_DROP = "drop table Dokumenty_postavwika_DokumentyPostavwika";
	public static final String ORDER_BY_JPQL = " ORDER BY dokumentyPostavwika.dokumenty_postavwika_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Dokumenty_postavwika_DokumentyPostavwika.dokumenty_postavwika_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.dokumenty.postavwika.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.dokumenty.postavwika.model.DokumentyPostavwika"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.dokumenty.postavwika.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.dokumenty.postavwika.model.DokumentyPostavwika"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(tj.dokumenty.postavwika.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.tj.dokumenty.postavwika.model.DokumentyPostavwika"),
			true);
	public static final long POSTAVWIK_ID_COLUMN_BITMASK = 1L;
	public static final long DOKUMENTY_POSTAVWIKA_ID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.dokumenty.postavwika.service.util.ServiceProps.get(
				"lock.expiration.time.tj.dokumenty.postavwika.model.DokumentyPostavwika"));

	public DokumentyPostavwikaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dokumenty_postavwika_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDokumenty_postavwika_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dokumenty_postavwika_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DokumentyPostavwika.class;
	}

	@Override
	public String getModelClassName() {
		return DokumentyPostavwika.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("dokumenty_postavwika_id", getDokumenty_postavwika_id());
		attributes.put("postavwik_id", getPostavwik_id());
		attributes.put("tip_dokumenta", getTip_dokumenta());
		attributes.put("nazvanie_dokumenta", getNazvanie_dokumenta());
		attributes.put("imja_fajla", getImja_fajla());
		attributes.put("zagruzil", getZagruzil());
		attributes.put("data_zagruzki", getData_zagruzki());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long dokumenty_postavwika_id = (Long)attributes.get(
				"dokumenty_postavwika_id");

		if (dokumenty_postavwika_id != null) {
			setDokumenty_postavwika_id(dokumenty_postavwika_id);
		}

		Long postavwik_id = (Long)attributes.get("postavwik_id");

		if (postavwik_id != null) {
			setPostavwik_id(postavwik_id);
		}

		Integer tip_dokumenta = (Integer)attributes.get("tip_dokumenta");

		if (tip_dokumenta != null) {
			setTip_dokumenta(tip_dokumenta);
		}

		String nazvanie_dokumenta = (String)attributes.get("nazvanie_dokumenta");

		if (nazvanie_dokumenta != null) {
			setNazvanie_dokumenta(nazvanie_dokumenta);
		}

		String imja_fajla = (String)attributes.get("imja_fajla");

		if (imja_fajla != null) {
			setImja_fajla(imja_fajla);
		}

		Long zagruzil = (Long)attributes.get("zagruzil");

		if (zagruzil != null) {
			setZagruzil(zagruzil);
		}

		Date data_zagruzki = (Date)attributes.get("data_zagruzki");

		if (data_zagruzki != null) {
			setData_zagruzki(data_zagruzki);
		}
	}

	@Override
	public long getDokumenty_postavwika_id() {
		return _dokumenty_postavwika_id;
	}

	@Override
	public void setDokumenty_postavwika_id(long dokumenty_postavwika_id) {
		_dokumenty_postavwika_id = dokumenty_postavwika_id;
	}

	@Override
	public long getPostavwik_id() {
		return _postavwik_id;
	}

	@Override
	public void setPostavwik_id(long postavwik_id) {
		_columnBitmask |= POSTAVWIK_ID_COLUMN_BITMASK;

		if (!_setOriginalPostavwik_id) {
			_setOriginalPostavwik_id = true;

			_originalPostavwik_id = _postavwik_id;
		}

		_postavwik_id = postavwik_id;
	}

	public long getOriginalPostavwik_id() {
		return _originalPostavwik_id;
	}

	@Override
	public int getTip_dokumenta() {
		return _tip_dokumenta;
	}

	@Override
	public void setTip_dokumenta(int tip_dokumenta) {
		_tip_dokumenta = tip_dokumenta;
	}

	@Override
	public String getNazvanie_dokumenta() {
		if (_nazvanie_dokumenta == null) {
			return StringPool.BLANK;
		}
		else {
			return _nazvanie_dokumenta;
		}
	}

	@Override
	public void setNazvanie_dokumenta(String nazvanie_dokumenta) {
		_nazvanie_dokumenta = nazvanie_dokumenta;
	}

	@Override
	public String getImja_fajla() {
		if (_imja_fajla == null) {
			return StringPool.BLANK;
		}
		else {
			return _imja_fajla;
		}
	}

	@Override
	public void setImja_fajla(String imja_fajla) {
		_imja_fajla = imja_fajla;
	}

	@Override
	public long getZagruzil() {
		return _zagruzil;
	}

	@Override
	public void setZagruzil(long zagruzil) {
		_zagruzil = zagruzil;
	}

	@Override
	public Date getData_zagruzki() {
		return _data_zagruzki;
	}

	@Override
	public void setData_zagruzki(Date data_zagruzki) {
		_data_zagruzki = data_zagruzki;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			DokumentyPostavwika.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DokumentyPostavwika toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DokumentyPostavwika)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DokumentyPostavwikaImpl dokumentyPostavwikaImpl = new DokumentyPostavwikaImpl();

		dokumentyPostavwikaImpl.setDokumenty_postavwika_id(getDokumenty_postavwika_id());
		dokumentyPostavwikaImpl.setPostavwik_id(getPostavwik_id());
		dokumentyPostavwikaImpl.setTip_dokumenta(getTip_dokumenta());
		dokumentyPostavwikaImpl.setNazvanie_dokumenta(getNazvanie_dokumenta());
		dokumentyPostavwikaImpl.setImja_fajla(getImja_fajla());
		dokumentyPostavwikaImpl.setZagruzil(getZagruzil());
		dokumentyPostavwikaImpl.setData_zagruzki(getData_zagruzki());

		dokumentyPostavwikaImpl.resetOriginalValues();

		return dokumentyPostavwikaImpl;
	}

	@Override
	public int compareTo(DokumentyPostavwika dokumentyPostavwika) {
		long primaryKey = dokumentyPostavwika.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DokumentyPostavwika)) {
			return false;
		}

		DokumentyPostavwika dokumentyPostavwika = (DokumentyPostavwika)obj;

		long primaryKey = dokumentyPostavwika.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		DokumentyPostavwikaModelImpl dokumentyPostavwikaModelImpl = this;

		dokumentyPostavwikaModelImpl._originalPostavwik_id = dokumentyPostavwikaModelImpl._postavwik_id;

		dokumentyPostavwikaModelImpl._setOriginalPostavwik_id = false;

		dokumentyPostavwikaModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DokumentyPostavwika> toCacheModel() {
		DokumentyPostavwikaCacheModel dokumentyPostavwikaCacheModel = new DokumentyPostavwikaCacheModel();

		dokumentyPostavwikaCacheModel.dokumenty_postavwika_id = getDokumenty_postavwika_id();

		dokumentyPostavwikaCacheModel.postavwik_id = getPostavwik_id();

		dokumentyPostavwikaCacheModel.tip_dokumenta = getTip_dokumenta();

		dokumentyPostavwikaCacheModel.nazvanie_dokumenta = getNazvanie_dokumenta();

		String nazvanie_dokumenta = dokumentyPostavwikaCacheModel.nazvanie_dokumenta;

		if ((nazvanie_dokumenta != null) && (nazvanie_dokumenta.length() == 0)) {
			dokumentyPostavwikaCacheModel.nazvanie_dokumenta = null;
		}

		dokumentyPostavwikaCacheModel.imja_fajla = getImja_fajla();

		String imja_fajla = dokumentyPostavwikaCacheModel.imja_fajla;

		if ((imja_fajla != null) && (imja_fajla.length() == 0)) {
			dokumentyPostavwikaCacheModel.imja_fajla = null;
		}

		dokumentyPostavwikaCacheModel.zagruzil = getZagruzil();

		Date data_zagruzki = getData_zagruzki();

		if (data_zagruzki != null) {
			dokumentyPostavwikaCacheModel.data_zagruzki = data_zagruzki.getTime();
		}
		else {
			dokumentyPostavwikaCacheModel.data_zagruzki = Long.MIN_VALUE;
		}

		return dokumentyPostavwikaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{dokumenty_postavwika_id=");
		sb.append(getDokumenty_postavwika_id());
		sb.append(", postavwik_id=");
		sb.append(getPostavwik_id());
		sb.append(", tip_dokumenta=");
		sb.append(getTip_dokumenta());
		sb.append(", nazvanie_dokumenta=");
		sb.append(getNazvanie_dokumenta());
		sb.append(", imja_fajla=");
		sb.append(getImja_fajla());
		sb.append(", zagruzil=");
		sb.append(getZagruzil());
		sb.append(", data_zagruzki=");
		sb.append(getData_zagruzki());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("tj.dokumenty.postavwika.model.DokumentyPostavwika");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>dokumenty_postavwika_id</column-name><column-value><![CDATA[");
		sb.append(getDokumenty_postavwika_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>postavwik_id</column-name><column-value><![CDATA[");
		sb.append(getPostavwik_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tip_dokumenta</column-name><column-value><![CDATA[");
		sb.append(getTip_dokumenta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nazvanie_dokumenta</column-name><column-value><![CDATA[");
		sb.append(getNazvanie_dokumenta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imja_fajla</column-name><column-value><![CDATA[");
		sb.append(getImja_fajla());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>zagruzil</column-name><column-value><![CDATA[");
		sb.append(getZagruzil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data_zagruzki</column-name><column-value><![CDATA[");
		sb.append(getData_zagruzki());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = DokumentyPostavwika.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			DokumentyPostavwika.class
		};
	private long _dokumenty_postavwika_id;
	private long _postavwik_id;
	private long _originalPostavwik_id;
	private boolean _setOriginalPostavwik_id;
	private int _tip_dokumenta;
	private String _nazvanie_dokumenta;
	private String _imja_fajla;
	private long _zagruzil;
	private Date _data_zagruzki;
	private long _columnBitmask;
	private DokumentyPostavwika _escapedModel;
}