/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.polzovateli.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.polzovateli.model.Polzovateli;
import tj.polzovateli.model.PolzovateliModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Polzovateli service. Represents a row in the &quot;sapp.polzovateli&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link PolzovateliModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PolzovateliImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PolzovateliImpl
 * @see Polzovateli
 * @see PolzovateliModel
 * @generated
 */
@ProviderType
public class PolzovateliModelImpl extends BaseModelImpl<Polzovateli>
	implements PolzovateliModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a polzovateli model instance should use the {@link Polzovateli} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.polzovateli";
	public static final Object[][] TABLE_COLUMNS = {
			{ "polzovateli_id", Types.BIGINT },
			{ "organizacija_id", Types.BIGINT },
			{ "tip_organizacii_id", Types.INTEGER },
			{ "rol_id", Types.INTEGER },
			{ "imja_polzovatelja", Types.VARCHAR },
			{ "parol", Types.VARCHAR },
			{ "aktivnost", Types.INTEGER },
			{ "sozdal", Types.BIGINT },
			{ "izmenil", Types.BIGINT },
			{ "data_sozdanija", Types.TIMESTAMP },
			{ "data_izmenenija", Types.TIMESTAMP },
			{ "podrazdelenije_id", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("polzovateli_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("organizacija_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tip_organizacii_id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("rol_id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("imja_polzovatelja", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("parol", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("aktivnost", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("sozdal", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("izmenil", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("data_sozdanija", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("data_izmenenija", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("podrazdelenije_id", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.polzovateli (polzovateli_id LONG not null primary key,organizacija_id LONG,tip_organizacii_id INTEGER,rol_id INTEGER,imja_polzovatelja VARCHAR(75) null,parol VARCHAR(75) null,aktivnost INTEGER,sozdal LONG,izmenil LONG,data_sozdanija DATE null,data_izmenenija DATE null,podrazdelenije_id INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table sapp.polzovateli";
	public static final String ORDER_BY_JPQL = " ORDER BY polzovateli.polzovateli_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.polzovateli.polzovateli_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.polzovateli.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.polzovateli.model.Polzovateli"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.polzovateli.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.polzovateli.model.Polzovateli"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.polzovateli.service.util.ServiceProps.get(
				"lock.expiration.time.tj.polzovateli.model.Polzovateli"));

	public PolzovateliModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _polzovateli_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPolzovateli_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _polzovateli_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Polzovateli.class;
	}

	@Override
	public String getModelClassName() {
		return Polzovateli.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("polzovateli_id", getPolzovateli_id());
		attributes.put("organizacija_id", getOrganizacija_id());
		attributes.put("tip_organizacii_id", getTip_organizacii_id());
		attributes.put("rol_id", getRol_id());
		attributes.put("imja_polzovatelja", getImja_polzovatelja());
		attributes.put("parol", getParol());
		attributes.put("aktivnost", getAktivnost());
		attributes.put("sozdal", getSozdal());
		attributes.put("izmenil", getIzmenil());
		attributes.put("data_sozdanija", getData_sozdanija());
		attributes.put("data_izmenenija", getData_izmenenija());
		attributes.put("podrazdelenije_id", getPodrazdelenije_id());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long polzovateli_id = (Long)attributes.get("polzovateli_id");

		if (polzovateli_id != null) {
			setPolzovateli_id(polzovateli_id);
		}

		Long organizacija_id = (Long)attributes.get("organizacija_id");

		if (organizacija_id != null) {
			setOrganizacija_id(organizacija_id);
		}

		Integer tip_organizacii_id = (Integer)attributes.get(
				"tip_organizacii_id");

		if (tip_organizacii_id != null) {
			setTip_organizacii_id(tip_organizacii_id);
		}

		Integer rol_id = (Integer)attributes.get("rol_id");

		if (rol_id != null) {
			setRol_id(rol_id);
		}

		String imja_polzovatelja = (String)attributes.get("imja_polzovatelja");

		if (imja_polzovatelja != null) {
			setImja_polzovatelja(imja_polzovatelja);
		}

		String parol = (String)attributes.get("parol");

		if (parol != null) {
			setParol(parol);
		}

		Integer aktivnost = (Integer)attributes.get("aktivnost");

		if (aktivnost != null) {
			setAktivnost(aktivnost);
		}

		Long sozdal = (Long)attributes.get("sozdal");

		if (sozdal != null) {
			setSozdal(sozdal);
		}

		Long izmenil = (Long)attributes.get("izmenil");

		if (izmenil != null) {
			setIzmenil(izmenil);
		}

		Date data_sozdanija = (Date)attributes.get("data_sozdanija");

		if (data_sozdanija != null) {
			setData_sozdanija(data_sozdanija);
		}

		Date data_izmenenija = (Date)attributes.get("data_izmenenija");

		if (data_izmenenija != null) {
			setData_izmenenija(data_izmenenija);
		}

		Integer podrazdelenije_id = (Integer)attributes.get("podrazdelenije_id");

		if (podrazdelenije_id != null) {
			setPodrazdelenije_id(podrazdelenije_id);
		}
	}

	@Override
	public long getPolzovateli_id() {
		return _polzovateli_id;
	}

	@Override
	public void setPolzovateli_id(long polzovateli_id) {
		_polzovateli_id = polzovateli_id;
	}

	@Override
	public long getOrganizacija_id() {
		return _organizacija_id;
	}

	@Override
	public void setOrganizacija_id(long organizacija_id) {
		_organizacija_id = organizacija_id;
	}

	@Override
	public int getTip_organizacii_id() {
		return _tip_organizacii_id;
	}

	@Override
	public void setTip_organizacii_id(int tip_organizacii_id) {
		_tip_organizacii_id = tip_organizacii_id;
	}

	@Override
	public int getRol_id() {
		return _rol_id;
	}

	@Override
	public void setRol_id(int rol_id) {
		_rol_id = rol_id;
	}

	@Override
	public String getImja_polzovatelja() {
		if (_imja_polzovatelja == null) {
			return StringPool.BLANK;
		}
		else {
			return _imja_polzovatelja;
		}
	}

	@Override
	public void setImja_polzovatelja(String imja_polzovatelja) {
		_imja_polzovatelja = imja_polzovatelja;
	}

	@Override
	public String getParol() {
		if (_parol == null) {
			return StringPool.BLANK;
		}
		else {
			return _parol;
		}
	}

	@Override
	public void setParol(String parol) {
		_parol = parol;
	}

	@Override
	public int getAktivnost() {
		return _aktivnost;
	}

	@Override
	public void setAktivnost(int aktivnost) {
		_aktivnost = aktivnost;
	}

	@Override
	public long getSozdal() {
		return _sozdal;
	}

	@Override
	public void setSozdal(long sozdal) {
		_sozdal = sozdal;
	}

	@Override
	public long getIzmenil() {
		return _izmenil;
	}

	@Override
	public void setIzmenil(long izmenil) {
		_izmenil = izmenil;
	}

	@Override
	public Date getData_sozdanija() {
		return _data_sozdanija;
	}

	@Override
	public void setData_sozdanija(Date data_sozdanija) {
		_data_sozdanija = data_sozdanija;
	}

	@Override
	public Date getData_izmenenija() {
		return _data_izmenenija;
	}

	@Override
	public void setData_izmenenija(Date data_izmenenija) {
		_data_izmenenija = data_izmenenija;
	}

	@Override
	public int getPodrazdelenije_id() {
		return _podrazdelenije_id;
	}

	@Override
	public void setPodrazdelenije_id(int podrazdelenije_id) {
		_podrazdelenije_id = podrazdelenije_id;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Polzovateli.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Polzovateli toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Polzovateli)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PolzovateliImpl polzovateliImpl = new PolzovateliImpl();

		polzovateliImpl.setPolzovateli_id(getPolzovateli_id());
		polzovateliImpl.setOrganizacija_id(getOrganizacija_id());
		polzovateliImpl.setTip_organizacii_id(getTip_organizacii_id());
		polzovateliImpl.setRol_id(getRol_id());
		polzovateliImpl.setImja_polzovatelja(getImja_polzovatelja());
		polzovateliImpl.setParol(getParol());
		polzovateliImpl.setAktivnost(getAktivnost());
		polzovateliImpl.setSozdal(getSozdal());
		polzovateliImpl.setIzmenil(getIzmenil());
		polzovateliImpl.setData_sozdanija(getData_sozdanija());
		polzovateliImpl.setData_izmenenija(getData_izmenenija());
		polzovateliImpl.setPodrazdelenije_id(getPodrazdelenije_id());

		polzovateliImpl.resetOriginalValues();

		return polzovateliImpl;
	}

	@Override
	public int compareTo(Polzovateli polzovateli) {
		long primaryKey = polzovateli.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Polzovateli)) {
			return false;
		}

		Polzovateli polzovateli = (Polzovateli)obj;

		long primaryKey = polzovateli.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Polzovateli> toCacheModel() {
		PolzovateliCacheModel polzovateliCacheModel = new PolzovateliCacheModel();

		polzovateliCacheModel.polzovateli_id = getPolzovateli_id();

		polzovateliCacheModel.organizacija_id = getOrganizacija_id();

		polzovateliCacheModel.tip_organizacii_id = getTip_organizacii_id();

		polzovateliCacheModel.rol_id = getRol_id();

		polzovateliCacheModel.imja_polzovatelja = getImja_polzovatelja();

		String imja_polzovatelja = polzovateliCacheModel.imja_polzovatelja;

		if ((imja_polzovatelja != null) && (imja_polzovatelja.length() == 0)) {
			polzovateliCacheModel.imja_polzovatelja = null;
		}

		polzovateliCacheModel.parol = getParol();

		String parol = polzovateliCacheModel.parol;

		if ((parol != null) && (parol.length() == 0)) {
			polzovateliCacheModel.parol = null;
		}

		polzovateliCacheModel.aktivnost = getAktivnost();

		polzovateliCacheModel.sozdal = getSozdal();

		polzovateliCacheModel.izmenil = getIzmenil();

		Date data_sozdanija = getData_sozdanija();

		if (data_sozdanija != null) {
			polzovateliCacheModel.data_sozdanija = data_sozdanija.getTime();
		}
		else {
			polzovateliCacheModel.data_sozdanija = Long.MIN_VALUE;
		}

		Date data_izmenenija = getData_izmenenija();

		if (data_izmenenija != null) {
			polzovateliCacheModel.data_izmenenija = data_izmenenija.getTime();
		}
		else {
			polzovateliCacheModel.data_izmenenija = Long.MIN_VALUE;
		}

		polzovateliCacheModel.podrazdelenije_id = getPodrazdelenije_id();

		return polzovateliCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{polzovateli_id=");
		sb.append(getPolzovateli_id());
		sb.append(", organizacija_id=");
		sb.append(getOrganizacija_id());
		sb.append(", tip_organizacii_id=");
		sb.append(getTip_organizacii_id());
		sb.append(", rol_id=");
		sb.append(getRol_id());
		sb.append(", imja_polzovatelja=");
		sb.append(getImja_polzovatelja());
		sb.append(", parol=");
		sb.append(getParol());
		sb.append(", aktivnost=");
		sb.append(getAktivnost());
		sb.append(", sozdal=");
		sb.append(getSozdal());
		sb.append(", izmenil=");
		sb.append(getIzmenil());
		sb.append(", data_sozdanija=");
		sb.append(getData_sozdanija());
		sb.append(", data_izmenenija=");
		sb.append(getData_izmenenija());
		sb.append(", podrazdelenije_id=");
		sb.append(getPodrazdelenije_id());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("tj.polzovateli.model.Polzovateli");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>polzovateli_id</column-name><column-value><![CDATA[");
		sb.append(getPolzovateli_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizacija_id</column-name><column-value><![CDATA[");
		sb.append(getOrganizacija_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tip_organizacii_id</column-name><column-value><![CDATA[");
		sb.append(getTip_organizacii_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rol_id</column-name><column-value><![CDATA[");
		sb.append(getRol_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imja_polzovatelja</column-name><column-value><![CDATA[");
		sb.append(getImja_polzovatelja());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parol</column-name><column-value><![CDATA[");
		sb.append(getParol());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>aktivnost</column-name><column-value><![CDATA[");
		sb.append(getAktivnost());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sozdal</column-name><column-value><![CDATA[");
		sb.append(getSozdal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izmenil</column-name><column-value><![CDATA[");
		sb.append(getIzmenil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data_sozdanija</column-name><column-value><![CDATA[");
		sb.append(getData_sozdanija());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data_izmenenija</column-name><column-value><![CDATA[");
		sb.append(getData_izmenenija());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>podrazdelenije_id</column-name><column-value><![CDATA[");
		sb.append(getPodrazdelenije_id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Polzovateli.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Polzovateli.class
		};
	private long _polzovateli_id;
	private long _organizacija_id;
	private int _tip_organizacii_id;
	private int _rol_id;
	private String _imja_polzovatelja;
	private String _parol;
	private int _aktivnost;
	private long _sozdal;
	private long _izmenil;
	private Date _data_sozdanija;
	private Date _data_izmenenija;
	private int _podrazdelenije_id;
	private Polzovateli _escapedModel;
}