/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.postavwiki.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Postavwiki service. Represents a row in the &quot;sapp.postavwiki&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.postavwiki.model.impl.PostavwikiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.postavwiki.model.impl.PostavwikiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Postavwiki
 * @see tj.postavwiki.model.impl.PostavwikiImpl
 * @see tj.postavwiki.model.impl.PostavwikiModelImpl
 * @generated
 */
@ProviderType
public interface PostavwikiModel extends BaseModel<Postavwiki> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a postavwiki model instance should use the {@link Postavwiki} interface instead.
	 */

	/**
	 * Returns the primary key of this postavwiki.
	 *
	 * @return the primary key of this postavwiki
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this postavwiki.
	 *
	 * @param primaryKey the primary key of this postavwiki
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the adres of this postavwiki.
	 *
	 * @return the adres of this postavwiki
	 */
	@AutoEscape
	public String getAdres();

	/**
	 * Sets the adres of this postavwiki.
	 *
	 * @param adres the adres of this postavwiki
	 */
	public void setAdres(String adres);

	/**
	 * Returns the data_gosudarstvennoj_registracii of this postavwiki.
	 *
	 * @return the data_gosudarstvennoj_registracii of this postavwiki
	 */
	public Date getData_gosudarstvennoj_registracii();

	/**
	 * Sets the data_gosudarstvennoj_registracii of this postavwiki.
	 *
	 * @param data_gosudarstvennoj_registracii the data_gosudarstvennoj_registracii of this postavwiki
	 */
	public void setData_gosudarstvennoj_registracii(
		Date data_gosudarstvennoj_registracii);

	/**
	 * Returns the data_izmenenija of this postavwiki.
	 *
	 * @return the data_izmenenija of this postavwiki
	 */
	public Date getData_izmenenija();

	/**
	 * Sets the data_izmenenija of this postavwiki.
	 *
	 * @param data_izmenenija the data_izmenenija of this postavwiki
	 */
	public void setData_izmenenija(Date data_izmenenija);

	/**
	 * Returns the data_sozdanija of this postavwiki.
	 *
	 * @return the data_sozdanija of this postavwiki
	 */
	public Date getData_sozdanija();

	/**
	 * Sets the data_sozdanija of this postavwiki.
	 *
	 * @param data_sozdanija the data_sozdanija of this postavwiki
	 */
	public void setData_sozdanija(Date data_sozdanija);

	/**
	 * Returns the ein of this postavwiki.
	 *
	 * @return the ein of this postavwiki
	 */
	@AutoEscape
	public String getEin();

	/**
	 * Sets the ein of this postavwiki.
	 *
	 * @param ein the ein of this postavwiki
	 */
	public void setEin(String ein);

	/**
	 * Returns the gorod of this postavwiki.
	 *
	 * @return the gorod of this postavwiki
	 */
	@AutoEscape
	public String getGorod();

	/**
	 * Sets the gorod of this postavwiki.
	 *
	 * @param gorod the gorod of this postavwiki
	 */
	public void setGorod(String gorod);

	/**
	 * Returns the inn of this postavwiki.
	 *
	 * @return the inn of this postavwiki
	 */
	@AutoEscape
	public String getInn();

	/**
	 * Sets the inn of this postavwiki.
	 *
	 * @param inn the inn of this postavwiki
	 */
	public void setInn(String inn);

	/**
	 * Returns the izmenil of this postavwiki.
	 *
	 * @return the izmenil of this postavwiki
	 */
	public long getIzmenil();

	/**
	 * Sets the izmenil of this postavwiki.
	 *
	 * @param izmenil the izmenil of this postavwiki
	 */
	public void setIzmenil(long izmenil);

	/**
	 * Returns the kratkoe_naimenovanie of this postavwiki.
	 *
	 * @return the kratkoe_naimenovanie of this postavwiki
	 */
	@AutoEscape
	public String getKratkoe_naimenovanie();

	/**
	 * Sets the kratkoe_naimenovanie of this postavwiki.
	 *
	 * @param kratkoe_naimenovanie the kratkoe_naimenovanie of this postavwiki
	 */
	public void setKratkoe_naimenovanie(String kratkoe_naimenovanie);

	/**
	 * Returns the mesto_registracii of this postavwiki.
	 *
	 * @return the mesto_registracii of this postavwiki
	 */
	@AutoEscape
	public String getMesto_registracii();

	/**
	 * Sets the mesto_registracii of this postavwiki.
	 *
	 * @param mesto_registracii the mesto_registracii of this postavwiki
	 */
	public void setMesto_registracii(String mesto_registracii);

	/**
	 * Returns the oblast_id of this postavwiki.
	 *
	 * @return the oblast_id of this postavwiki
	 */
	public long getOblast_id();

	/**
	 * Sets the oblast_id of this postavwiki.
	 *
	 * @param oblast_id the oblast_id of this postavwiki
	 */
	public void setOblast_id(long oblast_id);

	/**
	 * Returns the polnoe_naimenovanie of this postavwiki.
	 *
	 * @return the polnoe_naimenovanie of this postavwiki
	 */
	@AutoEscape
	public String getPolnoe_naimenovanie();

	/**
	 * Sets the polnoe_naimenovanie of this postavwiki.
	 *
	 * @param polnoe_naimenovanie the polnoe_naimenovanie of this postavwiki
	 */
	public void setPolnoe_naimenovanie(String polnoe_naimenovanie);

	/**
	 * Returns the postavwiki_id of this postavwiki.
	 *
	 * @return the postavwiki_id of this postavwiki
	 */
	public long getPostavwiki_id();

	/**
	 * Sets the postavwiki_id of this postavwiki.
	 *
	 * @param postavwiki_id the postavwiki_id of this postavwiki
	 */
	public void setPostavwiki_id(long postavwiki_id);

	/**
	 * Returns the rajon_id of this postavwiki.
	 *
	 * @return the rajon_id of this postavwiki
	 */
	public long getRajon_id();

	/**
	 * Sets the rajon_id of this postavwiki.
	 *
	 * @param rajon_id the rajon_id of this postavwiki
	 */
	public void setRajon_id(long rajon_id);

	/**
	 * Returns the sin of this postavwiki.
	 *
	 * @return the sin of this postavwiki
	 */
	@AutoEscape
	public String getSin();

	/**
	 * Sets the sin of this postavwiki.
	 *
	 * @param sin the sin of this postavwiki
	 */
	public void setSin(String sin);

	/**
	 * Returns the sozdal of this postavwiki.
	 *
	 * @return the sozdal of this postavwiki
	 */
	public long getSozdal();

	/**
	 * Sets the sozdal of this postavwiki.
	 *
	 * @param sozdal the sozdal of this postavwiki
	 */
	public void setSozdal(long sozdal);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.postavwiki.model.Postavwiki postavwiki);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.postavwiki.model.Postavwiki> toCacheModel();

	@Override
	public tj.postavwiki.model.Postavwiki toEscapedModel();

	@Override
	public tj.postavwiki.model.Postavwiki toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}