/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.tipy.dokumentov.postavwika.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the TipyDokumentovPostavwika service. Represents a row in the &quot;Tipy_dokumentov_postavwika_TipyDokumentovPostavwika&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.tipy.dokumentov.postavwika.model.impl.TipyDokumentovPostavwikaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.tipy.dokumentov.postavwika.model.impl.TipyDokumentovPostavwikaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TipyDokumentovPostavwika
 * @see tj.tipy.dokumentov.postavwika.model.impl.TipyDokumentovPostavwikaImpl
 * @see tj.tipy.dokumentov.postavwika.model.impl.TipyDokumentovPostavwikaModelImpl
 * @generated
 */
@ProviderType
public interface TipyDokumentovPostavwikaModel extends BaseModel<TipyDokumentovPostavwika> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tipy dokumentov postavwika model instance should use the {@link TipyDokumentovPostavwika} interface instead.
	 */

	/**
	 * Returns the primary key of this tipy dokumentov postavwika.
	 *
	 * @return the primary key of this tipy dokumentov postavwika
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this tipy dokumentov postavwika.
	 *
	 * @param primaryKey the primary key of this tipy dokumentov postavwika
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the tipy_dokumentov_postavwika_id of this tipy dokumentov postavwika.
	 *
	 * @return the tipy_dokumentov_postavwika_id of this tipy dokumentov postavwika
	 */
	public int getTipy_dokumentov_postavwika_id();

	/**
	 * Sets the tipy_dokumentov_postavwika_id of this tipy dokumentov postavwika.
	 *
	 * @param tipy_dokumentov_postavwika_id the tipy_dokumentov_postavwika_id of this tipy dokumentov postavwika
	 */
	public void setTipy_dokumentov_postavwika_id(
		int tipy_dokumentov_postavwika_id);

	/**
	 * Returns the tip of this tipy dokumentov postavwika.
	 *
	 * @return the tip of this tipy dokumentov postavwika
	 */
	@AutoEscape
	public String getTip();

	/**
	 * Sets the tip of this tipy dokumentov postavwika.
	 *
	 * @param tip the tip of this tipy dokumentov postavwika
	 */
	public void setTip(String tip);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.tipy.dokumentov.postavwika.model.TipyDokumentovPostavwika tipyDokumentovPostavwika);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.tipy.dokumentov.postavwika.model.TipyDokumentovPostavwika> toCacheModel();

	@Override
	public tj.tipy.dokumentov.postavwika.model.TipyDokumentovPostavwika toEscapedModel();

	@Override
	public tj.tipy.dokumentov.postavwika.model.TipyDokumentovPostavwika toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}