/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.sapp.services.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tj.sapp.services.model.VW_Izvewenija;
import tj.sapp.services.service.VW_IzvewenijaLocalService;
import tj.sapp.services.service.persistence.OKGZPersistence;
import tj.sapp.services.service.persistence.RajonyPersistence;
import tj.sapp.services.service.persistence.VBKPersistence;
import tj.sapp.services.service.persistence.VW_IzvewenijaPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the vw_ izvewenija local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tj.sapp.services.service.impl.VW_IzvewenijaLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tj.sapp.services.service.impl.VW_IzvewenijaLocalServiceImpl
 * @see tj.sapp.services.service.VW_IzvewenijaLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class VW_IzvewenijaLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements VW_IzvewenijaLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tj.sapp.services.service.VW_IzvewenijaLocalServiceUtil} to access the vw_ izvewenija local service.
	 */

	/**
	 * Adds the vw_ izvewenija to the database. Also notifies the appropriate model listeners.
	 *
	 * @param vw_Izvewenija the vw_ izvewenija
	 * @return the vw_ izvewenija that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public VW_Izvewenija addVW_Izvewenija(VW_Izvewenija vw_Izvewenija) {
		vw_Izvewenija.setNew(true);

		return vw_IzvewenijaPersistence.update(vw_Izvewenija);
	}

	/**
	 * Creates a new vw_ izvewenija with the primary key. Does not add the vw_ izvewenija to the database.
	 *
	 * @param izvewenija_id the primary key for the new vw_ izvewenija
	 * @return the new vw_ izvewenija
	 */
	@Override
	public VW_Izvewenija createVW_Izvewenija(long izvewenija_id) {
		return vw_IzvewenijaPersistence.create(izvewenija_id);
	}

	/**
	 * Deletes the vw_ izvewenija with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param izvewenija_id the primary key of the vw_ izvewenija
	 * @return the vw_ izvewenija that was removed
	 * @throws PortalException if a vw_ izvewenija with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public VW_Izvewenija deleteVW_Izvewenija(long izvewenija_id)
		throws PortalException {
		return vw_IzvewenijaPersistence.remove(izvewenija_id);
	}

	/**
	 * Deletes the vw_ izvewenija from the database. Also notifies the appropriate model listeners.
	 *
	 * @param vw_Izvewenija the vw_ izvewenija
	 * @return the vw_ izvewenija that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public VW_Izvewenija deleteVW_Izvewenija(VW_Izvewenija vw_Izvewenija) {
		return vw_IzvewenijaPersistence.remove(vw_Izvewenija);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(VW_Izvewenija.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return vw_IzvewenijaPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.sapp.services.model.impl.VW_IzvewenijaModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return vw_IzvewenijaPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.sapp.services.model.impl.VW_IzvewenijaModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return vw_IzvewenijaPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return vw_IzvewenijaPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return vw_IzvewenijaPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public VW_Izvewenija fetchVW_Izvewenija(long izvewenija_id) {
		return vw_IzvewenijaPersistence.fetchByPrimaryKey(izvewenija_id);
	}

	/**
	 * Returns the vw_ izvewenija with the primary key.
	 *
	 * @param izvewenija_id the primary key of the vw_ izvewenija
	 * @return the vw_ izvewenija
	 * @throws PortalException if a vw_ izvewenija with the primary key could not be found
	 */
	@Override
	public VW_Izvewenija getVW_Izvewenija(long izvewenija_id)
		throws PortalException {
		return vw_IzvewenijaPersistence.findByPrimaryKey(izvewenija_id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(vw_IzvewenijaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(VW_Izvewenija.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("izvewenija_id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(vw_IzvewenijaLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(VW_Izvewenija.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"izvewenija_id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(vw_IzvewenijaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(VW_Izvewenija.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("izvewenija_id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return vw_IzvewenijaLocalService.deleteVW_Izvewenija((VW_Izvewenija)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return vw_IzvewenijaPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the vw_ izvewenijas.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.sapp.services.model.impl.VW_IzvewenijaModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of vw_ izvewenijas
	 * @param end the upper bound of the range of vw_ izvewenijas (not inclusive)
	 * @return the range of vw_ izvewenijas
	 */
	@Override
	public List<VW_Izvewenija> getVW_Izvewenijas(int start, int end) {
		return vw_IzvewenijaPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of vw_ izvewenijas.
	 *
	 * @return the number of vw_ izvewenijas
	 */
	@Override
	public int getVW_IzvewenijasCount() {
		return vw_IzvewenijaPersistence.countAll();
	}

	/**
	 * Updates the vw_ izvewenija in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param vw_Izvewenija the vw_ izvewenija
	 * @return the vw_ izvewenija that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public VW_Izvewenija updateVW_Izvewenija(VW_Izvewenija vw_Izvewenija) {
		return vw_IzvewenijaPersistence.update(vw_Izvewenija);
	}

	/**
	 * Returns the okgz local service.
	 *
	 * @return the okgz local service
	 */
	public tj.sapp.services.service.OKGZLocalService getOKGZLocalService() {
		return okgzLocalService;
	}

	/**
	 * Sets the okgz local service.
	 *
	 * @param okgzLocalService the okgz local service
	 */
	public void setOKGZLocalService(
		tj.sapp.services.service.OKGZLocalService okgzLocalService) {
		this.okgzLocalService = okgzLocalService;
	}

	/**
	 * Returns the okgz persistence.
	 *
	 * @return the okgz persistence
	 */
	public OKGZPersistence getOKGZPersistence() {
		return okgzPersistence;
	}

	/**
	 * Sets the okgz persistence.
	 *
	 * @param okgzPersistence the okgz persistence
	 */
	public void setOKGZPersistence(OKGZPersistence okgzPersistence) {
		this.okgzPersistence = okgzPersistence;
	}

	/**
	 * Returns the Rajony local service.
	 *
	 * @return the Rajony local service
	 */
	public tj.sapp.services.service.RajonyLocalService getRajonyLocalService() {
		return rajonyLocalService;
	}

	/**
	 * Sets the Rajony local service.
	 *
	 * @param rajonyLocalService the Rajony local service
	 */
	public void setRajonyLocalService(
		tj.sapp.services.service.RajonyLocalService rajonyLocalService) {
		this.rajonyLocalService = rajonyLocalService;
	}

	/**
	 * Returns the Rajony persistence.
	 *
	 * @return the Rajony persistence
	 */
	public RajonyPersistence getRajonyPersistence() {
		return rajonyPersistence;
	}

	/**
	 * Sets the Rajony persistence.
	 *
	 * @param rajonyPersistence the Rajony persistence
	 */
	public void setRajonyPersistence(RajonyPersistence rajonyPersistence) {
		this.rajonyPersistence = rajonyPersistence;
	}

	/**
	 * Returns the vbk local service.
	 *
	 * @return the vbk local service
	 */
	public tj.sapp.services.service.VBKLocalService getVBKLocalService() {
		return vbkLocalService;
	}

	/**
	 * Sets the vbk local service.
	 *
	 * @param vbkLocalService the vbk local service
	 */
	public void setVBKLocalService(
		tj.sapp.services.service.VBKLocalService vbkLocalService) {
		this.vbkLocalService = vbkLocalService;
	}

	/**
	 * Returns the vbk persistence.
	 *
	 * @return the vbk persistence
	 */
	public VBKPersistence getVBKPersistence() {
		return vbkPersistence;
	}

	/**
	 * Sets the vbk persistence.
	 *
	 * @param vbkPersistence the vbk persistence
	 */
	public void setVBKPersistence(VBKPersistence vbkPersistence) {
		this.vbkPersistence = vbkPersistence;
	}

	/**
	 * Returns the vw_ izvewenija local service.
	 *
	 * @return the vw_ izvewenija local service
	 */
	public VW_IzvewenijaLocalService getVW_IzvewenijaLocalService() {
		return vw_IzvewenijaLocalService;
	}

	/**
	 * Sets the vw_ izvewenija local service.
	 *
	 * @param vw_IzvewenijaLocalService the vw_ izvewenija local service
	 */
	public void setVW_IzvewenijaLocalService(
		VW_IzvewenijaLocalService vw_IzvewenijaLocalService) {
		this.vw_IzvewenijaLocalService = vw_IzvewenijaLocalService;
	}

	/**
	 * Returns the vw_ izvewenija persistence.
	 *
	 * @return the vw_ izvewenija persistence
	 */
	public VW_IzvewenijaPersistence getVW_IzvewenijaPersistence() {
		return vw_IzvewenijaPersistence;
	}

	/**
	 * Sets the vw_ izvewenija persistence.
	 *
	 * @param vw_IzvewenijaPersistence the vw_ izvewenija persistence
	 */
	public void setVW_IzvewenijaPersistence(
		VW_IzvewenijaPersistence vw_IzvewenijaPersistence) {
		this.vw_IzvewenijaPersistence = vw_IzvewenijaPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("tj.sapp.services.model.VW_Izvewenija",
			vw_IzvewenijaLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"tj.sapp.services.model.VW_Izvewenija");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return VW_IzvewenijaLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return VW_Izvewenija.class;
	}

	protected String getModelClassName() {
		return VW_Izvewenija.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = vw_IzvewenijaPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = tj.sapp.services.service.OKGZLocalService.class)
	protected tj.sapp.services.service.OKGZLocalService okgzLocalService;
	@BeanReference(type = OKGZPersistence.class)
	protected OKGZPersistence okgzPersistence;
	@BeanReference(type = tj.sapp.services.service.RajonyLocalService.class)
	protected tj.sapp.services.service.RajonyLocalService rajonyLocalService;
	@BeanReference(type = RajonyPersistence.class)
	protected RajonyPersistence rajonyPersistence;
	@BeanReference(type = tj.sapp.services.service.VBKLocalService.class)
	protected tj.sapp.services.service.VBKLocalService vbkLocalService;
	@BeanReference(type = VBKPersistence.class)
	protected VBKPersistence vbkPersistence;
	@BeanReference(type = VW_IzvewenijaLocalService.class)
	protected VW_IzvewenijaLocalService vw_IzvewenijaLocalService;
	@BeanReference(type = VW_IzvewenijaPersistence.class)
	protected VW_IzvewenijaPersistence vw_IzvewenijaPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}