/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.status.izvewenij.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.status.izvewenij.model.StatusIzvewenij;
import tj.status.izvewenij.model.StatusIzvewenijModel;
import tj.status.izvewenij.model.StatusIzvewenijSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the StatusIzvewenij service. Represents a row in the &quot;sapp.status_izvewenij&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link StatusIzvewenijModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StatusIzvewenijImpl}.
 * </p>
 *
 * @author falko
 * @see StatusIzvewenijImpl
 * @see StatusIzvewenij
 * @see StatusIzvewenijModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class StatusIzvewenijModelImpl extends BaseModelImpl<StatusIzvewenij>
	implements StatusIzvewenijModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a status izvewenij model instance should use the {@link StatusIzvewenij} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.status_izvewenij";
	public static final Object[][] TABLE_COLUMNS = {
			{ "status_izvewenij_id", Types.BIGINT },
			{ "status", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("status_izvewenij_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.status_izvewenij (status_izvewenij_id LONG not null primary key,status VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table sapp.status_izvewenij";
	public static final String ORDER_BY_JPQL = " ORDER BY statusIzvewenij.status_izvewenij_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.status_izvewenij.status_izvewenij_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.status.izvewenij.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.status.izvewenij.model.StatusIzvewenij"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.status.izvewenij.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.status.izvewenij.model.StatusIzvewenij"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static StatusIzvewenij toModel(StatusIzvewenijSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		StatusIzvewenij model = new StatusIzvewenijImpl();

		model.setStatus_izvewenij_id(soapModel.getStatus_izvewenij_id());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<StatusIzvewenij> toModels(
		StatusIzvewenijSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<StatusIzvewenij> models = new ArrayList<StatusIzvewenij>(soapModels.length);

		for (StatusIzvewenijSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.status.izvewenij.service.util.ServiceProps.get(
				"lock.expiration.time.tj.status.izvewenij.model.StatusIzvewenij"));

	public StatusIzvewenijModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _status_izvewenij_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStatus_izvewenij_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _status_izvewenij_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return StatusIzvewenij.class;
	}

	@Override
	public String getModelClassName() {
		return StatusIzvewenij.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("status_izvewenij_id", getStatus_izvewenij_id());
		attributes.put("status", getStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long status_izvewenij_id = (Long)attributes.get("status_izvewenij_id");

		if (status_izvewenij_id != null) {
			setStatus_izvewenij_id(status_izvewenij_id);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@JSON
	@Override
	public long getStatus_izvewenij_id() {
		return _status_izvewenij_id;
	}

	@Override
	public void setStatus_izvewenij_id(long status_izvewenij_id) {
		_status_izvewenij_id = status_izvewenij_id;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			StatusIzvewenij.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StatusIzvewenij toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (StatusIzvewenij)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StatusIzvewenijImpl statusIzvewenijImpl = new StatusIzvewenijImpl();

		statusIzvewenijImpl.setStatus_izvewenij_id(getStatus_izvewenij_id());
		statusIzvewenijImpl.setStatus(getStatus());

		statusIzvewenijImpl.resetOriginalValues();

		return statusIzvewenijImpl;
	}

	@Override
	public int compareTo(StatusIzvewenij statusIzvewenij) {
		long primaryKey = statusIzvewenij.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof StatusIzvewenij)) {
			return false;
		}

		StatusIzvewenij statusIzvewenij = (StatusIzvewenij)obj;

		long primaryKey = statusIzvewenij.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<StatusIzvewenij> toCacheModel() {
		StatusIzvewenijCacheModel statusIzvewenijCacheModel = new StatusIzvewenijCacheModel();

		statusIzvewenijCacheModel.status_izvewenij_id = getStatus_izvewenij_id();

		statusIzvewenijCacheModel.status = getStatus();

		String status = statusIzvewenijCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			statusIzvewenijCacheModel.status = null;
		}

		return statusIzvewenijCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{status_izvewenij_id=");
		sb.append(getStatus_izvewenij_id());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("tj.status.izvewenij.model.StatusIzvewenij");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>status_izvewenij_id</column-name><column-value><![CDATA[");
		sb.append(getStatus_izvewenij_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = StatusIzvewenij.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			StatusIzvewenij.class
		};
	private long _status_izvewenij_id;
	private String _status;
	private StatusIzvewenij _escapedModel;
}