/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.balans.postavwika.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the BalansPostavwika service. Represents a row in the &quot;sapp.balans_postavwika&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.balans.postavwika.model.impl.BalansPostavwikaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.balans.postavwika.model.impl.BalansPostavwikaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BalansPostavwika
 * @see tj.balans.postavwika.model.impl.BalansPostavwikaImpl
 * @see tj.balans.postavwika.model.impl.BalansPostavwikaModelImpl
 * @generated
 */
@ProviderType
public interface BalansPostavwikaModel extends BaseModel<BalansPostavwika> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a balans postavwika model instance should use the {@link BalansPostavwika} interface instead.
	 */

	/**
	 * Returns the primary key of this balans postavwika.
	 *
	 * @return the primary key of this balans postavwika
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this balans postavwika.
	 *
	 * @param primaryKey the primary key of this balans postavwika
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the balans_postavwika_id of this balans postavwika.
	 *
	 * @return the balans_postavwika_id of this balans postavwika
	 */
	public long getBalans_postavwika_id();

	/**
	 * Sets the balans_postavwika_id of this balans postavwika.
	 *
	 * @param balans_postavwika_id the balans_postavwika_id of this balans postavwika
	 */
	public void setBalans_postavwika_id(long balans_postavwika_id);

	/**
	 * Returns the postavwik_id of this balans postavwika.
	 *
	 * @return the postavwik_id of this balans postavwika
	 */
	public long getPostavwik_id();

	/**
	 * Sets the postavwik_id of this balans postavwika.
	 *
	 * @param postavwik_id the postavwik_id of this balans postavwika
	 */
	public void setPostavwik_id(long postavwik_id);

	/**
	 * Returns the balans of this balans postavwika.
	 *
	 * @return the balans of this balans postavwika
	 */
	public double getBalans();

	/**
	 * Sets the balans of this balans postavwika.
	 *
	 * @param balans the balans of this balans postavwika
	 */
	public void setBalans(double balans);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.balans.postavwika.model.BalansPostavwika balansPostavwika);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.balans.postavwika.model.BalansPostavwika> toCacheModel();

	@Override
	public tj.balans.postavwika.model.BalansPostavwika toEscapedModel();

	@Override
	public tj.balans.postavwika.model.BalansPostavwika toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}