create table sapp.prochaja_informacija_dlja_zajavki (
	cena_postavki VARCHAR(75) null,
	cena_postavki_soglasno_zakazchiku INTEGER,
	data_sozdanija DATE null,
	izvewenie_id LONG,
	lot_id LONG,
	mesto_postavki VARCHAR(75) null,
	mesto_postavki_soglasno_zakazchiku INTEGER,
	oplata VARCHAR(75) null,
	oplata_soglasno_zakazchiku INTEGER,
	postavwik_id LONG,
	prochaja_informacija_dlja_zajavki_id LONG not null primary key,
	soputstvujuwie_uslovija VARCHAR(75) null,
	soputstvujuwie_uslovija_soglasno_zakazchiku INTEGER,
	sozdal LONG,
	srok_dejstvija VARCHAR(75) null,
	srok_dejstvija_soglasno_zakazchiku INTEGER,
	srok_ispolnenija_zajavki VARCHAR(75) null,
	srok_ispolnenija_zajavki_soglasno_zakazchiku INTEGER,
	srok_obespechenija_zajavki VARCHAR(75) null,
	srok_obespechenija_zajavki_soglasno_zakazchiku INTEGER,
	srok_postavki VARCHAR(75) null,
	srok_postavki_soglasno_zakazchiku INTEGER
);