/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.tipy.dokumentov.postavwika.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tj.tipy.dokumentov.postavwika.model.TipyDokumentovPostavwika;
import tj.tipy.dokumentov.postavwika.service.TipyDokumentovPostavwikaLocalService;
import tj.tipy.dokumentov.postavwika.service.persistence.TipyDokumentovPostavwikaPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the tipy dokumentov postavwika local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tj.tipy.dokumentov.postavwika.service.impl.TipyDokumentovPostavwikaLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tj.tipy.dokumentov.postavwika.service.impl.TipyDokumentovPostavwikaLocalServiceImpl
 * @see tj.tipy.dokumentov.postavwika.service.TipyDokumentovPostavwikaLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class TipyDokumentovPostavwikaLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements TipyDokumentovPostavwikaLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tj.tipy.dokumentov.postavwika.service.TipyDokumentovPostavwikaLocalServiceUtil} to access the tipy dokumentov postavwika local service.
	 */

	/**
	 * Adds the tipy dokumentov postavwika to the database. Also notifies the appropriate model listeners.
	 *
	 * @param tipyDokumentovPostavwika the tipy dokumentov postavwika
	 * @return the tipy dokumentov postavwika that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public TipyDokumentovPostavwika addTipyDokumentovPostavwika(
		TipyDokumentovPostavwika tipyDokumentovPostavwika) {
		tipyDokumentovPostavwika.setNew(true);

		return tipyDokumentovPostavwikaPersistence.update(tipyDokumentovPostavwika);
	}

	/**
	 * Creates a new tipy dokumentov postavwika with the primary key. Does not add the tipy dokumentov postavwika to the database.
	 *
	 * @param tipy_dokumentov_postavwika_id the primary key for the new tipy dokumentov postavwika
	 * @return the new tipy dokumentov postavwika
	 */
	@Override
	public TipyDokumentovPostavwika createTipyDokumentovPostavwika(
		int tipy_dokumentov_postavwika_id) {
		return tipyDokumentovPostavwikaPersistence.create(tipy_dokumentov_postavwika_id);
	}

	/**
	 * Deletes the tipy dokumentov postavwika with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param tipy_dokumentov_postavwika_id the primary key of the tipy dokumentov postavwika
	 * @return the tipy dokumentov postavwika that was removed
	 * @throws PortalException if a tipy dokumentov postavwika with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public TipyDokumentovPostavwika deleteTipyDokumentovPostavwika(
		int tipy_dokumentov_postavwika_id) throws PortalException {
		return tipyDokumentovPostavwikaPersistence.remove(tipy_dokumentov_postavwika_id);
	}

	/**
	 * Deletes the tipy dokumentov postavwika from the database. Also notifies the appropriate model listeners.
	 *
	 * @param tipyDokumentovPostavwika the tipy dokumentov postavwika
	 * @return the tipy dokumentov postavwika that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public TipyDokumentovPostavwika deleteTipyDokumentovPostavwika(
		TipyDokumentovPostavwika tipyDokumentovPostavwika) {
		return tipyDokumentovPostavwikaPersistence.remove(tipyDokumentovPostavwika);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(TipyDokumentovPostavwika.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return tipyDokumentovPostavwikaPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.tipy.dokumentov.postavwika.model.impl.TipyDokumentovPostavwikaModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return tipyDokumentovPostavwikaPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.tipy.dokumentov.postavwika.model.impl.TipyDokumentovPostavwikaModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return tipyDokumentovPostavwikaPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return tipyDokumentovPostavwikaPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return tipyDokumentovPostavwikaPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public TipyDokumentovPostavwika fetchTipyDokumentovPostavwika(
		int tipy_dokumentov_postavwika_id) {
		return tipyDokumentovPostavwikaPersistence.fetchByPrimaryKey(tipy_dokumentov_postavwika_id);
	}

	/**
	 * Returns the tipy dokumentov postavwika with the primary key.
	 *
	 * @param tipy_dokumentov_postavwika_id the primary key of the tipy dokumentov postavwika
	 * @return the tipy dokumentov postavwika
	 * @throws PortalException if a tipy dokumentov postavwika with the primary key could not be found
	 */
	@Override
	public TipyDokumentovPostavwika getTipyDokumentovPostavwika(
		int tipy_dokumentov_postavwika_id) throws PortalException {
		return tipyDokumentovPostavwikaPersistence.findByPrimaryKey(tipy_dokumentov_postavwika_id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(tipyDokumentovPostavwikaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(TipyDokumentovPostavwika.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"tipy_dokumentov_postavwika_id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(tipyDokumentovPostavwikaLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(TipyDokumentovPostavwika.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"tipy_dokumentov_postavwika_id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(tipyDokumentovPostavwikaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(TipyDokumentovPostavwika.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"tipy_dokumentov_postavwika_id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return tipyDokumentovPostavwikaLocalService.deleteTipyDokumentovPostavwika((TipyDokumentovPostavwika)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return tipyDokumentovPostavwikaPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the tipy dokumentov postavwikas.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.tipy.dokumentov.postavwika.model.impl.TipyDokumentovPostavwikaModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of tipy dokumentov postavwikas
	 * @param end the upper bound of the range of tipy dokumentov postavwikas (not inclusive)
	 * @return the range of tipy dokumentov postavwikas
	 */
	@Override
	public List<TipyDokumentovPostavwika> getTipyDokumentovPostavwikas(
		int start, int end) {
		return tipyDokumentovPostavwikaPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of tipy dokumentov postavwikas.
	 *
	 * @return the number of tipy dokumentov postavwikas
	 */
	@Override
	public int getTipyDokumentovPostavwikasCount() {
		return tipyDokumentovPostavwikaPersistence.countAll();
	}

	/**
	 * Updates the tipy dokumentov postavwika in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param tipyDokumentovPostavwika the tipy dokumentov postavwika
	 * @return the tipy dokumentov postavwika that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public TipyDokumentovPostavwika updateTipyDokumentovPostavwika(
		TipyDokumentovPostavwika tipyDokumentovPostavwika) {
		return tipyDokumentovPostavwikaPersistence.update(tipyDokumentovPostavwika);
	}

	/**
	 * Returns the tipy dokumentov postavwika local service.
	 *
	 * @return the tipy dokumentov postavwika local service
	 */
	public TipyDokumentovPostavwikaLocalService getTipyDokumentovPostavwikaLocalService() {
		return tipyDokumentovPostavwikaLocalService;
	}

	/**
	 * Sets the tipy dokumentov postavwika local service.
	 *
	 * @param tipyDokumentovPostavwikaLocalService the tipy dokumentov postavwika local service
	 */
	public void setTipyDokumentovPostavwikaLocalService(
		TipyDokumentovPostavwikaLocalService tipyDokumentovPostavwikaLocalService) {
		this.tipyDokumentovPostavwikaLocalService = tipyDokumentovPostavwikaLocalService;
	}

	/**
	 * Returns the tipy dokumentov postavwika persistence.
	 *
	 * @return the tipy dokumentov postavwika persistence
	 */
	public TipyDokumentovPostavwikaPersistence getTipyDokumentovPostavwikaPersistence() {
		return tipyDokumentovPostavwikaPersistence;
	}

	/**
	 * Sets the tipy dokumentov postavwika persistence.
	 *
	 * @param tipyDokumentovPostavwikaPersistence the tipy dokumentov postavwika persistence
	 */
	public void setTipyDokumentovPostavwikaPersistence(
		TipyDokumentovPostavwikaPersistence tipyDokumentovPostavwikaPersistence) {
		this.tipyDokumentovPostavwikaPersistence = tipyDokumentovPostavwikaPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("tj.tipy.dokumentov.postavwika.model.TipyDokumentovPostavwika",
			tipyDokumentovPostavwikaLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"tj.tipy.dokumentov.postavwika.model.TipyDokumentovPostavwika");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return TipyDokumentovPostavwikaLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return TipyDokumentovPostavwika.class;
	}

	protected String getModelClassName() {
		return TipyDokumentovPostavwika.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = tipyDokumentovPostavwikaPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = TipyDokumentovPostavwikaLocalService.class)
	protected TipyDokumentovPostavwikaLocalService tipyDokumentovPostavwikaLocalService;
	@BeanReference(type = TipyDokumentovPostavwikaPersistence.class)
	protected TipyDokumentovPostavwikaPersistence tipyDokumentovPostavwikaPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}