/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.izvewenija.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.izvewenija.model.Izvewenija;
import tj.izvewenija.model.IzvewenijaModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Izvewenija service. Represents a row in the &quot;sapp.izvewenija&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link IzvewenijaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IzvewenijaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see IzvewenijaImpl
 * @see Izvewenija
 * @see IzvewenijaModel
 * @generated
 */
@ProviderType
public class IzvewenijaModelImpl extends BaseModelImpl<Izvewenija>
	implements IzvewenijaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a izvewenija model instance should use the {@link Izvewenija} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.izvewenija";
	public static final Object[][] TABLE_COLUMNS = {
			{ "modifiedDate", Types.TIMESTAMP },
			{ "createDate", Types.TIMESTAMP },
			{ "izmenil", Types.BIGINT },
			{ "izvewenija_id", Types.BIGINT },
			{ "kod_id", Types.BIGINT },
			{ "naimenovanie", Types.VARCHAR },
			{ "organizacija_id", Types.BIGINT },
			{ "sostojanie_id", Types.BIGINT },
			{ "sozdal", Types.BIGINT },
			{ "status_id", Types.BIGINT },
			{ "tip_izvewenija_id", Types.BIGINT },
			{ "vyshestojawaja_organizacija_id", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "UserName", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("izmenil", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("izvewenija_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("kod_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("naimenovanie", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("organizacija_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sostojanie_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sozdal", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tip_izvewenija_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("vyshestojawaja_organizacija_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("UserName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.izvewenija (modifiedDate DATE null,createDate DATE null,izmenil LONG,izvewenija_id LONG not null primary key,kod_id LONG,naimenovanie VARCHAR(75) null,organizacija_id LONG,sostojanie_id LONG,sozdal LONG,status_id LONG,tip_izvewenija_id LONG,vyshestojawaja_organizacija_id LONG,userId LONG,groupId LONG,companyId LONG,UserName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table sapp.izvewenija";
	public static final String ORDER_BY_JPQL = " ORDER BY izvewenija.izvewenija_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.izvewenija.izvewenija_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.izvewenija.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.izvewenija.model.Izvewenija"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.izvewenija.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.izvewenija.model.Izvewenija"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(tj.izvewenija.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.tj.izvewenija.model.Izvewenija"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long IZVEWENIJA_ID_COLUMN_BITMASK = 4L;
	public static final long SOZDAL_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.izvewenija.service.util.ServiceProps.get(
				"lock.expiration.time.tj.izvewenija.model.Izvewenija"));

	public IzvewenijaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _izvewenija_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIzvewenija_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _izvewenija_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Izvewenija.class;
	}

	@Override
	public String getModelClassName() {
		return Izvewenija.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("createDate", getCreateDate());
		attributes.put("izmenil", getIzmenil());
		attributes.put("izvewenija_id", getIzvewenija_id());
		attributes.put("kod_id", getKod_id());
		attributes.put("naimenovanie", getNaimenovanie());
		attributes.put("organizacija_id", getOrganizacija_id());
		attributes.put("sostojanie_id", getSostojanie_id());
		attributes.put("sozdal", getSozdal());
		attributes.put("status_id", getStatus_id());
		attributes.put("tip_izvewenija_id", getTip_izvewenija_id());
		attributes.put("vyshestojawaja_organizacija_id",
			getVyshestojawaja_organizacija_id());
		attributes.put("userId", getUserId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("UserName", getUserName());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Long izmenil = (Long)attributes.get("izmenil");

		if (izmenil != null) {
			setIzmenil(izmenil);
		}

		Long izvewenija_id = (Long)attributes.get("izvewenija_id");

		if (izvewenija_id != null) {
			setIzvewenija_id(izvewenija_id);
		}

		Long kod_id = (Long)attributes.get("kod_id");

		if (kod_id != null) {
			setKod_id(kod_id);
		}

		String naimenovanie = (String)attributes.get("naimenovanie");

		if (naimenovanie != null) {
			setNaimenovanie(naimenovanie);
		}

		Long organizacija_id = (Long)attributes.get("organizacija_id");

		if (organizacija_id != null) {
			setOrganizacija_id(organizacija_id);
		}

		Long sostojanie_id = (Long)attributes.get("sostojanie_id");

		if (sostojanie_id != null) {
			setSostojanie_id(sostojanie_id);
		}

		Long sozdal = (Long)attributes.get("sozdal");

		if (sozdal != null) {
			setSozdal(sozdal);
		}

		Long status_id = (Long)attributes.get("status_id");

		if (status_id != null) {
			setStatus_id(status_id);
		}

		Long tip_izvewenija_id = (Long)attributes.get("tip_izvewenija_id");

		if (tip_izvewenija_id != null) {
			setTip_izvewenija_id(tip_izvewenija_id);
		}

		Long vyshestojawaja_organizacija_id = (Long)attributes.get(
				"vyshestojawaja_organizacija_id");

		if (vyshestojawaja_organizacija_id != null) {
			setVyshestojawaja_organizacija_id(vyshestojawaja_organizacija_id);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		String UserName = (String)attributes.get("UserName");

		if (UserName != null) {
			setUserName(UserName);
		}
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public long getIzmenil() {
		return _izmenil;
	}

	@Override
	public void setIzmenil(long izmenil) {
		_izmenil = izmenil;
	}

	@Override
	public long getIzvewenija_id() {
		return _izvewenija_id;
	}

	@Override
	public void setIzvewenija_id(long izvewenija_id) {
		_columnBitmask = -1L;

		if (!_setOriginalIzvewenija_id) {
			_setOriginalIzvewenija_id = true;

			_originalIzvewenija_id = _izvewenija_id;
		}

		_izvewenija_id = izvewenija_id;
	}

	public long getOriginalIzvewenija_id() {
		return _originalIzvewenija_id;
	}

	@Override
	public long getKod_id() {
		return _kod_id;
	}

	@Override
	public void setKod_id(long kod_id) {
		_kod_id = kod_id;
	}

	@Override
	public String getNaimenovanie() {
		if (_naimenovanie == null) {
			return StringPool.BLANK;
		}
		else {
			return _naimenovanie;
		}
	}

	@Override
	public void setNaimenovanie(String naimenovanie) {
		_naimenovanie = naimenovanie;
	}

	@Override
	public long getOrganizacija_id() {
		return _organizacija_id;
	}

	@Override
	public void setOrganizacija_id(long organizacija_id) {
		_organizacija_id = organizacija_id;
	}

	@Override
	public long getSostojanie_id() {
		return _sostojanie_id;
	}

	@Override
	public void setSostojanie_id(long sostojanie_id) {
		_sostojanie_id = sostojanie_id;
	}

	@Override
	public long getSozdal() {
		return _sozdal;
	}

	@Override
	public void setSozdal(long sozdal) {
		_columnBitmask |= SOZDAL_COLUMN_BITMASK;

		if (!_setOriginalSozdal) {
			_setOriginalSozdal = true;

			_originalSozdal = _sozdal;
		}

		_sozdal = sozdal;
	}

	public long getOriginalSozdal() {
		return _originalSozdal;
	}

	@Override
	public long getStatus_id() {
		return _status_id;
	}

	@Override
	public void setStatus_id(long status_id) {
		_status_id = status_id;
	}

	@Override
	public long getTip_izvewenija_id() {
		return _tip_izvewenija_id;
	}

	@Override
	public void setTip_izvewenija_id(long tip_izvewenija_id) {
		_tip_izvewenija_id = tip_izvewenija_id;
	}

	@Override
	public long getVyshestojawaja_organizacija_id() {
		return _vyshestojawaja_organizacija_id;
	}

	@Override
	public void setVyshestojawaja_organizacija_id(
		long vyshestojawaja_organizacija_id) {
		_vyshestojawaja_organizacija_id = vyshestojawaja_organizacija_id;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public String getUserName() {
		if (_UserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _UserName;
		}
	}

	@Override
	public void setUserName(String UserName) {
		_UserName = UserName;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Izvewenija.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Izvewenija toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Izvewenija)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		IzvewenijaImpl izvewenijaImpl = new IzvewenijaImpl();

		izvewenijaImpl.setModifiedDate(getModifiedDate());
		izvewenijaImpl.setCreateDate(getCreateDate());
		izvewenijaImpl.setIzmenil(getIzmenil());
		izvewenijaImpl.setIzvewenija_id(getIzvewenija_id());
		izvewenijaImpl.setKod_id(getKod_id());
		izvewenijaImpl.setNaimenovanie(getNaimenovanie());
		izvewenijaImpl.setOrganizacija_id(getOrganizacija_id());
		izvewenijaImpl.setSostojanie_id(getSostojanie_id());
		izvewenijaImpl.setSozdal(getSozdal());
		izvewenijaImpl.setStatus_id(getStatus_id());
		izvewenijaImpl.setTip_izvewenija_id(getTip_izvewenija_id());
		izvewenijaImpl.setVyshestojawaja_organizacija_id(getVyshestojawaja_organizacija_id());
		izvewenijaImpl.setUserId(getUserId());
		izvewenijaImpl.setGroupId(getGroupId());
		izvewenijaImpl.setCompanyId(getCompanyId());
		izvewenijaImpl.setUserName(getUserName());

		izvewenijaImpl.resetOriginalValues();

		return izvewenijaImpl;
	}

	@Override
	public int compareTo(Izvewenija izvewenija) {
		int value = 0;

		if (getIzvewenija_id() < izvewenija.getIzvewenija_id()) {
			value = -1;
		}
		else if (getIzvewenija_id() > izvewenija.getIzvewenija_id()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Izvewenija)) {
			return false;
		}

		Izvewenija izvewenija = (Izvewenija)obj;

		long primaryKey = izvewenija.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		IzvewenijaModelImpl izvewenijaModelImpl = this;

		izvewenijaModelImpl._setModifiedDate = false;

		izvewenijaModelImpl._originalIzvewenija_id = izvewenijaModelImpl._izvewenija_id;

		izvewenijaModelImpl._setOriginalIzvewenija_id = false;

		izvewenijaModelImpl._originalSozdal = izvewenijaModelImpl._sozdal;

		izvewenijaModelImpl._setOriginalSozdal = false;

		izvewenijaModelImpl._originalGroupId = izvewenijaModelImpl._groupId;

		izvewenijaModelImpl._setOriginalGroupId = false;

		izvewenijaModelImpl._originalCompanyId = izvewenijaModelImpl._companyId;

		izvewenijaModelImpl._setOriginalCompanyId = false;

		izvewenijaModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Izvewenija> toCacheModel() {
		IzvewenijaCacheModel izvewenijaCacheModel = new IzvewenijaCacheModel();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			izvewenijaCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			izvewenijaCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			izvewenijaCacheModel.createDate = createDate.getTime();
		}
		else {
			izvewenijaCacheModel.createDate = Long.MIN_VALUE;
		}

		izvewenijaCacheModel.izmenil = getIzmenil();

		izvewenijaCacheModel.izvewenija_id = getIzvewenija_id();

		izvewenijaCacheModel.kod_id = getKod_id();

		izvewenijaCacheModel.naimenovanie = getNaimenovanie();

		String naimenovanie = izvewenijaCacheModel.naimenovanie;

		if ((naimenovanie != null) && (naimenovanie.length() == 0)) {
			izvewenijaCacheModel.naimenovanie = null;
		}

		izvewenijaCacheModel.organizacija_id = getOrganizacija_id();

		izvewenijaCacheModel.sostojanie_id = getSostojanie_id();

		izvewenijaCacheModel.sozdal = getSozdal();

		izvewenijaCacheModel.status_id = getStatus_id();

		izvewenijaCacheModel.tip_izvewenija_id = getTip_izvewenija_id();

		izvewenijaCacheModel.vyshestojawaja_organizacija_id = getVyshestojawaja_organizacija_id();

		izvewenijaCacheModel.userId = getUserId();

		izvewenijaCacheModel.groupId = getGroupId();

		izvewenijaCacheModel.companyId = getCompanyId();

		izvewenijaCacheModel.UserName = getUserName();

		String UserName = izvewenijaCacheModel.UserName;

		if ((UserName != null) && (UserName.length() == 0)) {
			izvewenijaCacheModel.UserName = null;
		}

		return izvewenijaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(33);

		sb.append("{modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", izmenil=");
		sb.append(getIzmenil());
		sb.append(", izvewenija_id=");
		sb.append(getIzvewenija_id());
		sb.append(", kod_id=");
		sb.append(getKod_id());
		sb.append(", naimenovanie=");
		sb.append(getNaimenovanie());
		sb.append(", organizacija_id=");
		sb.append(getOrganizacija_id());
		sb.append(", sostojanie_id=");
		sb.append(getSostojanie_id());
		sb.append(", sozdal=");
		sb.append(getSozdal());
		sb.append(", status_id=");
		sb.append(getStatus_id());
		sb.append(", tip_izvewenija_id=");
		sb.append(getTip_izvewenija_id());
		sb.append(", vyshestojawaja_organizacija_id=");
		sb.append(getVyshestojawaja_organizacija_id());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", UserName=");
		sb.append(getUserName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(52);

		sb.append("<model><model-name>");
		sb.append("tj.izvewenija.model.Izvewenija");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izmenil</column-name><column-value><![CDATA[");
		sb.append(getIzmenil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izvewenija_id</column-name><column-value><![CDATA[");
		sb.append(getIzvewenija_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kod_id</column-name><column-value><![CDATA[");
		sb.append(getKod_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>naimenovanie</column-name><column-value><![CDATA[");
		sb.append(getNaimenovanie());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizacija_id</column-name><column-value><![CDATA[");
		sb.append(getOrganizacija_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sostojanie_id</column-name><column-value><![CDATA[");
		sb.append(getSostojanie_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sozdal</column-name><column-value><![CDATA[");
		sb.append(getSozdal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status_id</column-name><column-value><![CDATA[");
		sb.append(getStatus_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tip_izvewenija_id</column-name><column-value><![CDATA[");
		sb.append(getTip_izvewenija_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vyshestojawaja_organizacija_id</column-name><column-value><![CDATA[");
		sb.append(getVyshestojawaja_organizacija_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>UserName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Izvewenija.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Izvewenija.class
		};
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _createDate;
	private long _izmenil;
	private long _izvewenija_id;
	private long _originalIzvewenija_id;
	private boolean _setOriginalIzvewenija_id;
	private long _kod_id;
	private String _naimenovanie;
	private long _organizacija_id;
	private long _sostojanie_id;
	private long _sozdal;
	private long _originalSozdal;
	private boolean _setOriginalSozdal;
	private long _status_id;
	private long _tip_izvewenija_id;
	private long _vyshestojawaja_organizacija_id;
	private long _userId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private String _UserName;
	private long _columnBitmask;
	private Izvewenija _escapedModel;
}