/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.sapp.services.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Rajony service. Represents a row in the &quot;sapp.rajony&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.sapp.services.model.impl.RajonyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.sapp.services.model.impl.RajonyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Rajony
 * @see tj.sapp.services.model.impl.RajonyImpl
 * @see tj.sapp.services.model.impl.RajonyModelImpl
 * @generated
 */
@ProviderType
public interface RajonyModel extends BaseModel<Rajony> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Rajony model instance should use the {@link Rajony} interface instead.
	 */

	/**
	 * Returns the primary key of this Rajony.
	 *
	 * @return the primary key of this Rajony
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Rajony.
	 *
	 * @param primaryKey the primary key of this Rajony
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rajony_id of this Rajony.
	 *
	 * @return the rajony_id of this Rajony
	 */
	public long getRajony_id();

	/**
	 * Sets the rajony_id of this Rajony.
	 *
	 * @param rajony_id the rajony_id of this Rajony
	 */
	public void setRajony_id(long rajony_id);

	/**
	 * Returns the oblast_id of this Rajony.
	 *
	 * @return the oblast_id of this Rajony
	 */
	public long getOblast_id();

	/**
	 * Sets the oblast_id of this Rajony.
	 *
	 * @param oblast_id the oblast_id of this Rajony
	 */
	public void setOblast_id(long oblast_id);

	/**
	 * Returns the nazvanie of this Rajony.
	 *
	 * @return the nazvanie of this Rajony
	 */
	@AutoEscape
	public String getNazvanie();

	/**
	 * Sets the nazvanie of this Rajony.
	 *
	 * @param nazvanie the nazvanie of this Rajony
	 */
	public void setNazvanie(String nazvanie);

	/**
	 * Returns the kod_vbk of this Rajony.
	 *
	 * @return the kod_vbk of this Rajony
	 */
	public long getKod_vbk();

	/**
	 * Sets the kod_vbk of this Rajony.
	 *
	 * @param kod_vbk the kod_vbk of this Rajony
	 */
	public void setKod_vbk(long kod_vbk);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.sapp.services.model.Rajony rajony);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.sapp.services.model.Rajony> toCacheModel();

	@Override
	public tj.sapp.services.model.Rajony toEscapedModel();

	@Override
	public tj.sapp.services.model.Rajony toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}