/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.sapp.services.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the VBK service. Represents a row in the &quot;klassifikatory.vbk&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.sapp.services.model.impl.VBKModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.sapp.services.model.impl.VBKImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VBK
 * @see tj.sapp.services.model.impl.VBKImpl
 * @see tj.sapp.services.model.impl.VBKModelImpl
 * @generated
 */
@ProviderType
public interface VBKModel extends BaseModel<VBK> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vbk model instance should use the {@link VBK} interface instead.
	 */

	/**
	 * Returns the primary key of this vbk.
	 *
	 * @return the primary key of this vbk
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vbk.
	 *
	 * @param primaryKey the primary key of this vbk
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_ of this vbk.
	 *
	 * @return the id_ of this vbk
	 */
	public long getId_();

	/**
	 * Sets the id_ of this vbk.
	 *
	 * @param id_ the id_ of this vbk
	 */
	public void setId_(long id_);

	/**
	 * Returns the kod of this vbk.
	 *
	 * @return the kod of this vbk
	 */
	@AutoEscape
	public String getKod();

	/**
	 * Sets the kod of this vbk.
	 *
	 * @param kod the kod of this vbk
	 */
	public void setKod(String kod);

	/**
	 * Returns the nazvanie_tj of this vbk.
	 *
	 * @return the nazvanie_tj of this vbk
	 */
	@AutoEscape
	public String getNazvanie_tj();

	/**
	 * Sets the nazvanie_tj of this vbk.
	 *
	 * @param nazvanie_tj the nazvanie_tj of this vbk
	 */
	public void setNazvanie_tj(String nazvanie_tj);

	/**
	 * Returns the nazvanie_ru of this vbk.
	 *
	 * @return the nazvanie_ru of this vbk
	 */
	@AutoEscape
	public String getNazvanie_ru();

	/**
	 * Sets the nazvanie_ru of this vbk.
	 *
	 * @param nazvanie_ru the nazvanie_ru of this vbk
	 */
	public void setNazvanie_ru(String nazvanie_ru);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.sapp.services.model.VBK vbk);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.sapp.services.model.VBK> toCacheModel();

	@Override
	public tj.sapp.services.model.VBK toEscapedModel();

	@Override
	public tj.sapp.services.model.VBK toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}