/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.orgindex.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Orgindex service. Represents a row in the &quot;sapp.orgindex&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.orgindex.model.impl.OrgindexModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.orgindex.model.impl.OrgindexImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Orgindex
 * @see tj.orgindex.model.impl.OrgindexImpl
 * @see tj.orgindex.model.impl.OrgindexModelImpl
 * @generated
 */
@ProviderType
public interface OrgindexModel extends BaseModel<Orgindex> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a orgindex model instance should use the {@link Orgindex} interface instead.
	 */

	/**
	 * Returns the primary key of this orgindex.
	 *
	 * @return the primary key of this orgindex
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this orgindex.
	 *
	 * @param primaryKey the primary key of this orgindex
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the orgindex_id of this orgindex.
	 *
	 * @return the orgindex_id of this orgindex
	 */
	public long getOrgindex_id();

	/**
	 * Sets the orgindex_id of this orgindex.
	 *
	 * @param orgindex_id the orgindex_id of this orgindex
	 */
	public void setOrgindex_id(long orgindex_id);

	/**
	 * Returns the organization_id of this orgindex.
	 *
	 * @return the organization_id of this orgindex
	 */
	public long getOrganization_id();

	/**
	 * Sets the organization_id of this orgindex.
	 *
	 * @param organization_id the organization_id of this orgindex
	 */
	public void setOrganization_id(long organization_id);

	/**
	 * Returns the subdivision_index of this orgindex.
	 *
	 * @return the subdivision_index of this orgindex
	 */
	public int getSubdivision_index();

	/**
	 * Sets the subdivision_index of this orgindex.
	 *
	 * @param subdivision_index the subdivision_index of this orgindex
	 */
	public void setSubdivision_index(int subdivision_index);

	/**
	 * Returns the sozdal of this orgindex.
	 *
	 * @return the sozdal of this orgindex
	 */
	public long getSozdal();

	/**
	 * Sets the sozdal of this orgindex.
	 *
	 * @param sozdal the sozdal of this orgindex
	 */
	public void setSozdal(long sozdal);

	/**
	 * Returns the izmenil of this orgindex.
	 *
	 * @return the izmenil of this orgindex
	 */
	public long getIzmenil();

	/**
	 * Sets the izmenil of this orgindex.
	 *
	 * @param izmenil the izmenil of this orgindex
	 */
	public void setIzmenil(long izmenil);

	/**
	 * Returns the data_sozdanija of this orgindex.
	 *
	 * @return the data_sozdanija of this orgindex
	 */
	public Date getData_sozdanija();

	/**
	 * Sets the data_sozdanija of this orgindex.
	 *
	 * @param data_sozdanija the data_sozdanija of this orgindex
	 */
	public void setData_sozdanija(Date data_sozdanija);

	/**
	 * Returns the data_izmenenija of this orgindex.
	 *
	 * @return the data_izmenenija of this orgindex
	 */
	public Date getData_izmenenija();

	/**
	 * Sets the data_izmenenija of this orgindex.
	 *
	 * @param data_izmenenija the data_izmenenija of this orgindex
	 */
	public void setData_izmenenija(Date data_izmenenija);

	/**
	 * Returns the name of this orgindex.
	 *
	 * @return the name of this orgindex
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this orgindex.
	 *
	 * @param name the name of this orgindex
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.orgindex.model.Orgindex orgindex);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.orgindex.model.Orgindex> toCacheModel();

	@Override
	public tj.orgindex.model.Orgindex toEscapedModel();

	@Override
	public tj.orgindex.model.Orgindex toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}