/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.izvewenieput.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the IzveweniePut service. Represents a row in the &quot;sapp.izvewenie_put&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.izvewenieput.model.impl.IzveweniePutModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.izvewenieput.model.impl.IzveweniePutImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see IzveweniePut
 * @see tj.izvewenieput.model.impl.IzveweniePutImpl
 * @see tj.izvewenieput.model.impl.IzveweniePutModelImpl
 * @generated
 */
@ProviderType
public interface IzveweniePutModel extends BaseModel<IzveweniePut> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a izvewenie put model instance should use the {@link IzveweniePut} interface instead.
	 */

	/**
	 * Returns the primary key of this izvewenie put.
	 *
	 * @return the primary key of this izvewenie put
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this izvewenie put.
	 *
	 * @param primaryKey the primary key of this izvewenie put
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the izvewenie_id of this izvewenie put.
	 *
	 * @return the izvewenie_id of this izvewenie put
	 */
	public long getIzvewenie_id();

	/**
	 * Sets the izvewenie_id of this izvewenie put.
	 *
	 * @param izvewenie_id the izvewenie_id of this izvewenie put
	 */
	public void setIzvewenie_id(long izvewenie_id);

	/**
	 * Returns the izvewenie_put_id of this izvewenie put.
	 *
	 * @return the izvewenie_put_id of this izvewenie put
	 */
	public long getIzvewenie_put_id();

	/**
	 * Sets the izvewenie_put_id of this izvewenie put.
	 *
	 * @param izvewenie_put_id the izvewenie_put_id of this izvewenie put
	 */
	public void setIzvewenie_put_id(long izvewenie_put_id);

	/**
	 * Returns the put_a of this izvewenie put.
	 *
	 * @return the put_a of this izvewenie put
	 */
	public long getPut_a();

	/**
	 * Sets the put_a of this izvewenie put.
	 *
	 * @param put_a the put_a of this izvewenie put
	 */
	public void setPut_a(long put_a);

	/**
	 * Returns the put_b of this izvewenie put.
	 *
	 * @return the put_b of this izvewenie put
	 */
	public long getPut_b();

	/**
	 * Sets the put_b of this izvewenie put.
	 *
	 * @param put_b the put_b of this izvewenie put
	 */
	public void setPut_b(long put_b);

	/**
	 * Returns the put_c of this izvewenie put.
	 *
	 * @return the put_c of this izvewenie put
	 */
	@AutoEscape
	public String getPut_c();

	/**
	 * Sets the put_c of this izvewenie put.
	 *
	 * @param put_c the put_c of this izvewenie put
	 */
	public void setPut_c(String put_c);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.izvewenieput.model.IzveweniePut izveweniePut);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.izvewenieput.model.IzveweniePut> toCacheModel();

	@Override
	public tj.izvewenieput.model.IzveweniePut toEscapedModel();

	@Override
	public tj.izvewenieput.model.IzveweniePut toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}