/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.lots.winner.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the LotsWinner service. Represents a row in the &quot;sapp.lot_winner&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.lots.winner.model.impl.LotsWinnerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.lots.winner.model.impl.LotsWinnerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LotsWinner
 * @see tj.lots.winner.model.impl.LotsWinnerImpl
 * @see tj.lots.winner.model.impl.LotsWinnerModelImpl
 * @generated
 */
@ProviderType
public interface LotsWinnerModel extends BaseModel<LotsWinner> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lots winner model instance should use the {@link LotsWinner} interface instead.
	 */

	/**
	 * Returns the primary key of this lots winner.
	 *
	 * @return the primary key of this lots winner
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lots winner.
	 *
	 * @param primaryKey the primary key of this lots winner
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lot_winner_id of this lots winner.
	 *
	 * @return the lot_winner_id of this lots winner
	 */
	public long getLot_winner_id();

	/**
	 * Sets the lot_winner_id of this lots winner.
	 *
	 * @param lot_winner_id the lot_winner_id of this lots winner
	 */
	public void setLot_winner_id(long lot_winner_id);

	/**
	 * Returns the spisok_lotov_id of this lots winner.
	 *
	 * @return the spisok_lotov_id of this lots winner
	 */
	public long getSpisok_lotov_id();

	/**
	 * Sets the spisok_lotov_id of this lots winner.
	 *
	 * @param spisok_lotov_id the spisok_lotov_id of this lots winner
	 */
	public void setSpisok_lotov_id(long spisok_lotov_id);

	/**
	 * Returns the organization_id of this lots winner.
	 *
	 * @return the organization_id of this lots winner
	 */
	public long getOrganization_id();

	/**
	 * Sets the organization_id of this lots winner.
	 *
	 * @param organization_id the organization_id of this lots winner
	 */
	public void setOrganization_id(long organization_id);

	/**
	 * Returns the total_price of this lots winner.
	 *
	 * @return the total_price of this lots winner
	 */
	public double getTotal_price();

	/**
	 * Sets the total_price of this lots winner.
	 *
	 * @param total_price the total_price of this lots winner
	 */
	public void setTotal_price(double total_price);

	/**
	 * Returns the attribute of this lots winner.
	 *
	 * @return the attribute of this lots winner
	 */
	@AutoEscape
	public String getAttribute();

	/**
	 * Sets the attribute of this lots winner.
	 *
	 * @param attribute the attribute of this lots winner
	 */
	public void setAttribute(String attribute);

	/**
	 * Returns the serial_number of this lots winner.
	 *
	 * @return the serial_number of this lots winner
	 */
	public int getSerial_number();

	/**
	 * Sets the serial_number of this lots winner.
	 *
	 * @param serial_number the serial_number of this lots winner
	 */
	public void setSerial_number(int serial_number);

	/**
	 * Returns the point of this lots winner.
	 *
	 * @return the point of this lots winner
	 */
	public double getPoint();

	/**
	 * Sets the point of this lots winner.
	 *
	 * @param point the point of this lots winner
	 */
	public void setPoint(double point);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.lots.winner.model.LotsWinner lotsWinner);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.lots.winner.model.LotsWinner> toCacheModel();

	@Override
	public tj.lots.winner.model.LotsWinner toEscapedModel();

	@Override
	public tj.lots.winner.model.LotsWinner toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}