/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.strany.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Strany service. Represents a row in the &quot;sapp.strany&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.strany.model.impl.StranyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.strany.model.impl.StranyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Strany
 * @see tj.strany.model.impl.StranyImpl
 * @see tj.strany.model.impl.StranyModelImpl
 * @generated
 */
@ProviderType
public interface StranyModel extends BaseModel<Strany> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a strany model instance should use the {@link Strany} interface instead.
	 */

	/**
	 * Returns the primary key of this strany.
	 *
	 * @return the primary key of this strany
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this strany.
	 *
	 * @param primaryKey the primary key of this strany
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the nazvanie of this strany.
	 *
	 * @return the nazvanie of this strany
	 */
	@AutoEscape
	public String getNazvanie();

	/**
	 * Sets the nazvanie of this strany.
	 *
	 * @param nazvanie the nazvanie of this strany
	 */
	public void setNazvanie(String nazvanie);

	/**
	 * Returns the nazvanie_tj of this strany.
	 *
	 * @return the nazvanie_tj of this strany
	 */
	@AutoEscape
	public String getNazvanie_tj();

	/**
	 * Sets the nazvanie_tj of this strany.
	 *
	 * @param nazvanie_tj the nazvanie_tj of this strany
	 */
	public void setNazvanie_tj(String nazvanie_tj);

	/**
	 * Returns the strany_id of this strany.
	 *
	 * @return the strany_id of this strany
	 */
	public long getStrany_id();

	/**
	 * Sets the strany_id of this strany.
	 *
	 * @param strany_id the strany_id of this strany
	 */
	public void setStrany_id(long strany_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.strany.model.Strany strany);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.strany.model.Strany> toCacheModel();

	@Override
	public tj.strany.model.Strany toEscapedModel();

	@Override
	public tj.strany.model.Strany toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}