/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.istochnik.finansirovanija.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the IstochnikFinansirovanija service. Represents a row in the &quot;sapp.istochnik_finansirovanija&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.istochnik.finansirovanija.model.impl.IstochnikFinansirovanijaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.istochnik.finansirovanija.model.impl.IstochnikFinansirovanijaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see IstochnikFinansirovanija
 * @see tj.istochnik.finansirovanija.model.impl.IstochnikFinansirovanijaImpl
 * @see tj.istochnik.finansirovanija.model.impl.IstochnikFinansirovanijaModelImpl
 * @generated
 */
@ProviderType
public interface IstochnikFinansirovanijaModel extends BaseModel<IstochnikFinansirovanija> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a istochnik finansirovanija model instance should use the {@link IstochnikFinansirovanija} interface instead.
	 */

	/**
	 * Returns the primary key of this istochnik finansirovanija.
	 *
	 * @return the primary key of this istochnik finansirovanija
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this istochnik finansirovanija.
	 *
	 * @param primaryKey the primary key of this istochnik finansirovanija
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the istochnik_finansirovanija_id of this istochnik finansirovanija.
	 *
	 * @return the istochnik_finansirovanija_id of this istochnik finansirovanija
	 */
	public long getIstochnik_finansirovanija_id();

	/**
	 * Sets the istochnik_finansirovanija_id of this istochnik finansirovanija.
	 *
	 * @param istochnik_finansirovanija_id the istochnik_finansirovanija_id of this istochnik finansirovanija
	 */
	public void setIstochnik_finansirovanija_id(
		long istochnik_finansirovanija_id);

	/**
	 * Returns the naimenovanie of this istochnik finansirovanija.
	 *
	 * @return the naimenovanie of this istochnik finansirovanija
	 */
	@AutoEscape
	public String getNaimenovanie();

	/**
	 * Sets the naimenovanie of this istochnik finansirovanija.
	 *
	 * @param naimenovanie the naimenovanie of this istochnik finansirovanija
	 */
	public void setNaimenovanie(String naimenovanie);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.istochnik.finansirovanija.model.IstochnikFinansirovanija istochnikFinansirovanija);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.istochnik.finansirovanija.model.IstochnikFinansirovanija> toCacheModel();

	@Override
	public tj.istochnik.finansirovanija.model.IstochnikFinansirovanija toEscapedModel();

	@Override
	public tj.istochnik.finansirovanija.model.IstochnikFinansirovanija toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}