/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.fbk.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Fbk service. Represents a row in the &quot;klassifikatory.fbk&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.fbk.model.impl.FbkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.fbk.model.impl.FbkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Fbk
 * @see tj.fbk.model.impl.FbkImpl
 * @see tj.fbk.model.impl.FbkModelImpl
 * @generated
 */
@ProviderType
public interface FbkModel extends BaseModel<Fbk> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fbk model instance should use the {@link Fbk} interface instead.
	 */

	/**
	 * Returns the primary key of this fbk.
	 *
	 * @return the primary key of this fbk
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fbk.
	 *
	 * @param primaryKey the primary key of this fbk
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the fbk_id of this fbk.
	 *
	 * @return the fbk_id of this fbk
	 */
	public long getFbk_id();

	/**
	 * Sets the fbk_id of this fbk.
	 *
	 * @param fbk_id the fbk_id of this fbk
	 */
	public void setFbk_id(long fbk_id);

	/**
	 * Returns the pid of this fbk.
	 *
	 * @return the pid of this fbk
	 */
	public int getPid();

	/**
	 * Sets the pid of this fbk.
	 *
	 * @param pid the pid of this fbk
	 */
	public void setPid(int pid);

	/**
	 * Returns the kod of this fbk.
	 *
	 * @return the kod of this fbk
	 */
	@AutoEscape
	public String getKod();

	/**
	 * Sets the kod of this fbk.
	 *
	 * @param kod the kod of this fbk
	 */
	public void setKod(String kod);

	/**
	 * Returns the nazvanie_ru of this fbk.
	 *
	 * @return the nazvanie_ru of this fbk
	 */
	@AutoEscape
	public String getNazvanie_ru();

	/**
	 * Sets the nazvanie_ru of this fbk.
	 *
	 * @param nazvanie_ru the nazvanie_ru of this fbk
	 */
	public void setNazvanie_ru(String nazvanie_ru);

	/**
	 * Returns the nazvanie_en of this fbk.
	 *
	 * @return the nazvanie_en of this fbk
	 */
	@AutoEscape
	public String getNazvanie_en();

	/**
	 * Sets the nazvanie_en of this fbk.
	 *
	 * @param nazvanie_en the nazvanie_en of this fbk
	 */
	public void setNazvanie_en(String nazvanie_en);

	/**
	 * Returns the nazvanie_tj of this fbk.
	 *
	 * @return the nazvanie_tj of this fbk
	 */
	@AutoEscape
	public String getNazvanie_tj();

	/**
	 * Sets the nazvanie_tj of this fbk.
	 *
	 * @param nazvanie_tj the nazvanie_tj of this fbk
	 */
	public void setNazvanie_tj(String nazvanie_tj);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.fbk.model.Fbk fbk);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.fbk.model.Fbk> toCacheModel();

	@Override
	public tj.fbk.model.Fbk toEscapedModel();

	@Override
	public tj.fbk.model.Fbk toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}