/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.spisok.lotov.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tj.spisok.lotov.model.spisok_lotov;
import tj.spisok.lotov.service.persistence.spisok_lotovPersistence;
import tj.spisok.lotov.service.spisok_lotovLocalService;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the spisok_lotov local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tj.spisok.lotov.service.impl.spisok_lotovLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tj.spisok.lotov.service.impl.spisok_lotovLocalServiceImpl
 * @see tj.spisok.lotov.service.spisok_lotovLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class spisok_lotovLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements spisok_lotovLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tj.spisok.lotov.service.spisok_lotovLocalServiceUtil} to access the spisok_lotov local service.
	 */

	/**
	 * Adds the spisok_lotov to the database. Also notifies the appropriate model listeners.
	 *
	 * @param spisok_lotov the spisok_lotov
	 * @return the spisok_lotov that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public spisok_lotov addspisok_lotov(spisok_lotov spisok_lotov) {
		spisok_lotov.setNew(true);

		return spisok_lotovPersistence.update(spisok_lotov);
	}

	/**
	 * Creates a new spisok_lotov with the primary key. Does not add the spisok_lotov to the database.
	 *
	 * @param spisok_lotov_id the primary key for the new spisok_lotov
	 * @return the new spisok_lotov
	 */
	@Override
	public spisok_lotov createspisok_lotov(long spisok_lotov_id) {
		return spisok_lotovPersistence.create(spisok_lotov_id);
	}

	/**
	 * Deletes the spisok_lotov with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param spisok_lotov_id the primary key of the spisok_lotov
	 * @return the spisok_lotov that was removed
	 * @throws PortalException if a spisok_lotov with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public spisok_lotov deletespisok_lotov(long spisok_lotov_id)
		throws PortalException {
		return spisok_lotovPersistence.remove(spisok_lotov_id);
	}

	/**
	 * Deletes the spisok_lotov from the database. Also notifies the appropriate model listeners.
	 *
	 * @param spisok_lotov the spisok_lotov
	 * @return the spisok_lotov that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public spisok_lotov deletespisok_lotov(spisok_lotov spisok_lotov) {
		return spisok_lotovPersistence.remove(spisok_lotov);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(spisok_lotov.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return spisok_lotovPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.spisok.lotov.model.impl.spisok_lotovModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return spisok_lotovPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.spisok.lotov.model.impl.spisok_lotovModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return spisok_lotovPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return spisok_lotovPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return spisok_lotovPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public spisok_lotov fetchspisok_lotov(long spisok_lotov_id) {
		return spisok_lotovPersistence.fetchByPrimaryKey(spisok_lotov_id);
	}

	/**
	 * Returns the spisok_lotov with the primary key.
	 *
	 * @param spisok_lotov_id the primary key of the spisok_lotov
	 * @return the spisok_lotov
	 * @throws PortalException if a spisok_lotov with the primary key could not be found
	 */
	@Override
	public spisok_lotov getspisok_lotov(long spisok_lotov_id)
		throws PortalException {
		return spisok_lotovPersistence.findByPrimaryKey(spisok_lotov_id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(spisok_lotovLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(spisok_lotov.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("spisok_lotov_id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(spisok_lotovLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(spisok_lotov.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"spisok_lotov_id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(spisok_lotovLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(spisok_lotov.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("spisok_lotov_id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return spisok_lotovLocalService.deletespisok_lotov((spisok_lotov)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return spisok_lotovPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the spisok_lotovs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.spisok.lotov.model.impl.spisok_lotovModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of spisok_lotovs
	 * @param end the upper bound of the range of spisok_lotovs (not inclusive)
	 * @return the range of spisok_lotovs
	 */
	@Override
	public List<spisok_lotov> getspisok_lotovs(int start, int end) {
		return spisok_lotovPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of spisok_lotovs.
	 *
	 * @return the number of spisok_lotovs
	 */
	@Override
	public int getspisok_lotovsCount() {
		return spisok_lotovPersistence.countAll();
	}

	/**
	 * Updates the spisok_lotov in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param spisok_lotov the spisok_lotov
	 * @return the spisok_lotov that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public spisok_lotov updatespisok_lotov(spisok_lotov spisok_lotov) {
		return spisok_lotovPersistence.update(spisok_lotov);
	}

	/**
	 * Returns the spisok_lotov local service.
	 *
	 * @return the spisok_lotov local service
	 */
	public spisok_lotovLocalService getspisok_lotovLocalService() {
		return spisok_lotovLocalService;
	}

	/**
	 * Sets the spisok_lotov local service.
	 *
	 * @param spisok_lotovLocalService the spisok_lotov local service
	 */
	public void setspisok_lotovLocalService(
		spisok_lotovLocalService spisok_lotovLocalService) {
		this.spisok_lotovLocalService = spisok_lotovLocalService;
	}

	/**
	 * Returns the spisok_lotov persistence.
	 *
	 * @return the spisok_lotov persistence
	 */
	public spisok_lotovPersistence getspisok_lotovPersistence() {
		return spisok_lotovPersistence;
	}

	/**
	 * Sets the spisok_lotov persistence.
	 *
	 * @param spisok_lotovPersistence the spisok_lotov persistence
	 */
	public void setspisok_lotovPersistence(
		spisok_lotovPersistence spisok_lotovPersistence) {
		this.spisok_lotovPersistence = spisok_lotovPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("tj.spisok.lotov.model.spisok_lotov",
			spisok_lotovLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"tj.spisok.lotov.model.spisok_lotov");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return spisok_lotovLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return spisok_lotov.class;
	}

	protected String getModelClassName() {
		return spisok_lotov.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = spisok_lotovPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = spisok_lotovLocalService.class)
	protected spisok_lotovLocalService spisok_lotovLocalService;
	@BeanReference(type = spisok_lotovPersistence.class)
	protected spisok_lotovPersistence spisok_lotovPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}