/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.istochnik.finansirovanija.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.istochnik.finansirovanija.model.IstochnikFinansirovanija;
import tj.istochnik.finansirovanija.model.IstochnikFinansirovanijaModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the IstochnikFinansirovanija service. Represents a row in the &quot;sapp.istochnik_finansirovanija&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link IstochnikFinansirovanijaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IstochnikFinansirovanijaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see IstochnikFinansirovanijaImpl
 * @see IstochnikFinansirovanija
 * @see IstochnikFinansirovanijaModel
 * @generated
 */
@ProviderType
public class IstochnikFinansirovanijaModelImpl extends BaseModelImpl<IstochnikFinansirovanija>
	implements IstochnikFinansirovanijaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a istochnik finansirovanija model instance should use the {@link IstochnikFinansirovanija} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.istochnik_finansirovanija";
	public static final Object[][] TABLE_COLUMNS = {
			{ "istochnik_finansirovanija_id", Types.BIGINT },
			{ "naimenovanie", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("istochnik_finansirovanija_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("naimenovanie", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.istochnik_finansirovanija (istochnik_finansirovanija_id LONG not null primary key,naimenovanie VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table sapp.istochnik_finansirovanija";
	public static final String ORDER_BY_JPQL = " ORDER BY istochnikFinansirovanija.istochnik_finansirovanija_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.istochnik_finansirovanija.istochnik_finansirovanija_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.istochnik.finansirovanija.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.istochnik.finansirovanija.model.IstochnikFinansirovanija"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.istochnik.finansirovanija.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.istochnik.finansirovanija.model.IstochnikFinansirovanija"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.istochnik.finansirovanija.service.util.ServiceProps.get(
				"lock.expiration.time.tj.istochnik.finansirovanija.model.IstochnikFinansirovanija"));

	public IstochnikFinansirovanijaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _istochnik_finansirovanija_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIstochnik_finansirovanija_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _istochnik_finansirovanija_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return IstochnikFinansirovanija.class;
	}

	@Override
	public String getModelClassName() {
		return IstochnikFinansirovanija.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("istochnik_finansirovanija_id",
			getIstochnik_finansirovanija_id());
		attributes.put("naimenovanie", getNaimenovanie());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long istochnik_finansirovanija_id = (Long)attributes.get(
				"istochnik_finansirovanija_id");

		if (istochnik_finansirovanija_id != null) {
			setIstochnik_finansirovanija_id(istochnik_finansirovanija_id);
		}

		String naimenovanie = (String)attributes.get("naimenovanie");

		if (naimenovanie != null) {
			setNaimenovanie(naimenovanie);
		}
	}

	@Override
	public long getIstochnik_finansirovanija_id() {
		return _istochnik_finansirovanija_id;
	}

	@Override
	public void setIstochnik_finansirovanija_id(
		long istochnik_finansirovanija_id) {
		_istochnik_finansirovanija_id = istochnik_finansirovanija_id;
	}

	@Override
	public String getNaimenovanie() {
		if (_naimenovanie == null) {
			return StringPool.BLANK;
		}
		else {
			return _naimenovanie;
		}
	}

	@Override
	public void setNaimenovanie(String naimenovanie) {
		_naimenovanie = naimenovanie;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			IstochnikFinansirovanija.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public IstochnikFinansirovanija toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (IstochnikFinansirovanija)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		IstochnikFinansirovanijaImpl istochnikFinansirovanijaImpl = new IstochnikFinansirovanijaImpl();

		istochnikFinansirovanijaImpl.setIstochnik_finansirovanija_id(getIstochnik_finansirovanija_id());
		istochnikFinansirovanijaImpl.setNaimenovanie(getNaimenovanie());

		istochnikFinansirovanijaImpl.resetOriginalValues();

		return istochnikFinansirovanijaImpl;
	}

	@Override
	public int compareTo(IstochnikFinansirovanija istochnikFinansirovanija) {
		long primaryKey = istochnikFinansirovanija.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof IstochnikFinansirovanija)) {
			return false;
		}

		IstochnikFinansirovanija istochnikFinansirovanija = (IstochnikFinansirovanija)obj;

		long primaryKey = istochnikFinansirovanija.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<IstochnikFinansirovanija> toCacheModel() {
		IstochnikFinansirovanijaCacheModel istochnikFinansirovanijaCacheModel = new IstochnikFinansirovanijaCacheModel();

		istochnikFinansirovanijaCacheModel.istochnik_finansirovanija_id = getIstochnik_finansirovanija_id();

		istochnikFinansirovanijaCacheModel.naimenovanie = getNaimenovanie();

		String naimenovanie = istochnikFinansirovanijaCacheModel.naimenovanie;

		if ((naimenovanie != null) && (naimenovanie.length() == 0)) {
			istochnikFinansirovanijaCacheModel.naimenovanie = null;
		}

		return istochnikFinansirovanijaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{istochnik_finansirovanija_id=");
		sb.append(getIstochnik_finansirovanija_id());
		sb.append(", naimenovanie=");
		sb.append(getNaimenovanie());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("tj.istochnik.finansirovanija.model.IstochnikFinansirovanija");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>istochnik_finansirovanija_id</column-name><column-value><![CDATA[");
		sb.append(getIstochnik_finansirovanija_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>naimenovanie</column-name><column-value><![CDATA[");
		sb.append(getNaimenovanie());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = IstochnikFinansirovanija.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			IstochnikFinansirovanija.class
		};
	private long _istochnik_finansirovanija_id;
	private String _naimenovanie;
	private IstochnikFinansirovanija _escapedModel;
}