/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.obwaja.informacija.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.obwaja.informacija.model.ObwajaInformacija;
import tj.obwaja.informacija.model.ObwajaInformacijaModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ObwajaInformacija service. Represents a row in the &quot;sapp.obwaja_informacija&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ObwajaInformacijaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ObwajaInformacijaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ObwajaInformacijaImpl
 * @see ObwajaInformacija
 * @see ObwajaInformacijaModel
 * @generated
 */
@ProviderType
public class ObwajaInformacijaModelImpl extends BaseModelImpl<ObwajaInformacija>
	implements ObwajaInformacijaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a obwaja informacija model instance should use the {@link ObwajaInformacija} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.obwaja_informacija";
	public static final Object[][] TABLE_COLUMNS = {
			{ "data_izmenenija", Types.TIMESTAMP },
			{ "data_sozdanija", Types.TIMESTAMP },
			{ "izmenil", Types.BIGINT },
			{ "izvewenie_id", Types.BIGINT },
			{ "je_pochta", Types.VARCHAR },
			{ "kontaktnoe_lico", Types.VARCHAR },
			{ "kontaktnyj_telefon", Types.VARCHAR },
			{ "obwaja_informacija_id", Types.BIGINT },
			{ "sozdal", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("data_izmenenija", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("data_sozdanija", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("izmenil", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("izvewenie_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("je_pochta", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("kontaktnoe_lico", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("kontaktnyj_telefon", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("obwaja_informacija_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sozdal", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.obwaja_informacija (data_izmenenija DATE null,data_sozdanija DATE null,izmenil LONG,izvewenie_id LONG,je_pochta VARCHAR(75) null,kontaktnoe_lico VARCHAR(75) null,kontaktnyj_telefon VARCHAR(75) null,obwaja_informacija_id LONG not null primary key,sozdal LONG)";
	public static final String TABLE_SQL_DROP = "drop table sapp.obwaja_informacija";
	public static final String ORDER_BY_JPQL = " ORDER BY obwajaInformacija.obwaja_informacija_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.obwaja_informacija.obwaja_informacija_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.obwaja.informacija.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.obwaja.informacija.model.ObwajaInformacija"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.obwaja.informacija.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.obwaja.informacija.model.ObwajaInformacija"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(tj.obwaja.informacija.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.tj.obwaja.informacija.model.ObwajaInformacija"),
			true);
	public static final long IZVEWENIE_ID_COLUMN_BITMASK = 1L;
	public static final long OBWAJA_INFORMACIJA_ID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.obwaja.informacija.service.util.ServiceProps.get(
				"lock.expiration.time.tj.obwaja.informacija.model.ObwajaInformacija"));

	public ObwajaInformacijaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _obwaja_informacija_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setObwaja_informacija_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _obwaja_informacija_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ObwajaInformacija.class;
	}

	@Override
	public String getModelClassName() {
		return ObwajaInformacija.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("data_izmenenija", getData_izmenenija());
		attributes.put("data_sozdanija", getData_sozdanija());
		attributes.put("izmenil", getIzmenil());
		attributes.put("izvewenie_id", getIzvewenie_id());
		attributes.put("je_pochta", getJe_pochta());
		attributes.put("kontaktnoe_lico", getKontaktnoe_lico());
		attributes.put("kontaktnyj_telefon", getKontaktnyj_telefon());
		attributes.put("obwaja_informacija_id", getObwaja_informacija_id());
		attributes.put("sozdal", getSozdal());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Date data_izmenenija = (Date)attributes.get("data_izmenenija");

		if (data_izmenenija != null) {
			setData_izmenenija(data_izmenenija);
		}

		Date data_sozdanija = (Date)attributes.get("data_sozdanija");

		if (data_sozdanija != null) {
			setData_sozdanija(data_sozdanija);
		}

		Long izmenil = (Long)attributes.get("izmenil");

		if (izmenil != null) {
			setIzmenil(izmenil);
		}

		Long izvewenie_id = (Long)attributes.get("izvewenie_id");

		if (izvewenie_id != null) {
			setIzvewenie_id(izvewenie_id);
		}

		String je_pochta = (String)attributes.get("je_pochta");

		if (je_pochta != null) {
			setJe_pochta(je_pochta);
		}

		String kontaktnoe_lico = (String)attributes.get("kontaktnoe_lico");

		if (kontaktnoe_lico != null) {
			setKontaktnoe_lico(kontaktnoe_lico);
		}

		String kontaktnyj_telefon = (String)attributes.get("kontaktnyj_telefon");

		if (kontaktnyj_telefon != null) {
			setKontaktnyj_telefon(kontaktnyj_telefon);
		}

		Long obwaja_informacija_id = (Long)attributes.get(
				"obwaja_informacija_id");

		if (obwaja_informacija_id != null) {
			setObwaja_informacija_id(obwaja_informacija_id);
		}

		Long sozdal = (Long)attributes.get("sozdal");

		if (sozdal != null) {
			setSozdal(sozdal);
		}
	}

	@Override
	public Date getData_izmenenija() {
		return _data_izmenenija;
	}

	@Override
	public void setData_izmenenija(Date data_izmenenija) {
		_data_izmenenija = data_izmenenija;
	}

	@Override
	public Date getData_sozdanija() {
		return _data_sozdanija;
	}

	@Override
	public void setData_sozdanija(Date data_sozdanija) {
		_data_sozdanija = data_sozdanija;
	}

	@Override
	public long getIzmenil() {
		return _izmenil;
	}

	@Override
	public void setIzmenil(long izmenil) {
		_izmenil = izmenil;
	}

	@Override
	public long getIzvewenie_id() {
		return _izvewenie_id;
	}

	@Override
	public void setIzvewenie_id(long izvewenie_id) {
		_columnBitmask |= IZVEWENIE_ID_COLUMN_BITMASK;

		if (!_setOriginalIzvewenie_id) {
			_setOriginalIzvewenie_id = true;

			_originalIzvewenie_id = _izvewenie_id;
		}

		_izvewenie_id = izvewenie_id;
	}

	public long getOriginalIzvewenie_id() {
		return _originalIzvewenie_id;
	}

	@Override
	public String getJe_pochta() {
		if (_je_pochta == null) {
			return StringPool.BLANK;
		}
		else {
			return _je_pochta;
		}
	}

	@Override
	public void setJe_pochta(String je_pochta) {
		_je_pochta = je_pochta;
	}

	@Override
	public String getKontaktnoe_lico() {
		if (_kontaktnoe_lico == null) {
			return StringPool.BLANK;
		}
		else {
			return _kontaktnoe_lico;
		}
	}

	@Override
	public void setKontaktnoe_lico(String kontaktnoe_lico) {
		_kontaktnoe_lico = kontaktnoe_lico;
	}

	@Override
	public String getKontaktnyj_telefon() {
		if (_kontaktnyj_telefon == null) {
			return StringPool.BLANK;
		}
		else {
			return _kontaktnyj_telefon;
		}
	}

	@Override
	public void setKontaktnyj_telefon(String kontaktnyj_telefon) {
		_kontaktnyj_telefon = kontaktnyj_telefon;
	}

	@Override
	public long getObwaja_informacija_id() {
		return _obwaja_informacija_id;
	}

	@Override
	public void setObwaja_informacija_id(long obwaja_informacija_id) {
		_obwaja_informacija_id = obwaja_informacija_id;
	}

	@Override
	public long getSozdal() {
		return _sozdal;
	}

	@Override
	public void setSozdal(long sozdal) {
		_sozdal = sozdal;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ObwajaInformacija.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ObwajaInformacija toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ObwajaInformacija)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ObwajaInformacijaImpl obwajaInformacijaImpl = new ObwajaInformacijaImpl();

		obwajaInformacijaImpl.setData_izmenenija(getData_izmenenija());
		obwajaInformacijaImpl.setData_sozdanija(getData_sozdanija());
		obwajaInformacijaImpl.setIzmenil(getIzmenil());
		obwajaInformacijaImpl.setIzvewenie_id(getIzvewenie_id());
		obwajaInformacijaImpl.setJe_pochta(getJe_pochta());
		obwajaInformacijaImpl.setKontaktnoe_lico(getKontaktnoe_lico());
		obwajaInformacijaImpl.setKontaktnyj_telefon(getKontaktnyj_telefon());
		obwajaInformacijaImpl.setObwaja_informacija_id(getObwaja_informacija_id());
		obwajaInformacijaImpl.setSozdal(getSozdal());

		obwajaInformacijaImpl.resetOriginalValues();

		return obwajaInformacijaImpl;
	}

	@Override
	public int compareTo(ObwajaInformacija obwajaInformacija) {
		long primaryKey = obwajaInformacija.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ObwajaInformacija)) {
			return false;
		}

		ObwajaInformacija obwajaInformacija = (ObwajaInformacija)obj;

		long primaryKey = obwajaInformacija.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ObwajaInformacijaModelImpl obwajaInformacijaModelImpl = this;

		obwajaInformacijaModelImpl._originalIzvewenie_id = obwajaInformacijaModelImpl._izvewenie_id;

		obwajaInformacijaModelImpl._setOriginalIzvewenie_id = false;

		obwajaInformacijaModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ObwajaInformacija> toCacheModel() {
		ObwajaInformacijaCacheModel obwajaInformacijaCacheModel = new ObwajaInformacijaCacheModel();

		Date data_izmenenija = getData_izmenenija();

		if (data_izmenenija != null) {
			obwajaInformacijaCacheModel.data_izmenenija = data_izmenenija.getTime();
		}
		else {
			obwajaInformacijaCacheModel.data_izmenenija = Long.MIN_VALUE;
		}

		Date data_sozdanija = getData_sozdanija();

		if (data_sozdanija != null) {
			obwajaInformacijaCacheModel.data_sozdanija = data_sozdanija.getTime();
		}
		else {
			obwajaInformacijaCacheModel.data_sozdanija = Long.MIN_VALUE;
		}

		obwajaInformacijaCacheModel.izmenil = getIzmenil();

		obwajaInformacijaCacheModel.izvewenie_id = getIzvewenie_id();

		obwajaInformacijaCacheModel.je_pochta = getJe_pochta();

		String je_pochta = obwajaInformacijaCacheModel.je_pochta;

		if ((je_pochta != null) && (je_pochta.length() == 0)) {
			obwajaInformacijaCacheModel.je_pochta = null;
		}

		obwajaInformacijaCacheModel.kontaktnoe_lico = getKontaktnoe_lico();

		String kontaktnoe_lico = obwajaInformacijaCacheModel.kontaktnoe_lico;

		if ((kontaktnoe_lico != null) && (kontaktnoe_lico.length() == 0)) {
			obwajaInformacijaCacheModel.kontaktnoe_lico = null;
		}

		obwajaInformacijaCacheModel.kontaktnyj_telefon = getKontaktnyj_telefon();

		String kontaktnyj_telefon = obwajaInformacijaCacheModel.kontaktnyj_telefon;

		if ((kontaktnyj_telefon != null) && (kontaktnyj_telefon.length() == 0)) {
			obwajaInformacijaCacheModel.kontaktnyj_telefon = null;
		}

		obwajaInformacijaCacheModel.obwaja_informacija_id = getObwaja_informacija_id();

		obwajaInformacijaCacheModel.sozdal = getSozdal();

		return obwajaInformacijaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{data_izmenenija=");
		sb.append(getData_izmenenija());
		sb.append(", data_sozdanija=");
		sb.append(getData_sozdanija());
		sb.append(", izmenil=");
		sb.append(getIzmenil());
		sb.append(", izvewenie_id=");
		sb.append(getIzvewenie_id());
		sb.append(", je_pochta=");
		sb.append(getJe_pochta());
		sb.append(", kontaktnoe_lico=");
		sb.append(getKontaktnoe_lico());
		sb.append(", kontaktnyj_telefon=");
		sb.append(getKontaktnyj_telefon());
		sb.append(", obwaja_informacija_id=");
		sb.append(getObwaja_informacija_id());
		sb.append(", sozdal=");
		sb.append(getSozdal());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("tj.obwaja.informacija.model.ObwajaInformacija");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>data_izmenenija</column-name><column-value><![CDATA[");
		sb.append(getData_izmenenija());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data_sozdanija</column-name><column-value><![CDATA[");
		sb.append(getData_sozdanija());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izmenil</column-name><column-value><![CDATA[");
		sb.append(getIzmenil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izvewenie_id</column-name><column-value><![CDATA[");
		sb.append(getIzvewenie_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>je_pochta</column-name><column-value><![CDATA[");
		sb.append(getJe_pochta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kontaktnoe_lico</column-name><column-value><![CDATA[");
		sb.append(getKontaktnoe_lico());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kontaktnyj_telefon</column-name><column-value><![CDATA[");
		sb.append(getKontaktnyj_telefon());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>obwaja_informacija_id</column-name><column-value><![CDATA[");
		sb.append(getObwaja_informacija_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sozdal</column-name><column-value><![CDATA[");
		sb.append(getSozdal());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ObwajaInformacija.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ObwajaInformacija.class
		};
	private Date _data_izmenenija;
	private Date _data_sozdanija;
	private long _izmenil;
	private long _izvewenie_id;
	private long _originalIzvewenie_id;
	private boolean _setOriginalIzvewenie_id;
	private String _je_pochta;
	private String _kontaktnoe_lico;
	private String _kontaktnyj_telefon;
	private long _obwaja_informacija_id;
	private long _sozdal;
	private long _columnBitmask;
	private ObwajaInformacija _escapedModel;
}