/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.obwaja.informacija.model.impl;

import aQute.bnd.annotation.ProviderType;

import tj.obwaja.informacija.model.ObwajaInformacija;
import tj.obwaja.informacija.service.ObwajaInformacijaLocalServiceUtil;

/**
 * The extended model base implementation for the ObwajaInformacija service. Represents a row in the &quot;sapp.obwaja_informacija&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ObwajaInformacijaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ObwajaInformacijaImpl
 * @see ObwajaInformacija
 * @generated
 */
@ProviderType
public abstract class ObwajaInformacijaBaseImpl
	extends ObwajaInformacijaModelImpl implements ObwajaInformacija {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a obwaja informacija model instance should use the {@link ObwajaInformacija} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ObwajaInformacijaLocalServiceUtil.addObwajaInformacija(this);
		}
		else {
			ObwajaInformacijaLocalServiceUtil.updateObwajaInformacija(this);
		}
	}
}