/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.tipy.izvewenij.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the tipy_izvewenij service. Represents a row in the &quot;sapp.tipy_izvewenij&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.tipy.izvewenij.model.impl.tipy_izvewenijModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.tipy.izvewenij.model.impl.tipy_izvewenijImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tipy_izvewenij
 * @see tj.tipy.izvewenij.model.impl.tipy_izvewenijImpl
 * @see tj.tipy.izvewenij.model.impl.tipy_izvewenijModelImpl
 * @generated
 */
@ProviderType
public interface tipy_izvewenijModel extends BaseModel<tipy_izvewenij> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tipy_izvewenij model instance should use the {@link tipy_izvewenij} interface instead.
	 */

	/**
	 * Returns the primary key of this tipy_izvewenij.
	 *
	 * @return the primary key of this tipy_izvewenij
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tipy_izvewenij.
	 *
	 * @param primaryKey the primary key of this tipy_izvewenij
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tip of this tipy_izvewenij.
	 *
	 * @return the tip of this tipy_izvewenij
	 */
	@AutoEscape
	public String getTip();

	/**
	 * Sets the tip of this tipy_izvewenij.
	 *
	 * @param tip the tip of this tipy_izvewenij
	 */
	public void setTip(String tip);

	/**
	 * Returns the tipy_izvewenij_id of this tipy_izvewenij.
	 *
	 * @return the tipy_izvewenij_id of this tipy_izvewenij
	 */
	public long getTipy_izvewenij_id();

	/**
	 * Sets the tipy_izvewenij_id of this tipy_izvewenij.
	 *
	 * @param tipy_izvewenij_id the tipy_izvewenij_id of this tipy_izvewenij
	 */
	public void setTipy_izvewenij_id(long tipy_izvewenij_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.tipy.izvewenij.model.tipy_izvewenij tipy_izvewenij);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.tipy.izvewenij.model.tipy_izvewenij> toCacheModel();

	@Override
	public tj.tipy.izvewenij.model.tipy_izvewenij toEscapedModel();

	@Override
	public tj.tipy.izvewenij.model.tipy_izvewenij toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}