/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.zajavki.ot.postavwikov.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.zajavki.ot.postavwikov.model.ZajavkiOtPostavwikov;
import tj.zajavki.ot.postavwikov.model.ZajavkiOtPostavwikovModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ZajavkiOtPostavwikov service. Represents a row in the &quot;sapp.zajavki_ot_postavwikov&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ZajavkiOtPostavwikovModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ZajavkiOtPostavwikovImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ZajavkiOtPostavwikovImpl
 * @see ZajavkiOtPostavwikov
 * @see ZajavkiOtPostavwikovModel
 * @generated
 */
@ProviderType
public class ZajavkiOtPostavwikovModelImpl extends BaseModelImpl<ZajavkiOtPostavwikov>
	implements ZajavkiOtPostavwikovModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a zajavki ot postavwikov model instance should use the {@link ZajavkiOtPostavwikov} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.zajavki_ot_postavwikov";
	public static final Object[][] TABLE_COLUMNS = {
			{ "zajavki_ot_postavwikov_id", Types.BIGINT },
			{ "izvewenie_id", Types.BIGINT },
			{ "lot_id", Types.BIGINT },
			{ "tovar_id", Types.BIGINT },
			{ "postavwik_id", Types.BIGINT },
			{ "kolichestvo", Types.INTEGER },
			{ "summa_za_edinicu_tovara", Types.DOUBLE },
			{ "itogo_za_tovar", Types.DOUBLE },
			{ "sozdal", Types.BIGINT },
			{ "izmenil", Types.BIGINT },
			{ "data_sozdanija", Types.TIMESTAMP },
			{ "data_izmenenija", Types.TIMESTAMP },
			{ "kod_po_obshhemu_klassifikatoru", Types.BIGINT },
			{ "kod_strany_proizvoditelja", Types.BIGINT },
			{ "opisanie_tovara", Types.VARCHAR },
			{ "predlozhenie_postavwika", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("zajavki_ot_postavwikov_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("izvewenie_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("lot_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tovar_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("postavwik_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("kolichestvo", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("summa_za_edinicu_tovara", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("itogo_za_tovar", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("sozdal", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("izmenil", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("data_sozdanija", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("data_izmenenija", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("kod_po_obshhemu_klassifikatoru", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("kod_strany_proizvoditelja", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("opisanie_tovara", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("predlozhenie_postavwika", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.zajavki_ot_postavwikov (zajavki_ot_postavwikov_id LONG not null primary key,izvewenie_id LONG,lot_id LONG,tovar_id LONG,postavwik_id LONG,kolichestvo INTEGER,summa_za_edinicu_tovara DOUBLE,itogo_za_tovar DOUBLE,sozdal LONG,izmenil LONG,data_sozdanija DATE null,data_izmenenija DATE null,kod_po_obshhemu_klassifikatoru LONG,kod_strany_proizvoditelja LONG,opisanie_tovara VARCHAR(75) null,predlozhenie_postavwika VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table sapp.zajavki_ot_postavwikov";
	public static final String ORDER_BY_JPQL = " ORDER BY zajavkiOtPostavwikov.zajavki_ot_postavwikov_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.zajavki_ot_postavwikov.zajavki_ot_postavwikov_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.zajavki.ot.postavwikov.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.zajavki.ot.postavwikov.model.ZajavkiOtPostavwikov"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.zajavki.ot.postavwikov.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.zajavki.ot.postavwikov.model.ZajavkiOtPostavwikov"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(tj.zajavki.ot.postavwikov.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.tj.zajavki.ot.postavwikov.model.ZajavkiOtPostavwikov"),
			true);
	public static final long LOT_ID_COLUMN_BITMASK = 1L;
	public static final long POSTAVWIK_ID_COLUMN_BITMASK = 2L;
	public static final long TOVAR_ID_COLUMN_BITMASK = 4L;
	public static final long ZAJAVKI_OT_POSTAVWIKOV_ID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.zajavki.ot.postavwikov.service.util.ServiceProps.get(
				"lock.expiration.time.tj.zajavki.ot.postavwikov.model.ZajavkiOtPostavwikov"));

	public ZajavkiOtPostavwikovModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _zajavki_ot_postavwikov_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setZajavki_ot_postavwikov_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _zajavki_ot_postavwikov_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ZajavkiOtPostavwikov.class;
	}

	@Override
	public String getModelClassName() {
		return ZajavkiOtPostavwikov.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("zajavki_ot_postavwikov_id",
			getZajavki_ot_postavwikov_id());
		attributes.put("izvewenie_id", getIzvewenie_id());
		attributes.put("lot_id", getLot_id());
		attributes.put("tovar_id", getTovar_id());
		attributes.put("postavwik_id", getPostavwik_id());
		attributes.put("kolichestvo", getKolichestvo());
		attributes.put("summa_za_edinicu_tovara", getSumma_za_edinicu_tovara());
		attributes.put("itogo_za_tovar", getItogo_za_tovar());
		attributes.put("sozdal", getSozdal());
		attributes.put("izmenil", getIzmenil());
		attributes.put("data_sozdanija", getData_sozdanija());
		attributes.put("data_izmenenija", getData_izmenenija());
		attributes.put("kod_po_obshhemu_klassifikatoru",
			getKod_po_obshhemu_klassifikatoru());
		attributes.put("kod_strany_proizvoditelja",
			getKod_strany_proizvoditelja());
		attributes.put("opisanie_tovara", getOpisanie_tovara());
		attributes.put("predlozhenie_postavwika", getPredlozhenie_postavwika());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long zajavki_ot_postavwikov_id = (Long)attributes.get(
				"zajavki_ot_postavwikov_id");

		if (zajavki_ot_postavwikov_id != null) {
			setZajavki_ot_postavwikov_id(zajavki_ot_postavwikov_id);
		}

		Long izvewenie_id = (Long)attributes.get("izvewenie_id");

		if (izvewenie_id != null) {
			setIzvewenie_id(izvewenie_id);
		}

		Long lot_id = (Long)attributes.get("lot_id");

		if (lot_id != null) {
			setLot_id(lot_id);
		}

		Long tovar_id = (Long)attributes.get("tovar_id");

		if (tovar_id != null) {
			setTovar_id(tovar_id);
		}

		Long postavwik_id = (Long)attributes.get("postavwik_id");

		if (postavwik_id != null) {
			setPostavwik_id(postavwik_id);
		}

		Integer kolichestvo = (Integer)attributes.get("kolichestvo");

		if (kolichestvo != null) {
			setKolichestvo(kolichestvo);
		}

		Double summa_za_edinicu_tovara = (Double)attributes.get(
				"summa_za_edinicu_tovara");

		if (summa_za_edinicu_tovara != null) {
			setSumma_za_edinicu_tovara(summa_za_edinicu_tovara);
		}

		Double itogo_za_tovar = (Double)attributes.get("itogo_za_tovar");

		if (itogo_za_tovar != null) {
			setItogo_za_tovar(itogo_za_tovar);
		}

		Long sozdal = (Long)attributes.get("sozdal");

		if (sozdal != null) {
			setSozdal(sozdal);
		}

		Long izmenil = (Long)attributes.get("izmenil");

		if (izmenil != null) {
			setIzmenil(izmenil);
		}

		Date data_sozdanija = (Date)attributes.get("data_sozdanija");

		if (data_sozdanija != null) {
			setData_sozdanija(data_sozdanija);
		}

		Date data_izmenenija = (Date)attributes.get("data_izmenenija");

		if (data_izmenenija != null) {
			setData_izmenenija(data_izmenenija);
		}

		Long kod_po_obshhemu_klassifikatoru = (Long)attributes.get(
				"kod_po_obshhemu_klassifikatoru");

		if (kod_po_obshhemu_klassifikatoru != null) {
			setKod_po_obshhemu_klassifikatoru(kod_po_obshhemu_klassifikatoru);
		}

		Long kod_strany_proizvoditelja = (Long)attributes.get(
				"kod_strany_proizvoditelja");

		if (kod_strany_proizvoditelja != null) {
			setKod_strany_proizvoditelja(kod_strany_proizvoditelja);
		}

		String opisanie_tovara = (String)attributes.get("opisanie_tovara");

		if (opisanie_tovara != null) {
			setOpisanie_tovara(opisanie_tovara);
		}

		String predlozhenie_postavwika = (String)attributes.get(
				"predlozhenie_postavwika");

		if (predlozhenie_postavwika != null) {
			setPredlozhenie_postavwika(predlozhenie_postavwika);
		}
	}

	@Override
	public long getZajavki_ot_postavwikov_id() {
		return _zajavki_ot_postavwikov_id;
	}

	@Override
	public void setZajavki_ot_postavwikov_id(long zajavki_ot_postavwikov_id) {
		_zajavki_ot_postavwikov_id = zajavki_ot_postavwikov_id;
	}

	@Override
	public long getIzvewenie_id() {
		return _izvewenie_id;
	}

	@Override
	public void setIzvewenie_id(long izvewenie_id) {
		_izvewenie_id = izvewenie_id;
	}

	@Override
	public long getLot_id() {
		return _lot_id;
	}

	@Override
	public void setLot_id(long lot_id) {
		_columnBitmask |= LOT_ID_COLUMN_BITMASK;

		if (!_setOriginalLot_id) {
			_setOriginalLot_id = true;

			_originalLot_id = _lot_id;
		}

		_lot_id = lot_id;
	}

	public long getOriginalLot_id() {
		return _originalLot_id;
	}

	@Override
	public long getTovar_id() {
		return _tovar_id;
	}

	@Override
	public void setTovar_id(long tovar_id) {
		_columnBitmask |= TOVAR_ID_COLUMN_BITMASK;

		if (!_setOriginalTovar_id) {
			_setOriginalTovar_id = true;

			_originalTovar_id = _tovar_id;
		}

		_tovar_id = tovar_id;
	}

	public long getOriginalTovar_id() {
		return _originalTovar_id;
	}

	@Override
	public long getPostavwik_id() {
		return _postavwik_id;
	}

	@Override
	public void setPostavwik_id(long postavwik_id) {
		_columnBitmask |= POSTAVWIK_ID_COLUMN_BITMASK;

		if (!_setOriginalPostavwik_id) {
			_setOriginalPostavwik_id = true;

			_originalPostavwik_id = _postavwik_id;
		}

		_postavwik_id = postavwik_id;
	}

	public long getOriginalPostavwik_id() {
		return _originalPostavwik_id;
	}

	@Override
	public int getKolichestvo() {
		return _kolichestvo;
	}

	@Override
	public void setKolichestvo(int kolichestvo) {
		_kolichestvo = kolichestvo;
	}

	@Override
	public double getSumma_za_edinicu_tovara() {
		return _summa_za_edinicu_tovara;
	}

	@Override
	public void setSumma_za_edinicu_tovara(double summa_za_edinicu_tovara) {
		_summa_za_edinicu_tovara = summa_za_edinicu_tovara;
	}

	@Override
	public double getItogo_za_tovar() {
		return _itogo_za_tovar;
	}

	@Override
	public void setItogo_za_tovar(double itogo_za_tovar) {
		_itogo_za_tovar = itogo_za_tovar;
	}

	@Override
	public long getSozdal() {
		return _sozdal;
	}

	@Override
	public void setSozdal(long sozdal) {
		_sozdal = sozdal;
	}

	@Override
	public long getIzmenil() {
		return _izmenil;
	}

	@Override
	public void setIzmenil(long izmenil) {
		_izmenil = izmenil;
	}

	@Override
	public Date getData_sozdanija() {
		return _data_sozdanija;
	}

	@Override
	public void setData_sozdanija(Date data_sozdanija) {
		_data_sozdanija = data_sozdanija;
	}

	@Override
	public Date getData_izmenenija() {
		return _data_izmenenija;
	}

	@Override
	public void setData_izmenenija(Date data_izmenenija) {
		_data_izmenenija = data_izmenenija;
	}

	@Override
	public long getKod_po_obshhemu_klassifikatoru() {
		return _kod_po_obshhemu_klassifikatoru;
	}

	@Override
	public void setKod_po_obshhemu_klassifikatoru(
		long kod_po_obshhemu_klassifikatoru) {
		_kod_po_obshhemu_klassifikatoru = kod_po_obshhemu_klassifikatoru;
	}

	@Override
	public long getKod_strany_proizvoditelja() {
		return _kod_strany_proizvoditelja;
	}

	@Override
	public void setKod_strany_proizvoditelja(long kod_strany_proizvoditelja) {
		_kod_strany_proizvoditelja = kod_strany_proizvoditelja;
	}

	@Override
	public String getOpisanie_tovara() {
		if (_opisanie_tovara == null) {
			return StringPool.BLANK;
		}
		else {
			return _opisanie_tovara;
		}
	}

	@Override
	public void setOpisanie_tovara(String opisanie_tovara) {
		_opisanie_tovara = opisanie_tovara;
	}

	@Override
	public String getPredlozhenie_postavwika() {
		if (_predlozhenie_postavwika == null) {
			return StringPool.BLANK;
		}
		else {
			return _predlozhenie_postavwika;
		}
	}

	@Override
	public void setPredlozhenie_postavwika(String predlozhenie_postavwika) {
		_predlozhenie_postavwika = predlozhenie_postavwika;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ZajavkiOtPostavwikov.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ZajavkiOtPostavwikov toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ZajavkiOtPostavwikov)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ZajavkiOtPostavwikovImpl zajavkiOtPostavwikovImpl = new ZajavkiOtPostavwikovImpl();

		zajavkiOtPostavwikovImpl.setZajavki_ot_postavwikov_id(getZajavki_ot_postavwikov_id());
		zajavkiOtPostavwikovImpl.setIzvewenie_id(getIzvewenie_id());
		zajavkiOtPostavwikovImpl.setLot_id(getLot_id());
		zajavkiOtPostavwikovImpl.setTovar_id(getTovar_id());
		zajavkiOtPostavwikovImpl.setPostavwik_id(getPostavwik_id());
		zajavkiOtPostavwikovImpl.setKolichestvo(getKolichestvo());
		zajavkiOtPostavwikovImpl.setSumma_za_edinicu_tovara(getSumma_za_edinicu_tovara());
		zajavkiOtPostavwikovImpl.setItogo_za_tovar(getItogo_za_tovar());
		zajavkiOtPostavwikovImpl.setSozdal(getSozdal());
		zajavkiOtPostavwikovImpl.setIzmenil(getIzmenil());
		zajavkiOtPostavwikovImpl.setData_sozdanija(getData_sozdanija());
		zajavkiOtPostavwikovImpl.setData_izmenenija(getData_izmenenija());
		zajavkiOtPostavwikovImpl.setKod_po_obshhemu_klassifikatoru(getKod_po_obshhemu_klassifikatoru());
		zajavkiOtPostavwikovImpl.setKod_strany_proizvoditelja(getKod_strany_proizvoditelja());
		zajavkiOtPostavwikovImpl.setOpisanie_tovara(getOpisanie_tovara());
		zajavkiOtPostavwikovImpl.setPredlozhenie_postavwika(getPredlozhenie_postavwika());

		zajavkiOtPostavwikovImpl.resetOriginalValues();

		return zajavkiOtPostavwikovImpl;
	}

	@Override
	public int compareTo(ZajavkiOtPostavwikov zajavkiOtPostavwikov) {
		long primaryKey = zajavkiOtPostavwikov.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ZajavkiOtPostavwikov)) {
			return false;
		}

		ZajavkiOtPostavwikov zajavkiOtPostavwikov = (ZajavkiOtPostavwikov)obj;

		long primaryKey = zajavkiOtPostavwikov.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ZajavkiOtPostavwikovModelImpl zajavkiOtPostavwikovModelImpl = this;

		zajavkiOtPostavwikovModelImpl._originalLot_id = zajavkiOtPostavwikovModelImpl._lot_id;

		zajavkiOtPostavwikovModelImpl._setOriginalLot_id = false;

		zajavkiOtPostavwikovModelImpl._originalTovar_id = zajavkiOtPostavwikovModelImpl._tovar_id;

		zajavkiOtPostavwikovModelImpl._setOriginalTovar_id = false;

		zajavkiOtPostavwikovModelImpl._originalPostavwik_id = zajavkiOtPostavwikovModelImpl._postavwik_id;

		zajavkiOtPostavwikovModelImpl._setOriginalPostavwik_id = false;

		zajavkiOtPostavwikovModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ZajavkiOtPostavwikov> toCacheModel() {
		ZajavkiOtPostavwikovCacheModel zajavkiOtPostavwikovCacheModel = new ZajavkiOtPostavwikovCacheModel();

		zajavkiOtPostavwikovCacheModel.zajavki_ot_postavwikov_id = getZajavki_ot_postavwikov_id();

		zajavkiOtPostavwikovCacheModel.izvewenie_id = getIzvewenie_id();

		zajavkiOtPostavwikovCacheModel.lot_id = getLot_id();

		zajavkiOtPostavwikovCacheModel.tovar_id = getTovar_id();

		zajavkiOtPostavwikovCacheModel.postavwik_id = getPostavwik_id();

		zajavkiOtPostavwikovCacheModel.kolichestvo = getKolichestvo();

		zajavkiOtPostavwikovCacheModel.summa_za_edinicu_tovara = getSumma_za_edinicu_tovara();

		zajavkiOtPostavwikovCacheModel.itogo_za_tovar = getItogo_za_tovar();

		zajavkiOtPostavwikovCacheModel.sozdal = getSozdal();

		zajavkiOtPostavwikovCacheModel.izmenil = getIzmenil();

		Date data_sozdanija = getData_sozdanija();

		if (data_sozdanija != null) {
			zajavkiOtPostavwikovCacheModel.data_sozdanija = data_sozdanija.getTime();
		}
		else {
			zajavkiOtPostavwikovCacheModel.data_sozdanija = Long.MIN_VALUE;
		}

		Date data_izmenenija = getData_izmenenija();

		if (data_izmenenija != null) {
			zajavkiOtPostavwikovCacheModel.data_izmenenija = data_izmenenija.getTime();
		}
		else {
			zajavkiOtPostavwikovCacheModel.data_izmenenija = Long.MIN_VALUE;
		}

		zajavkiOtPostavwikovCacheModel.kod_po_obshhemu_klassifikatoru = getKod_po_obshhemu_klassifikatoru();

		zajavkiOtPostavwikovCacheModel.kod_strany_proizvoditelja = getKod_strany_proizvoditelja();

		zajavkiOtPostavwikovCacheModel.opisanie_tovara = getOpisanie_tovara();

		String opisanie_tovara = zajavkiOtPostavwikovCacheModel.opisanie_tovara;

		if ((opisanie_tovara != null) && (opisanie_tovara.length() == 0)) {
			zajavkiOtPostavwikovCacheModel.opisanie_tovara = null;
		}

		zajavkiOtPostavwikovCacheModel.predlozhenie_postavwika = getPredlozhenie_postavwika();

		String predlozhenie_postavwika = zajavkiOtPostavwikovCacheModel.predlozhenie_postavwika;

		if ((predlozhenie_postavwika != null) &&
				(predlozhenie_postavwika.length() == 0)) {
			zajavkiOtPostavwikovCacheModel.predlozhenie_postavwika = null;
		}

		return zajavkiOtPostavwikovCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(33);

		sb.append("{zajavki_ot_postavwikov_id=");
		sb.append(getZajavki_ot_postavwikov_id());
		sb.append(", izvewenie_id=");
		sb.append(getIzvewenie_id());
		sb.append(", lot_id=");
		sb.append(getLot_id());
		sb.append(", tovar_id=");
		sb.append(getTovar_id());
		sb.append(", postavwik_id=");
		sb.append(getPostavwik_id());
		sb.append(", kolichestvo=");
		sb.append(getKolichestvo());
		sb.append(", summa_za_edinicu_tovara=");
		sb.append(getSumma_za_edinicu_tovara());
		sb.append(", itogo_za_tovar=");
		sb.append(getItogo_za_tovar());
		sb.append(", sozdal=");
		sb.append(getSozdal());
		sb.append(", izmenil=");
		sb.append(getIzmenil());
		sb.append(", data_sozdanija=");
		sb.append(getData_sozdanija());
		sb.append(", data_izmenenija=");
		sb.append(getData_izmenenija());
		sb.append(", kod_po_obshhemu_klassifikatoru=");
		sb.append(getKod_po_obshhemu_klassifikatoru());
		sb.append(", kod_strany_proizvoditelja=");
		sb.append(getKod_strany_proizvoditelja());
		sb.append(", opisanie_tovara=");
		sb.append(getOpisanie_tovara());
		sb.append(", predlozhenie_postavwika=");
		sb.append(getPredlozhenie_postavwika());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(52);

		sb.append("<model><model-name>");
		sb.append("tj.zajavki.ot.postavwikov.model.ZajavkiOtPostavwikov");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>zajavki_ot_postavwikov_id</column-name><column-value><![CDATA[");
		sb.append(getZajavki_ot_postavwikov_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izvewenie_id</column-name><column-value><![CDATA[");
		sb.append(getIzvewenie_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lot_id</column-name><column-value><![CDATA[");
		sb.append(getLot_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tovar_id</column-name><column-value><![CDATA[");
		sb.append(getTovar_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>postavwik_id</column-name><column-value><![CDATA[");
		sb.append(getPostavwik_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kolichestvo</column-name><column-value><![CDATA[");
		sb.append(getKolichestvo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>summa_za_edinicu_tovara</column-name><column-value><![CDATA[");
		sb.append(getSumma_za_edinicu_tovara());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>itogo_za_tovar</column-name><column-value><![CDATA[");
		sb.append(getItogo_za_tovar());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sozdal</column-name><column-value><![CDATA[");
		sb.append(getSozdal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izmenil</column-name><column-value><![CDATA[");
		sb.append(getIzmenil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data_sozdanija</column-name><column-value><![CDATA[");
		sb.append(getData_sozdanija());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data_izmenenija</column-name><column-value><![CDATA[");
		sb.append(getData_izmenenija());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kod_po_obshhemu_klassifikatoru</column-name><column-value><![CDATA[");
		sb.append(getKod_po_obshhemu_klassifikatoru());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kod_strany_proizvoditelja</column-name><column-value><![CDATA[");
		sb.append(getKod_strany_proizvoditelja());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>opisanie_tovara</column-name><column-value><![CDATA[");
		sb.append(getOpisanie_tovara());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>predlozhenie_postavwika</column-name><column-value><![CDATA[");
		sb.append(getPredlozhenie_postavwika());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ZajavkiOtPostavwikov.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ZajavkiOtPostavwikov.class
		};
	private long _zajavki_ot_postavwikov_id;
	private long _izvewenie_id;
	private long _lot_id;
	private long _originalLot_id;
	private boolean _setOriginalLot_id;
	private long _tovar_id;
	private long _originalTovar_id;
	private boolean _setOriginalTovar_id;
	private long _postavwik_id;
	private long _originalPostavwik_id;
	private boolean _setOriginalPostavwik_id;
	private int _kolichestvo;
	private double _summa_za_edinicu_tovara;
	private double _itogo_za_tovar;
	private long _sozdal;
	private long _izmenil;
	private Date _data_sozdanija;
	private Date _data_izmenenija;
	private long _kod_po_obshhemu_klassifikatoru;
	private long _kod_strany_proizvoditelja;
	private String _opisanie_tovara;
	private String _predlozhenie_postavwika;
	private long _columnBitmask;
	private ZajavkiOtPostavwikov _escapedModel;
}