/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.profil.polzovatelej.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the profil_polzovatelej service. Represents a row in the &quot;sapp.profil_polzovatelej&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.profil.polzovatelej.model.impl.profil_polzovatelejModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.profil.polzovatelej.model.impl.profil_polzovatelejImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see profil_polzovatelej
 * @see tj.profil.polzovatelej.model.impl.profil_polzovatelejImpl
 * @see tj.profil.polzovatelej.model.impl.profil_polzovatelejModelImpl
 * @generated
 */
@ProviderType
public interface profil_polzovatelejModel extends BaseModel<profil_polzovatelej> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a profil_polzovatelej model instance should use the {@link profil_polzovatelej} interface instead.
	 */

	/**
	 * Returns the primary key of this profil_polzovatelej.
	 *
	 * @return the primary key of this profil_polzovatelej
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this profil_polzovatelej.
	 *
	 * @param primaryKey the primary key of this profil_polzovatelej
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the profil_polzovatelej_id of this profil_polzovatelej.
	 *
	 * @return the profil_polzovatelej_id of this profil_polzovatelej
	 */
	public long getProfil_polzovatelej_id();

	/**
	 * Sets the profil_polzovatelej_id of this profil_polzovatelej.
	 *
	 * @param profil_polzovatelej_id the profil_polzovatelej_id of this profil_polzovatelej
	 */
	public void setProfil_polzovatelej_id(long profil_polzovatelej_id);

	/**
	 * Returns the polzovatel_id of this profil_polzovatelej.
	 *
	 * @return the polzovatel_id of this profil_polzovatelej
	 */
	public long getPolzovatel_id();

	/**
	 * Sets the polzovatel_id of this profil_polzovatelej.
	 *
	 * @param polzovatel_id the polzovatel_id of this profil_polzovatelej
	 */
	public void setPolzovatel_id(long polzovatel_id);

	/**
	 * Returns the inicialy of this profil_polzovatelej.
	 *
	 * @return the inicialy of this profil_polzovatelej
	 */
	@AutoEscape
	public String getInicialy();

	/**
	 * Sets the inicialy of this profil_polzovatelej.
	 *
	 * @param inicialy the inicialy of this profil_polzovatelej
	 */
	public void setInicialy(String inicialy);

	/**
	 * Returns the kontaktnyj_telefon of this profil_polzovatelej.
	 *
	 * @return the kontaktnyj_telefon of this profil_polzovatelej
	 */
	@AutoEscape
	public String getKontaktnyj_telefon();

	/**
	 * Sets the kontaktnyj_telefon of this profil_polzovatelej.
	 *
	 * @param kontaktnyj_telefon the kontaktnyj_telefon of this profil_polzovatelej
	 */
	public void setKontaktnyj_telefon(String kontaktnyj_telefon);

	/**
	 * Returns the je_pochta of this profil_polzovatelej.
	 *
	 * @return the je_pochta of this profil_polzovatelej
	 */
	@AutoEscape
	public String getJe_pochta();

	/**
	 * Sets the je_pochta of this profil_polzovatelej.
	 *
	 * @param je_pochta the je_pochta of this profil_polzovatelej
	 */
	public void setJe_pochta(String je_pochta);

	/**
	 * Returns the sozdal of this profil_polzovatelej.
	 *
	 * @return the sozdal of this profil_polzovatelej
	 */
	public long getSozdal();

	/**
	 * Sets the sozdal of this profil_polzovatelej.
	 *
	 * @param sozdal the sozdal of this profil_polzovatelej
	 */
	public void setSozdal(long sozdal);

	/**
	 * Returns the izmenil of this profil_polzovatelej.
	 *
	 * @return the izmenil of this profil_polzovatelej
	 */
	public long getIzmenil();

	/**
	 * Sets the izmenil of this profil_polzovatelej.
	 *
	 * @param izmenil the izmenil of this profil_polzovatelej
	 */
	public void setIzmenil(long izmenil);

	/**
	 * Returns the data_sozdanija of this profil_polzovatelej.
	 *
	 * @return the data_sozdanija of this profil_polzovatelej
	 */
	public Date getData_sozdanija();

	/**
	 * Sets the data_sozdanija of this profil_polzovatelej.
	 *
	 * @param data_sozdanija the data_sozdanija of this profil_polzovatelej
	 */
	public void setData_sozdanija(Date data_sozdanija);

	/**
	 * Returns the data_izmenenija of this profil_polzovatelej.
	 *
	 * @return the data_izmenenija of this profil_polzovatelej
	 */
	public Date getData_izmenenija();

	/**
	 * Sets the data_izmenenija of this profil_polzovatelej.
	 *
	 * @param data_izmenenija the data_izmenenija of this profil_polzovatelej
	 */
	public void setData_izmenenija(Date data_izmenenija);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.profil.polzovatelej.model.profil_polzovatelej profil_polzovatelej);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.profil.polzovatelej.model.profil_polzovatelej> toCacheModel();

	@Override
	public tj.profil.polzovatelej.model.profil_polzovatelej toEscapedModel();

	@Override
	public tj.profil.polzovatelej.model.profil_polzovatelej toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}