/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.fbk.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.fbk.model.Fbk;
import tj.fbk.model.FbkModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Fbk service. Represents a row in the &quot;klassifikatory.fbk&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link FbkModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FbkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FbkImpl
 * @see Fbk
 * @see FbkModel
 * @generated
 */
@ProviderType
public class FbkModelImpl extends BaseModelImpl<Fbk> implements FbkModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fbk model instance should use the {@link Fbk} interface instead.
	 */
	public static final String TABLE_NAME = "klassifikatory.fbk";
	public static final Object[][] TABLE_COLUMNS = {
			{ "fbk_id", Types.BIGINT },
			{ "pid", Types.INTEGER },
			{ "kod", Types.VARCHAR },
			{ "nazvanie_ru", Types.VARCHAR },
			{ "nazvanie_en", Types.VARCHAR },
			{ "nazvanie_tj", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("fbk_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("pid", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("kod", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nazvanie_ru", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nazvanie_en", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nazvanie_tj", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table klassifikatory.fbk (fbk_id LONG not null primary key,pid INTEGER,kod VARCHAR(75) null,nazvanie_ru VARCHAR(75) null,nazvanie_en VARCHAR(75) null,nazvanie_tj VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table klassifikatory.fbk";
	public static final String ORDER_BY_JPQL = " ORDER BY fbk.fbk_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY klassifikatory.fbk.fbk_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.fbk.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.fbk.model.Fbk"), true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.fbk.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.fbk.model.Fbk"), true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(tj.fbk.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.tj.fbk.model.Fbk"), true);
	public static final long KOD_COLUMN_BITMASK = 1L;
	public static final long PID_COLUMN_BITMASK = 2L;
	public static final long FBK_ID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.fbk.service.util.ServiceProps.get(
				"lock.expiration.time.tj.fbk.model.Fbk"));

	public FbkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fbk_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFbk_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fbk_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Fbk.class;
	}

	@Override
	public String getModelClassName() {
		return Fbk.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("fbk_id", getFbk_id());
		attributes.put("pid", getPid());
		attributes.put("kod", getKod());
		attributes.put("nazvanie_ru", getNazvanie_ru());
		attributes.put("nazvanie_en", getNazvanie_en());
		attributes.put("nazvanie_tj", getNazvanie_tj());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long fbk_id = (Long)attributes.get("fbk_id");

		if (fbk_id != null) {
			setFbk_id(fbk_id);
		}

		Integer pid = (Integer)attributes.get("pid");

		if (pid != null) {
			setPid(pid);
		}

		String kod = (String)attributes.get("kod");

		if (kod != null) {
			setKod(kod);
		}

		String nazvanie_ru = (String)attributes.get("nazvanie_ru");

		if (nazvanie_ru != null) {
			setNazvanie_ru(nazvanie_ru);
		}

		String nazvanie_en = (String)attributes.get("nazvanie_en");

		if (nazvanie_en != null) {
			setNazvanie_en(nazvanie_en);
		}

		String nazvanie_tj = (String)attributes.get("nazvanie_tj");

		if (nazvanie_tj != null) {
			setNazvanie_tj(nazvanie_tj);
		}
	}

	@Override
	public long getFbk_id() {
		return _fbk_id;
	}

	@Override
	public void setFbk_id(long fbk_id) {
		_fbk_id = fbk_id;
	}

	@Override
	public int getPid() {
		return _pid;
	}

	@Override
	public void setPid(int pid) {
		_columnBitmask |= PID_COLUMN_BITMASK;

		if (!_setOriginalPid) {
			_setOriginalPid = true;

			_originalPid = _pid;
		}

		_pid = pid;
	}

	public int getOriginalPid() {
		return _originalPid;
	}

	@Override
	public String getKod() {
		if (_kod == null) {
			return StringPool.BLANK;
		}
		else {
			return _kod;
		}
	}

	@Override
	public void setKod(String kod) {
		_columnBitmask |= KOD_COLUMN_BITMASK;

		if (_originalKod == null) {
			_originalKod = _kod;
		}

		_kod = kod;
	}

	public String getOriginalKod() {
		return GetterUtil.getString(_originalKod);
	}

	@Override
	public String getNazvanie_ru() {
		if (_nazvanie_ru == null) {
			return StringPool.BLANK;
		}
		else {
			return _nazvanie_ru;
		}
	}

	@Override
	public void setNazvanie_ru(String nazvanie_ru) {
		_nazvanie_ru = nazvanie_ru;
	}

	@Override
	public String getNazvanie_en() {
		if (_nazvanie_en == null) {
			return StringPool.BLANK;
		}
		else {
			return _nazvanie_en;
		}
	}

	@Override
	public void setNazvanie_en(String nazvanie_en) {
		_nazvanie_en = nazvanie_en;
	}

	@Override
	public String getNazvanie_tj() {
		if (_nazvanie_tj == null) {
			return StringPool.BLANK;
		}
		else {
			return _nazvanie_tj;
		}
	}

	@Override
	public void setNazvanie_tj(String nazvanie_tj) {
		_nazvanie_tj = nazvanie_tj;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Fbk.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Fbk toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Fbk)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FbkImpl fbkImpl = new FbkImpl();

		fbkImpl.setFbk_id(getFbk_id());
		fbkImpl.setPid(getPid());
		fbkImpl.setKod(getKod());
		fbkImpl.setNazvanie_ru(getNazvanie_ru());
		fbkImpl.setNazvanie_en(getNazvanie_en());
		fbkImpl.setNazvanie_tj(getNazvanie_tj());

		fbkImpl.resetOriginalValues();

		return fbkImpl;
	}

	@Override
	public int compareTo(Fbk fbk) {
		long primaryKey = fbk.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Fbk)) {
			return false;
		}

		Fbk fbk = (Fbk)obj;

		long primaryKey = fbk.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		FbkModelImpl fbkModelImpl = this;

		fbkModelImpl._originalPid = fbkModelImpl._pid;

		fbkModelImpl._setOriginalPid = false;

		fbkModelImpl._originalKod = fbkModelImpl._kod;

		fbkModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Fbk> toCacheModel() {
		FbkCacheModel fbkCacheModel = new FbkCacheModel();

		fbkCacheModel.fbk_id = getFbk_id();

		fbkCacheModel.pid = getPid();

		fbkCacheModel.kod = getKod();

		String kod = fbkCacheModel.kod;

		if ((kod != null) && (kod.length() == 0)) {
			fbkCacheModel.kod = null;
		}

		fbkCacheModel.nazvanie_ru = getNazvanie_ru();

		String nazvanie_ru = fbkCacheModel.nazvanie_ru;

		if ((nazvanie_ru != null) && (nazvanie_ru.length() == 0)) {
			fbkCacheModel.nazvanie_ru = null;
		}

		fbkCacheModel.nazvanie_en = getNazvanie_en();

		String nazvanie_en = fbkCacheModel.nazvanie_en;

		if ((nazvanie_en != null) && (nazvanie_en.length() == 0)) {
			fbkCacheModel.nazvanie_en = null;
		}

		fbkCacheModel.nazvanie_tj = getNazvanie_tj();

		String nazvanie_tj = fbkCacheModel.nazvanie_tj;

		if ((nazvanie_tj != null) && (nazvanie_tj.length() == 0)) {
			fbkCacheModel.nazvanie_tj = null;
		}

		return fbkCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{fbk_id=");
		sb.append(getFbk_id());
		sb.append(", pid=");
		sb.append(getPid());
		sb.append(", kod=");
		sb.append(getKod());
		sb.append(", nazvanie_ru=");
		sb.append(getNazvanie_ru());
		sb.append(", nazvanie_en=");
		sb.append(getNazvanie_en());
		sb.append(", nazvanie_tj=");
		sb.append(getNazvanie_tj());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("tj.fbk.model.Fbk");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>fbk_id</column-name><column-value><![CDATA[");
		sb.append(getFbk_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pid</column-name><column-value><![CDATA[");
		sb.append(getPid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kod</column-name><column-value><![CDATA[");
		sb.append(getKod());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nazvanie_ru</column-name><column-value><![CDATA[");
		sb.append(getNazvanie_ru());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nazvanie_en</column-name><column-value><![CDATA[");
		sb.append(getNazvanie_en());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nazvanie_tj</column-name><column-value><![CDATA[");
		sb.append(getNazvanie_tj());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Fbk.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Fbk.class
		};
	private long _fbk_id;
	private int _pid;
	private int _originalPid;
	private boolean _setOriginalPid;
	private String _kod;
	private String _originalKod;
	private String _nazvanie_ru;
	private String _nazvanie_en;
	private String _nazvanie_tj;
	private long _columnBitmask;
	private Fbk _escapedModel;
}