/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.dokumenty.postavwika.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DokumentyPostavwika service. Represents a row in the &quot;Dokumenty_postavwika_DokumentyPostavwika&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.dokumenty.postavwika.model.impl.DokumentyPostavwikaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.dokumenty.postavwika.model.impl.DokumentyPostavwikaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DokumentyPostavwika
 * @see tj.dokumenty.postavwika.model.impl.DokumentyPostavwikaImpl
 * @see tj.dokumenty.postavwika.model.impl.DokumentyPostavwikaModelImpl
 * @generated
 */
@ProviderType
public interface DokumentyPostavwikaModel extends BaseModel<DokumentyPostavwika> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dokumenty postavwika model instance should use the {@link DokumentyPostavwika} interface instead.
	 */

	/**
	 * Returns the primary key of this dokumenty postavwika.
	 *
	 * @return the primary key of this dokumenty postavwika
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dokumenty postavwika.
	 *
	 * @param primaryKey the primary key of this dokumenty postavwika
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dokumenty_postavwika_id of this dokumenty postavwika.
	 *
	 * @return the dokumenty_postavwika_id of this dokumenty postavwika
	 */
	public long getDokumenty_postavwika_id();

	/**
	 * Sets the dokumenty_postavwika_id of this dokumenty postavwika.
	 *
	 * @param dokumenty_postavwika_id the dokumenty_postavwika_id of this dokumenty postavwika
	 */
	public void setDokumenty_postavwika_id(long dokumenty_postavwika_id);

	/**
	 * Returns the postavwik_id of this dokumenty postavwika.
	 *
	 * @return the postavwik_id of this dokumenty postavwika
	 */
	public long getPostavwik_id();

	/**
	 * Sets the postavwik_id of this dokumenty postavwika.
	 *
	 * @param postavwik_id the postavwik_id of this dokumenty postavwika
	 */
	public void setPostavwik_id(long postavwik_id);

	/**
	 * Returns the tip_dokumenta of this dokumenty postavwika.
	 *
	 * @return the tip_dokumenta of this dokumenty postavwika
	 */
	public int getTip_dokumenta();

	/**
	 * Sets the tip_dokumenta of this dokumenty postavwika.
	 *
	 * @param tip_dokumenta the tip_dokumenta of this dokumenty postavwika
	 */
	public void setTip_dokumenta(int tip_dokumenta);

	/**
	 * Returns the nazvanie_dokumenta of this dokumenty postavwika.
	 *
	 * @return the nazvanie_dokumenta of this dokumenty postavwika
	 */
	@AutoEscape
	public String getNazvanie_dokumenta();

	/**
	 * Sets the nazvanie_dokumenta of this dokumenty postavwika.
	 *
	 * @param nazvanie_dokumenta the nazvanie_dokumenta of this dokumenty postavwika
	 */
	public void setNazvanie_dokumenta(String nazvanie_dokumenta);

	/**
	 * Returns the imja_fajla of this dokumenty postavwika.
	 *
	 * @return the imja_fajla of this dokumenty postavwika
	 */
	@AutoEscape
	public String getImja_fajla();

	/**
	 * Sets the imja_fajla of this dokumenty postavwika.
	 *
	 * @param imja_fajla the imja_fajla of this dokumenty postavwika
	 */
	public void setImja_fajla(String imja_fajla);

	/**
	 * Returns the zagruzil of this dokumenty postavwika.
	 *
	 * @return the zagruzil of this dokumenty postavwika
	 */
	public long getZagruzil();

	/**
	 * Sets the zagruzil of this dokumenty postavwika.
	 *
	 * @param zagruzil the zagruzil of this dokumenty postavwika
	 */
	public void setZagruzil(long zagruzil);

	/**
	 * Returns the data_zagruzki of this dokumenty postavwika.
	 *
	 * @return the data_zagruzki of this dokumenty postavwika
	 */
	public Date getData_zagruzki();

	/**
	 * Sets the data_zagruzki of this dokumenty postavwika.
	 *
	 * @param data_zagruzki the data_zagruzki of this dokumenty postavwika
	 */
	public void setData_zagruzki(Date data_zagruzki);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		tj.dokumenty.postavwika.model.DokumentyPostavwika dokumentyPostavwika);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.dokumenty.postavwika.model.DokumentyPostavwika> toCacheModel();

	@Override
	public tj.dokumenty.postavwika.model.DokumentyPostavwika toEscapedModel();

	@Override
	public tj.dokumenty.postavwika.model.DokumentyPostavwika toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}