/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.log.evaluated.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tj.log.evaluated.model.LogEvaluated;
import tj.log.evaluated.service.LogEvaluatedLocalService;
import tj.log.evaluated.service.persistence.LogEvaluatedPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the log evaluated local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tj.log.evaluated.service.impl.LogEvaluatedLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tj.log.evaluated.service.impl.LogEvaluatedLocalServiceImpl
 * @see tj.log.evaluated.service.LogEvaluatedLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class LogEvaluatedLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements LogEvaluatedLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tj.log.evaluated.service.LogEvaluatedLocalServiceUtil} to access the log evaluated local service.
	 */

	/**
	 * Adds the log evaluated to the database. Also notifies the appropriate model listeners.
	 *
	 * @param logEvaluated the log evaluated
	 * @return the log evaluated that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LogEvaluated addLogEvaluated(LogEvaluated logEvaluated) {
		logEvaluated.setNew(true);

		return logEvaluatedPersistence.update(logEvaluated);
	}

	/**
	 * Creates a new log evaluated with the primary key. Does not add the log evaluated to the database.
	 *
	 * @param log_evaluated_id the primary key for the new log evaluated
	 * @return the new log evaluated
	 */
	@Override
	public LogEvaluated createLogEvaluated(long log_evaluated_id) {
		return logEvaluatedPersistence.create(log_evaluated_id);
	}

	/**
	 * Deletes the log evaluated with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param log_evaluated_id the primary key of the log evaluated
	 * @return the log evaluated that was removed
	 * @throws PortalException if a log evaluated with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LogEvaluated deleteLogEvaluated(long log_evaluated_id)
		throws PortalException {
		return logEvaluatedPersistence.remove(log_evaluated_id);
	}

	/**
	 * Deletes the log evaluated from the database. Also notifies the appropriate model listeners.
	 *
	 * @param logEvaluated the log evaluated
	 * @return the log evaluated that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LogEvaluated deleteLogEvaluated(LogEvaluated logEvaluated) {
		return logEvaluatedPersistence.remove(logEvaluated);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(LogEvaluated.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return logEvaluatedPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.log.evaluated.model.impl.LogEvaluatedModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return logEvaluatedPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.log.evaluated.model.impl.LogEvaluatedModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return logEvaluatedPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return logEvaluatedPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return logEvaluatedPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public LogEvaluated fetchLogEvaluated(long log_evaluated_id) {
		return logEvaluatedPersistence.fetchByPrimaryKey(log_evaluated_id);
	}

	/**
	 * Returns the log evaluated with the primary key.
	 *
	 * @param log_evaluated_id the primary key of the log evaluated
	 * @return the log evaluated
	 * @throws PortalException if a log evaluated with the primary key could not be found
	 */
	@Override
	public LogEvaluated getLogEvaluated(long log_evaluated_id)
		throws PortalException {
		return logEvaluatedPersistence.findByPrimaryKey(log_evaluated_id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(logEvaluatedLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LogEvaluated.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("log_evaluated_id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(logEvaluatedLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(LogEvaluated.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"log_evaluated_id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(logEvaluatedLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LogEvaluated.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("log_evaluated_id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return logEvaluatedLocalService.deleteLogEvaluated((LogEvaluated)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return logEvaluatedPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the log evaluateds.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.log.evaluated.model.impl.LogEvaluatedModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of log evaluateds
	 * @param end the upper bound of the range of log evaluateds (not inclusive)
	 * @return the range of log evaluateds
	 */
	@Override
	public List<LogEvaluated> getLogEvaluateds(int start, int end) {
		return logEvaluatedPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of log evaluateds.
	 *
	 * @return the number of log evaluateds
	 */
	@Override
	public int getLogEvaluatedsCount() {
		return logEvaluatedPersistence.countAll();
	}

	/**
	 * Updates the log evaluated in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param logEvaluated the log evaluated
	 * @return the log evaluated that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LogEvaluated updateLogEvaluated(LogEvaluated logEvaluated) {
		return logEvaluatedPersistence.update(logEvaluated);
	}

	/**
	 * Returns the log evaluated local service.
	 *
	 * @return the log evaluated local service
	 */
	public LogEvaluatedLocalService getLogEvaluatedLocalService() {
		return logEvaluatedLocalService;
	}

	/**
	 * Sets the log evaluated local service.
	 *
	 * @param logEvaluatedLocalService the log evaluated local service
	 */
	public void setLogEvaluatedLocalService(
		LogEvaluatedLocalService logEvaluatedLocalService) {
		this.logEvaluatedLocalService = logEvaluatedLocalService;
	}

	/**
	 * Returns the log evaluated persistence.
	 *
	 * @return the log evaluated persistence
	 */
	public LogEvaluatedPersistence getLogEvaluatedPersistence() {
		return logEvaluatedPersistence;
	}

	/**
	 * Sets the log evaluated persistence.
	 *
	 * @param logEvaluatedPersistence the log evaluated persistence
	 */
	public void setLogEvaluatedPersistence(
		LogEvaluatedPersistence logEvaluatedPersistence) {
		this.logEvaluatedPersistence = logEvaluatedPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("tj.log.evaluated.model.LogEvaluated",
			logEvaluatedLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"tj.log.evaluated.model.LogEvaluated");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LogEvaluatedLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return LogEvaluated.class;
	}

	protected String getModelClassName() {
		return LogEvaluated.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = logEvaluatedPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = LogEvaluatedLocalService.class)
	protected LogEvaluatedLocalService logEvaluatedLocalService;
	@BeanReference(type = LogEvaluatedPersistence.class)
	protected LogEvaluatedPersistence logEvaluatedPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}