/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.sapp.services.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.sapp.services.model.OKGZ;
import tj.sapp.services.model.OKGZModel;
import tj.sapp.services.model.OKGZSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the OKGZ service. Represents a row in the &quot;sapp.okgz&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link OKGZModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OKGZImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OKGZImpl
 * @see OKGZ
 * @see OKGZModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class OKGZModelImpl extends BaseModelImpl<OKGZ> implements OKGZModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a o k g z model instance should use the {@link OKGZ} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.okgz";
	public static final Object[][] TABLE_COLUMNS = {
			{ "okgz_id", Types.BIGINT },
			{ "kod", Types.VARCHAR },
			{ "naimenovanie", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("okgz_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("kod", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("naimenovanie", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.okgz (okgz_id LONG not null primary key,kod VARCHAR(75) null,naimenovanie VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table sapp.okgz";
	public static final String ORDER_BY_JPQL = " ORDER BY okgz.okgz_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.okgz.okgz_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.sapp.services.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.sapp.services.model.OKGZ"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.sapp.services.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.sapp.services.model.OKGZ"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static OKGZ toModel(OKGZSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		OKGZ model = new OKGZImpl();

		model.setOkgz_id(soapModel.getOkgz_id());
		model.setKod(soapModel.getKod());
		model.setNaimenovanie(soapModel.getNaimenovanie());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<OKGZ> toModels(OKGZSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<OKGZ> models = new ArrayList<OKGZ>(soapModels.length);

		for (OKGZSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.sapp.services.service.util.ServiceProps.get(
				"lock.expiration.time.tj.sapp.services.model.OKGZ"));

	public OKGZModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _okgz_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOkgz_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _okgz_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OKGZ.class;
	}

	@Override
	public String getModelClassName() {
		return OKGZ.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("okgz_id", getOkgz_id());
		attributes.put("kod", getKod());
		attributes.put("naimenovanie", getNaimenovanie());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long okgz_id = (Long)attributes.get("okgz_id");

		if (okgz_id != null) {
			setOkgz_id(okgz_id);
		}

		String kod = (String)attributes.get("kod");

		if (kod != null) {
			setKod(kod);
		}

		String naimenovanie = (String)attributes.get("naimenovanie");

		if (naimenovanie != null) {
			setNaimenovanie(naimenovanie);
		}
	}

	@JSON
	@Override
	public long getOkgz_id() {
		return _okgz_id;
	}

	@Override
	public void setOkgz_id(long okgz_id) {
		_okgz_id = okgz_id;
	}

	@JSON
	@Override
	public String getKod() {
		if (_kod == null) {
			return StringPool.BLANK;
		}
		else {
			return _kod;
		}
	}

	@Override
	public void setKod(String kod) {
		_kod = kod;
	}

	@JSON
	@Override
	public String getNaimenovanie() {
		if (_naimenovanie == null) {
			return StringPool.BLANK;
		}
		else {
			return _naimenovanie;
		}
	}

	@Override
	public void setNaimenovanie(String naimenovanie) {
		_naimenovanie = naimenovanie;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			OKGZ.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OKGZ toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (OKGZ)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OKGZImpl okgzImpl = new OKGZImpl();

		okgzImpl.setOkgz_id(getOkgz_id());
		okgzImpl.setKod(getKod());
		okgzImpl.setNaimenovanie(getNaimenovanie());

		okgzImpl.resetOriginalValues();

		return okgzImpl;
	}

	@Override
	public int compareTo(OKGZ okgz) {
		long primaryKey = okgz.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof OKGZ)) {
			return false;
		}

		OKGZ okgz = (OKGZ)obj;

		long primaryKey = okgz.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<OKGZ> toCacheModel() {
		OKGZCacheModel okgzCacheModel = new OKGZCacheModel();

		okgzCacheModel.okgz_id = getOkgz_id();

		okgzCacheModel.kod = getKod();

		String kod = okgzCacheModel.kod;

		if ((kod != null) && (kod.length() == 0)) {
			okgzCacheModel.kod = null;
		}

		okgzCacheModel.naimenovanie = getNaimenovanie();

		String naimenovanie = okgzCacheModel.naimenovanie;

		if ((naimenovanie != null) && (naimenovanie.length() == 0)) {
			okgzCacheModel.naimenovanie = null;
		}

		return okgzCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{okgz_id=");
		sb.append(getOkgz_id());
		sb.append(", kod=");
		sb.append(getKod());
		sb.append(", naimenovanie=");
		sb.append(getNaimenovanie());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("tj.sapp.services.model.OKGZ");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>okgz_id</column-name><column-value><![CDATA[");
		sb.append(getOkgz_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kod</column-name><column-value><![CDATA[");
		sb.append(getKod());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>naimenovanie</column-name><column-value><![CDATA[");
		sb.append(getNaimenovanie());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = OKGZ.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			OKGZ.class
		};
	private long _okgz_id;
	private String _kod;
	private String _naimenovanie;
	private OKGZ _escapedModel;
}