/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.sapp.services.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import tj.sapp.services.model.VW_Izvewenija;
import tj.sapp.services.model.VW_IzvewenijaModel;
import tj.sapp.services.model.VW_IzvewenijaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the VW_Izvewenija service. Represents a row in the &quot;sapp.vw_izvewenija&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VW_IzvewenijaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VW_IzvewenijaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VW_IzvewenijaImpl
 * @see VW_Izvewenija
 * @see VW_IzvewenijaModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class VW_IzvewenijaModelImpl extends BaseModelImpl<VW_Izvewenija>
	implements VW_IzvewenijaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a v w_ izvewenija model instance should use the {@link VW_Izvewenija} interface instead.
	 */
	public static final String TABLE_NAME = "sapp.vw_izvewenija";
	public static final Object[][] TABLE_COLUMNS = {
			{ "izvewenija_id", Types.BIGINT },
			{ "sostojanie_id", Types.BIGINT },
			{ "status_id", Types.BIGINT },
			{ "tip_izvewenija_id", Types.BIGINT },
			{ "organizacija_id", Types.BIGINT },
			{ "vyshestojawaja_organizacija_id", Types.BIGINT },
			{ "naimenovanie", Types.VARCHAR },
			{ "sozdal", Types.BIGINT },
			{ "izmenil", Types.BIGINT },
			{ "data_sozdanija", Types.TIMESTAMP },
			{ "data_izmenenija", Types.TIMESTAMP },
			{ "kod_id", Types.BIGINT },
			{ "put_a", Types.INTEGER },
			{ "put_b", Types.INTEGER },
			{ "put_c", Types.VARCHAR },
			{ "kontaktnoe_lico", Types.VARCHAR },
			{ "je_pochta", Types.VARCHAR },
			{ "kontaktnyj_telefon", Types.VARCHAR },
			{ "data_publikacii", Types.TIMESTAMP },
			{ "data_podvedenija_itogov", Types.TIMESTAMP },
			{ "po_istecheniju_dnej", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("izvewenija_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sostojanie_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tip_izvewenija_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("organizacija_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("vyshestojawaja_organizacija_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("naimenovanie", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sozdal", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("izmenil", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("data_sozdanija", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("data_izmenenija", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("kod_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("put_a", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("put_b", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("put_c", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("kontaktnoe_lico", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("je_pochta", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("kontaktnyj_telefon", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("data_publikacii", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("data_podvedenija_itogov", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("po_istecheniju_dnej", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table sapp.vw_izvewenija (izvewenija_id LONG not null primary key,sostojanie_id LONG,status_id LONG,tip_izvewenija_id LONG,organizacija_id LONG,vyshestojawaja_organizacija_id LONG,naimenovanie VARCHAR(75) null,sozdal LONG,izmenil LONG,data_sozdanija DATE null,data_izmenenija DATE null,kod_id LONG,put_a INTEGER,put_b INTEGER,put_c VARCHAR(75) null,kontaktnoe_lico VARCHAR(75) null,je_pochta VARCHAR(75) null,kontaktnyj_telefon VARCHAR(75) null,data_publikacii DATE null,data_podvedenija_itogov DATE null,po_istecheniju_dnej INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table sapp.vw_izvewenija";
	public static final String ORDER_BY_JPQL = " ORDER BY vw_Izvewenija.izvewenija_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY sapp.vw_izvewenija.izvewenija_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(tj.sapp.services.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.tj.sapp.services.model.VW_Izvewenija"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(tj.sapp.services.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.tj.sapp.services.model.VW_Izvewenija"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static VW_Izvewenija toModel(VW_IzvewenijaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		VW_Izvewenija model = new VW_IzvewenijaImpl();

		model.setIzvewenija_id(soapModel.getIzvewenija_id());
		model.setSostojanie_id(soapModel.getSostojanie_id());
		model.setStatus_id(soapModel.getStatus_id());
		model.setTip_izvewenija_id(soapModel.getTip_izvewenija_id());
		model.setOrganizacija_id(soapModel.getOrganizacija_id());
		model.setVyshestojawaja_organizacija_id(soapModel.getVyshestojawaja_organizacija_id());
		model.setNaimenovanie(soapModel.getNaimenovanie());
		model.setSozdal(soapModel.getSozdal());
		model.setIzmenil(soapModel.getIzmenil());
		model.setData_sozdanija(soapModel.getData_sozdanija());
		model.setData_izmenenija(soapModel.getData_izmenenija());
		model.setKod_id(soapModel.getKod_id());
		model.setPut_a(soapModel.getPut_a());
		model.setPut_b(soapModel.getPut_b());
		model.setPut_c(soapModel.getPut_c());
		model.setKontaktnoe_lico(soapModel.getKontaktnoe_lico());
		model.setJe_pochta(soapModel.getJe_pochta());
		model.setKontaktnyj_telefon(soapModel.getKontaktnyj_telefon());
		model.setData_publikacii(soapModel.getData_publikacii());
		model.setData_podvedenija_itogov(soapModel.getData_podvedenija_itogov());
		model.setPo_istecheniju_dnej(soapModel.getPo_istecheniju_dnej());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<VW_Izvewenija> toModels(VW_IzvewenijaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<VW_Izvewenija> models = new ArrayList<VW_Izvewenija>(soapModels.length);

		for (VW_IzvewenijaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(tj.sapp.services.service.util.ServiceProps.get(
				"lock.expiration.time.tj.sapp.services.model.VW_Izvewenija"));

	public VW_IzvewenijaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _izvewenija_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIzvewenija_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _izvewenija_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VW_Izvewenija.class;
	}

	@Override
	public String getModelClassName() {
		return VW_Izvewenija.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("izvewenija_id", getIzvewenija_id());
		attributes.put("sostojanie_id", getSostojanie_id());
		attributes.put("status_id", getStatus_id());
		attributes.put("tip_izvewenija_id", getTip_izvewenija_id());
		attributes.put("organizacija_id", getOrganizacija_id());
		attributes.put("vyshestojawaja_organizacija_id",
			getVyshestojawaja_organizacija_id());
		attributes.put("naimenovanie", getNaimenovanie());
		attributes.put("sozdal", getSozdal());
		attributes.put("izmenil", getIzmenil());
		attributes.put("data_sozdanija", getData_sozdanija());
		attributes.put("data_izmenenija", getData_izmenenija());
		attributes.put("kod_id", getKod_id());
		attributes.put("put_a", getPut_a());
		attributes.put("put_b", getPut_b());
		attributes.put("put_c", getPut_c());
		attributes.put("kontaktnoe_lico", getKontaktnoe_lico());
		attributes.put("je_pochta", getJe_pochta());
		attributes.put("kontaktnyj_telefon", getKontaktnyj_telefon());
		attributes.put("data_publikacii", getData_publikacii());
		attributes.put("data_podvedenija_itogov", getData_podvedenija_itogov());
		attributes.put("po_istecheniju_dnej", getPo_istecheniju_dnej());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long izvewenija_id = (Long)attributes.get("izvewenija_id");

		if (izvewenija_id != null) {
			setIzvewenija_id(izvewenija_id);
		}

		Long sostojanie_id = (Long)attributes.get("sostojanie_id");

		if (sostojanie_id != null) {
			setSostojanie_id(sostojanie_id);
		}

		Long status_id = (Long)attributes.get("status_id");

		if (status_id != null) {
			setStatus_id(status_id);
		}

		Long tip_izvewenija_id = (Long)attributes.get("tip_izvewenija_id");

		if (tip_izvewenija_id != null) {
			setTip_izvewenija_id(tip_izvewenija_id);
		}

		Long organizacija_id = (Long)attributes.get("organizacija_id");

		if (organizacija_id != null) {
			setOrganizacija_id(organizacija_id);
		}

		Long vyshestojawaja_organizacija_id = (Long)attributes.get(
				"vyshestojawaja_organizacija_id");

		if (vyshestojawaja_organizacija_id != null) {
			setVyshestojawaja_organizacija_id(vyshestojawaja_organizacija_id);
		}

		String naimenovanie = (String)attributes.get("naimenovanie");

		if (naimenovanie != null) {
			setNaimenovanie(naimenovanie);
		}

		Long sozdal = (Long)attributes.get("sozdal");

		if (sozdal != null) {
			setSozdal(sozdal);
		}

		Long izmenil = (Long)attributes.get("izmenil");

		if (izmenil != null) {
			setIzmenil(izmenil);
		}

		Date data_sozdanija = (Date)attributes.get("data_sozdanija");

		if (data_sozdanija != null) {
			setData_sozdanija(data_sozdanija);
		}

		Date data_izmenenija = (Date)attributes.get("data_izmenenija");

		if (data_izmenenija != null) {
			setData_izmenenija(data_izmenenija);
		}

		Long kod_id = (Long)attributes.get("kod_id");

		if (kod_id != null) {
			setKod_id(kod_id);
		}

		Integer put_a = (Integer)attributes.get("put_a");

		if (put_a != null) {
			setPut_a(put_a);
		}

		Integer put_b = (Integer)attributes.get("put_b");

		if (put_b != null) {
			setPut_b(put_b);
		}

		String put_c = (String)attributes.get("put_c");

		if (put_c != null) {
			setPut_c(put_c);
		}

		String kontaktnoe_lico = (String)attributes.get("kontaktnoe_lico");

		if (kontaktnoe_lico != null) {
			setKontaktnoe_lico(kontaktnoe_lico);
		}

		String je_pochta = (String)attributes.get("je_pochta");

		if (je_pochta != null) {
			setJe_pochta(je_pochta);
		}

		String kontaktnyj_telefon = (String)attributes.get("kontaktnyj_telefon");

		if (kontaktnyj_telefon != null) {
			setKontaktnyj_telefon(kontaktnyj_telefon);
		}

		Date data_publikacii = (Date)attributes.get("data_publikacii");

		if (data_publikacii != null) {
			setData_publikacii(data_publikacii);
		}

		Date data_podvedenija_itogov = (Date)attributes.get(
				"data_podvedenija_itogov");

		if (data_podvedenija_itogov != null) {
			setData_podvedenija_itogov(data_podvedenija_itogov);
		}

		Integer po_istecheniju_dnej = (Integer)attributes.get(
				"po_istecheniju_dnej");

		if (po_istecheniju_dnej != null) {
			setPo_istecheniju_dnej(po_istecheniju_dnej);
		}
	}

	@JSON
	@Override
	public long getIzvewenija_id() {
		return _izvewenija_id;
	}

	@Override
	public void setIzvewenija_id(long izvewenija_id) {
		_izvewenija_id = izvewenija_id;
	}

	@JSON
	@Override
	public long getSostojanie_id() {
		return _sostojanie_id;
	}

	@Override
	public void setSostojanie_id(long sostojanie_id) {
		_sostojanie_id = sostojanie_id;
	}

	@JSON
	@Override
	public long getStatus_id() {
		return _status_id;
	}

	@Override
	public void setStatus_id(long status_id) {
		_status_id = status_id;
	}

	@JSON
	@Override
	public long getTip_izvewenija_id() {
		return _tip_izvewenija_id;
	}

	@Override
	public void setTip_izvewenija_id(long tip_izvewenija_id) {
		_tip_izvewenija_id = tip_izvewenija_id;
	}

	@JSON
	@Override
	public long getOrganizacija_id() {
		return _organizacija_id;
	}

	@Override
	public void setOrganizacija_id(long organizacija_id) {
		_organizacija_id = organizacija_id;
	}

	@JSON
	@Override
	public long getVyshestojawaja_organizacija_id() {
		return _vyshestojawaja_organizacija_id;
	}

	@Override
	public void setVyshestojawaja_organizacija_id(
		long vyshestojawaja_organizacija_id) {
		_vyshestojawaja_organizacija_id = vyshestojawaja_organizacija_id;
	}

	@JSON
	@Override
	public String getNaimenovanie() {
		if (_naimenovanie == null) {
			return StringPool.BLANK;
		}
		else {
			return _naimenovanie;
		}
	}

	@Override
	public void setNaimenovanie(String naimenovanie) {
		_naimenovanie = naimenovanie;
	}

	@JSON
	@Override
	public long getSozdal() {
		return _sozdal;
	}

	@Override
	public void setSozdal(long sozdal) {
		_sozdal = sozdal;
	}

	@JSON
	@Override
	public long getIzmenil() {
		return _izmenil;
	}

	@Override
	public void setIzmenil(long izmenil) {
		_izmenil = izmenil;
	}

	@JSON
	@Override
	public Date getData_sozdanija() {
		return _data_sozdanija;
	}

	@Override
	public void setData_sozdanija(Date data_sozdanija) {
		_data_sozdanija = data_sozdanija;
	}

	@JSON
	@Override
	public Date getData_izmenenija() {
		return _data_izmenenija;
	}

	@Override
	public void setData_izmenenija(Date data_izmenenija) {
		_data_izmenenija = data_izmenenija;
	}

	@JSON
	@Override
	public long getKod_id() {
		return _kod_id;
	}

	@Override
	public void setKod_id(long kod_id) {
		_kod_id = kod_id;
	}

	@JSON
	@Override
	public int getPut_a() {
		return _put_a;
	}

	@Override
	public void setPut_a(int put_a) {
		_put_a = put_a;
	}

	@JSON
	@Override
	public int getPut_b() {
		return _put_b;
	}

	@Override
	public void setPut_b(int put_b) {
		_put_b = put_b;
	}

	@JSON
	@Override
	public String getPut_c() {
		if (_put_c == null) {
			return StringPool.BLANK;
		}
		else {
			return _put_c;
		}
	}

	@Override
	public void setPut_c(String put_c) {
		_put_c = put_c;
	}

	@JSON
	@Override
	public String getKontaktnoe_lico() {
		if (_kontaktnoe_lico == null) {
			return StringPool.BLANK;
		}
		else {
			return _kontaktnoe_lico;
		}
	}

	@Override
	public void setKontaktnoe_lico(String kontaktnoe_lico) {
		_kontaktnoe_lico = kontaktnoe_lico;
	}

	@JSON
	@Override
	public String getJe_pochta() {
		if (_je_pochta == null) {
			return StringPool.BLANK;
		}
		else {
			return _je_pochta;
		}
	}

	@Override
	public void setJe_pochta(String je_pochta) {
		_je_pochta = je_pochta;
	}

	@JSON
	@Override
	public String getKontaktnyj_telefon() {
		if (_kontaktnyj_telefon == null) {
			return StringPool.BLANK;
		}
		else {
			return _kontaktnyj_telefon;
		}
	}

	@Override
	public void setKontaktnyj_telefon(String kontaktnyj_telefon) {
		_kontaktnyj_telefon = kontaktnyj_telefon;
	}

	@JSON
	@Override
	public Date getData_publikacii() {
		return _data_publikacii;
	}

	@Override
	public void setData_publikacii(Date data_publikacii) {
		_data_publikacii = data_publikacii;
	}

	@JSON
	@Override
	public Date getData_podvedenija_itogov() {
		return _data_podvedenija_itogov;
	}

	@Override
	public void setData_podvedenija_itogov(Date data_podvedenija_itogov) {
		_data_podvedenija_itogov = data_podvedenija_itogov;
	}

	@JSON
	@Override
	public int getPo_istecheniju_dnej() {
		return _po_istecheniju_dnej;
	}

	@Override
	public void setPo_istecheniju_dnej(int po_istecheniju_dnej) {
		_po_istecheniju_dnej = po_istecheniju_dnej;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			VW_Izvewenija.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VW_Izvewenija toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VW_Izvewenija)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VW_IzvewenijaImpl vw_IzvewenijaImpl = new VW_IzvewenijaImpl();

		vw_IzvewenijaImpl.setIzvewenija_id(getIzvewenija_id());
		vw_IzvewenijaImpl.setSostojanie_id(getSostojanie_id());
		vw_IzvewenijaImpl.setStatus_id(getStatus_id());
		vw_IzvewenijaImpl.setTip_izvewenija_id(getTip_izvewenija_id());
		vw_IzvewenijaImpl.setOrganizacija_id(getOrganizacija_id());
		vw_IzvewenijaImpl.setVyshestojawaja_organizacija_id(getVyshestojawaja_organizacija_id());
		vw_IzvewenijaImpl.setNaimenovanie(getNaimenovanie());
		vw_IzvewenijaImpl.setSozdal(getSozdal());
		vw_IzvewenijaImpl.setIzmenil(getIzmenil());
		vw_IzvewenijaImpl.setData_sozdanija(getData_sozdanija());
		vw_IzvewenijaImpl.setData_izmenenija(getData_izmenenija());
		vw_IzvewenijaImpl.setKod_id(getKod_id());
		vw_IzvewenijaImpl.setPut_a(getPut_a());
		vw_IzvewenijaImpl.setPut_b(getPut_b());
		vw_IzvewenijaImpl.setPut_c(getPut_c());
		vw_IzvewenijaImpl.setKontaktnoe_lico(getKontaktnoe_lico());
		vw_IzvewenijaImpl.setJe_pochta(getJe_pochta());
		vw_IzvewenijaImpl.setKontaktnyj_telefon(getKontaktnyj_telefon());
		vw_IzvewenijaImpl.setData_publikacii(getData_publikacii());
		vw_IzvewenijaImpl.setData_podvedenija_itogov(getData_podvedenija_itogov());
		vw_IzvewenijaImpl.setPo_istecheniju_dnej(getPo_istecheniju_dnej());

		vw_IzvewenijaImpl.resetOriginalValues();

		return vw_IzvewenijaImpl;
	}

	@Override
	public int compareTo(VW_Izvewenija vw_Izvewenija) {
		long primaryKey = vw_Izvewenija.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VW_Izvewenija)) {
			return false;
		}

		VW_Izvewenija vw_Izvewenija = (VW_Izvewenija)obj;

		long primaryKey = vw_Izvewenija.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<VW_Izvewenija> toCacheModel() {
		VW_IzvewenijaCacheModel vw_IzvewenijaCacheModel = new VW_IzvewenijaCacheModel();

		vw_IzvewenijaCacheModel.izvewenija_id = getIzvewenija_id();

		vw_IzvewenijaCacheModel.sostojanie_id = getSostojanie_id();

		vw_IzvewenijaCacheModel.status_id = getStatus_id();

		vw_IzvewenijaCacheModel.tip_izvewenija_id = getTip_izvewenija_id();

		vw_IzvewenijaCacheModel.organizacija_id = getOrganizacija_id();

		vw_IzvewenijaCacheModel.vyshestojawaja_organizacija_id = getVyshestojawaja_organizacija_id();

		vw_IzvewenijaCacheModel.naimenovanie = getNaimenovanie();

		String naimenovanie = vw_IzvewenijaCacheModel.naimenovanie;

		if ((naimenovanie != null) && (naimenovanie.length() == 0)) {
			vw_IzvewenijaCacheModel.naimenovanie = null;
		}

		vw_IzvewenijaCacheModel.sozdal = getSozdal();

		vw_IzvewenijaCacheModel.izmenil = getIzmenil();

		Date data_sozdanija = getData_sozdanija();

		if (data_sozdanija != null) {
			vw_IzvewenijaCacheModel.data_sozdanija = data_sozdanija.getTime();
		}
		else {
			vw_IzvewenijaCacheModel.data_sozdanija = Long.MIN_VALUE;
		}

		Date data_izmenenija = getData_izmenenija();

		if (data_izmenenija != null) {
			vw_IzvewenijaCacheModel.data_izmenenija = data_izmenenija.getTime();
		}
		else {
			vw_IzvewenijaCacheModel.data_izmenenija = Long.MIN_VALUE;
		}

		vw_IzvewenijaCacheModel.kod_id = getKod_id();

		vw_IzvewenijaCacheModel.put_a = getPut_a();

		vw_IzvewenijaCacheModel.put_b = getPut_b();

		vw_IzvewenijaCacheModel.put_c = getPut_c();

		String put_c = vw_IzvewenijaCacheModel.put_c;

		if ((put_c != null) && (put_c.length() == 0)) {
			vw_IzvewenijaCacheModel.put_c = null;
		}

		vw_IzvewenijaCacheModel.kontaktnoe_lico = getKontaktnoe_lico();

		String kontaktnoe_lico = vw_IzvewenijaCacheModel.kontaktnoe_lico;

		if ((kontaktnoe_lico != null) && (kontaktnoe_lico.length() == 0)) {
			vw_IzvewenijaCacheModel.kontaktnoe_lico = null;
		}

		vw_IzvewenijaCacheModel.je_pochta = getJe_pochta();

		String je_pochta = vw_IzvewenijaCacheModel.je_pochta;

		if ((je_pochta != null) && (je_pochta.length() == 0)) {
			vw_IzvewenijaCacheModel.je_pochta = null;
		}

		vw_IzvewenijaCacheModel.kontaktnyj_telefon = getKontaktnyj_telefon();

		String kontaktnyj_telefon = vw_IzvewenijaCacheModel.kontaktnyj_telefon;

		if ((kontaktnyj_telefon != null) && (kontaktnyj_telefon.length() == 0)) {
			vw_IzvewenijaCacheModel.kontaktnyj_telefon = null;
		}

		Date data_publikacii = getData_publikacii();

		if (data_publikacii != null) {
			vw_IzvewenijaCacheModel.data_publikacii = data_publikacii.getTime();
		}
		else {
			vw_IzvewenijaCacheModel.data_publikacii = Long.MIN_VALUE;
		}

		Date data_podvedenija_itogov = getData_podvedenija_itogov();

		if (data_podvedenija_itogov != null) {
			vw_IzvewenijaCacheModel.data_podvedenija_itogov = data_podvedenija_itogov.getTime();
		}
		else {
			vw_IzvewenijaCacheModel.data_podvedenija_itogov = Long.MIN_VALUE;
		}

		vw_IzvewenijaCacheModel.po_istecheniju_dnej = getPo_istecheniju_dnej();

		return vw_IzvewenijaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(43);

		sb.append("{izvewenija_id=");
		sb.append(getIzvewenija_id());
		sb.append(", sostojanie_id=");
		sb.append(getSostojanie_id());
		sb.append(", status_id=");
		sb.append(getStatus_id());
		sb.append(", tip_izvewenija_id=");
		sb.append(getTip_izvewenija_id());
		sb.append(", organizacija_id=");
		sb.append(getOrganizacija_id());
		sb.append(", vyshestojawaja_organizacija_id=");
		sb.append(getVyshestojawaja_organizacija_id());
		sb.append(", naimenovanie=");
		sb.append(getNaimenovanie());
		sb.append(", sozdal=");
		sb.append(getSozdal());
		sb.append(", izmenil=");
		sb.append(getIzmenil());
		sb.append(", data_sozdanija=");
		sb.append(getData_sozdanija());
		sb.append(", data_izmenenija=");
		sb.append(getData_izmenenija());
		sb.append(", kod_id=");
		sb.append(getKod_id());
		sb.append(", put_a=");
		sb.append(getPut_a());
		sb.append(", put_b=");
		sb.append(getPut_b());
		sb.append(", put_c=");
		sb.append(getPut_c());
		sb.append(", kontaktnoe_lico=");
		sb.append(getKontaktnoe_lico());
		sb.append(", je_pochta=");
		sb.append(getJe_pochta());
		sb.append(", kontaktnyj_telefon=");
		sb.append(getKontaktnyj_telefon());
		sb.append(", data_publikacii=");
		sb.append(getData_publikacii());
		sb.append(", data_podvedenija_itogov=");
		sb.append(getData_podvedenija_itogov());
		sb.append(", po_istecheniju_dnej=");
		sb.append(getPo_istecheniju_dnej());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(67);

		sb.append("<model><model-name>");
		sb.append("tj.sapp.services.model.VW_Izvewenija");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>izvewenija_id</column-name><column-value><![CDATA[");
		sb.append(getIzvewenija_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sostojanie_id</column-name><column-value><![CDATA[");
		sb.append(getSostojanie_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status_id</column-name><column-value><![CDATA[");
		sb.append(getStatus_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tip_izvewenija_id</column-name><column-value><![CDATA[");
		sb.append(getTip_izvewenija_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizacija_id</column-name><column-value><![CDATA[");
		sb.append(getOrganizacija_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vyshestojawaja_organizacija_id</column-name><column-value><![CDATA[");
		sb.append(getVyshestojawaja_organizacija_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>naimenovanie</column-name><column-value><![CDATA[");
		sb.append(getNaimenovanie());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sozdal</column-name><column-value><![CDATA[");
		sb.append(getSozdal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>izmenil</column-name><column-value><![CDATA[");
		sb.append(getIzmenil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data_sozdanija</column-name><column-value><![CDATA[");
		sb.append(getData_sozdanija());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data_izmenenija</column-name><column-value><![CDATA[");
		sb.append(getData_izmenenija());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kod_id</column-name><column-value><![CDATA[");
		sb.append(getKod_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>put_a</column-name><column-value><![CDATA[");
		sb.append(getPut_a());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>put_b</column-name><column-value><![CDATA[");
		sb.append(getPut_b());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>put_c</column-name><column-value><![CDATA[");
		sb.append(getPut_c());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kontaktnoe_lico</column-name><column-value><![CDATA[");
		sb.append(getKontaktnoe_lico());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>je_pochta</column-name><column-value><![CDATA[");
		sb.append(getJe_pochta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kontaktnyj_telefon</column-name><column-value><![CDATA[");
		sb.append(getKontaktnyj_telefon());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data_publikacii</column-name><column-value><![CDATA[");
		sb.append(getData_publikacii());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data_podvedenija_itogov</column-name><column-value><![CDATA[");
		sb.append(getData_podvedenija_itogov());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>po_istecheniju_dnej</column-name><column-value><![CDATA[");
		sb.append(getPo_istecheniju_dnej());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = VW_Izvewenija.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			VW_Izvewenija.class
		};
	private long _izvewenija_id;
	private long _sostojanie_id;
	private long _status_id;
	private long _tip_izvewenija_id;
	private long _organizacija_id;
	private long _vyshestojawaja_organizacija_id;
	private String _naimenovanie;
	private long _sozdal;
	private long _izmenil;
	private Date _data_sozdanija;
	private Date _data_izmenenija;
	private long _kod_id;
	private int _put_a;
	private int _put_b;
	private String _put_c;
	private String _kontaktnoe_lico;
	private String _je_pochta;
	private String _kontaktnyj_telefon;
	private Date _data_publikacii;
	private Date _data_podvedenija_itogov;
	private int _po_istecheniju_dnej;
	private VW_Izvewenija _escapedModel;
}