/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.module.access.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AccessModule service. Represents a row in the &quot;sapp.dostup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tj.module.access.model.impl.AccessModuleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tj.module.access.model.impl.AccessModuleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AccessModule
 * @see tj.module.access.model.impl.AccessModuleImpl
 * @see tj.module.access.model.impl.AccessModuleModelImpl
 * @generated
 */
@ProviderType
public interface AccessModuleModel extends BaseModel<AccessModule> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a access module model instance should use the {@link AccessModule} interface instead.
	 */

	/**
	 * Returns the primary key of this access module.
	 *
	 * @return the primary key of this access module
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this access module.
	 *
	 * @param primaryKey the primary key of this access module
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this access module.
	 *
	 * @return the uuid of this access module
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this access module.
	 *
	 * @param uuid the uuid of this access module
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the dostup_id of this access module.
	 *
	 * @return the dostup_id of this access module
	 */
	public long getDostup_id();

	/**
	 * Sets the dostup_id of this access module.
	 *
	 * @param dostup_id the dostup_id of this access module
	 */
	public void setDostup_id(long dostup_id);

	/**
	 * Returns the izvewenije_id of this access module.
	 *
	 * @return the izvewenije_id of this access module
	 */
	public long getIzvewenije_id();

	/**
	 * Sets the izvewenije_id of this access module.
	 *
	 * @param izvewenije_id the izvewenije_id of this access module
	 */
	public void setIzvewenije_id(long izvewenije_id);

	/**
	 * Returns the user_id of this access module.
	 *
	 * @return the user_id of this access module
	 */
	public long getUser_id();

	/**
	 * Sets the user_id of this access module.
	 *
	 * @param user_id the user_id of this access module
	 */
	public void setUser_id(long user_id);

	/**
	 * Returns the createdby of this access module.
	 *
	 * @return the createdby of this access module
	 */
	public long getCreatedby();

	/**
	 * Sets the createdby of this access module.
	 *
	 * @param createdby the createdby of this access module
	 */
	public void setCreatedby(long createdby);

	/**
	 * Returns the created of this access module.
	 *
	 * @return the created of this access module
	 */
	public Date getCreated();

	/**
	 * Sets the created of this access module.
	 *
	 * @param created the created of this access module
	 */
	public void setCreated(Date created);

	/**
	 * Returns the updatedby of this access module.
	 *
	 * @return the updatedby of this access module
	 */
	public long getUpdatedby();

	/**
	 * Sets the updatedby of this access module.
	 *
	 * @param updatedby the updatedby of this access module
	 */
	public void setUpdatedby(long updatedby);

	/**
	 * Returns the updated of this access module.
	 *
	 * @return the updated of this access module
	 */
	public Date getUpdated();

	/**
	 * Sets the updated of this access module.
	 *
	 * @param updated the updated of this access module
	 */
	public void setUpdated(Date updated);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(tj.module.access.model.AccessModule accessModule);

	@Override
	public int hashCode();

	@Override
	public CacheModel<tj.module.access.model.AccessModule> toCacheModel();

	@Override
	public tj.module.access.model.AccessModule toEscapedModel();

	@Override
	public tj.module.access.model.AccessModule toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}