/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tj.protocol.contracts.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tj.protocol.contracts.model.ProtocolOpening;
import tj.protocol.contracts.service.ProtocolOpeningLocalService;
import tj.protocol.contracts.service.persistence.ProtocolContractsPersistence;
import tj.protocol.contracts.service.persistence.ProtocolOpeningPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the protocol opening local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tj.protocol.contracts.service.impl.ProtocolOpeningLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tj.protocol.contracts.service.impl.ProtocolOpeningLocalServiceImpl
 * @see tj.protocol.contracts.service.ProtocolOpeningLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class ProtocolOpeningLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements ProtocolOpeningLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tj.protocol.contracts.service.ProtocolOpeningLocalServiceUtil} to access the protocol opening local service.
	 */

	/**
	 * Adds the protocol opening to the database. Also notifies the appropriate model listeners.
	 *
	 * @param protocolOpening the protocol opening
	 * @return the protocol opening that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ProtocolOpening addProtocolOpening(ProtocolOpening protocolOpening) {
		protocolOpening.setNew(true);

		return protocolOpeningPersistence.update(protocolOpening);
	}

	/**
	 * Creates a new protocol opening with the primary key. Does not add the protocol opening to the database.
	 *
	 * @param protocol_opening_id the primary key for the new protocol opening
	 * @return the new protocol opening
	 */
	@Override
	public ProtocolOpening createProtocolOpening(long protocol_opening_id) {
		return protocolOpeningPersistence.create(protocol_opening_id);
	}

	/**
	 * Deletes the protocol opening with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param protocol_opening_id the primary key of the protocol opening
	 * @return the protocol opening that was removed
	 * @throws PortalException if a protocol opening with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ProtocolOpening deleteProtocolOpening(long protocol_opening_id)
		throws PortalException {
		return protocolOpeningPersistence.remove(protocol_opening_id);
	}

	/**
	 * Deletes the protocol opening from the database. Also notifies the appropriate model listeners.
	 *
	 * @param protocolOpening the protocol opening
	 * @return the protocol opening that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ProtocolOpening deleteProtocolOpening(
		ProtocolOpening protocolOpening) {
		return protocolOpeningPersistence.remove(protocolOpening);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(ProtocolOpening.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return protocolOpeningPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.protocol.contracts.model.impl.ProtocolOpeningModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return protocolOpeningPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.protocol.contracts.model.impl.ProtocolOpeningModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return protocolOpeningPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return protocolOpeningPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return protocolOpeningPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public ProtocolOpening fetchProtocolOpening(long protocol_opening_id) {
		return protocolOpeningPersistence.fetchByPrimaryKey(protocol_opening_id);
	}

	/**
	 * Returns the protocol opening with the primary key.
	 *
	 * @param protocol_opening_id the primary key of the protocol opening
	 * @return the protocol opening
	 * @throws PortalException if a protocol opening with the primary key could not be found
	 */
	@Override
	public ProtocolOpening getProtocolOpening(long protocol_opening_id)
		throws PortalException {
		return protocolOpeningPersistence.findByPrimaryKey(protocol_opening_id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(protocolOpeningLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ProtocolOpening.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("protocol_opening_id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(protocolOpeningLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ProtocolOpening.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"protocol_opening_id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(protocolOpeningLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ProtocolOpening.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("protocol_opening_id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return protocolOpeningLocalService.deleteProtocolOpening((ProtocolOpening)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return protocolOpeningPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the protocol openings.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tj.protocol.contracts.model.impl.ProtocolOpeningModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of protocol openings
	 * @param end the upper bound of the range of protocol openings (not inclusive)
	 * @return the range of protocol openings
	 */
	@Override
	public List<ProtocolOpening> getProtocolOpenings(int start, int end) {
		return protocolOpeningPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of protocol openings.
	 *
	 * @return the number of protocol openings
	 */
	@Override
	public int getProtocolOpeningsCount() {
		return protocolOpeningPersistence.countAll();
	}

	/**
	 * Updates the protocol opening in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param protocolOpening the protocol opening
	 * @return the protocol opening that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ProtocolOpening updateProtocolOpening(
		ProtocolOpening protocolOpening) {
		return protocolOpeningPersistence.update(protocolOpening);
	}

	/**
	 * Returns the protocol contracts local service.
	 *
	 * @return the protocol contracts local service
	 */
	public tj.protocol.contracts.service.ProtocolContractsLocalService getProtocolContractsLocalService() {
		return protocolContractsLocalService;
	}

	/**
	 * Sets the protocol contracts local service.
	 *
	 * @param protocolContractsLocalService the protocol contracts local service
	 */
	public void setProtocolContractsLocalService(
		tj.protocol.contracts.service.ProtocolContractsLocalService protocolContractsLocalService) {
		this.protocolContractsLocalService = protocolContractsLocalService;
	}

	/**
	 * Returns the protocol contracts persistence.
	 *
	 * @return the protocol contracts persistence
	 */
	public ProtocolContractsPersistence getProtocolContractsPersistence() {
		return protocolContractsPersistence;
	}

	/**
	 * Sets the protocol contracts persistence.
	 *
	 * @param protocolContractsPersistence the protocol contracts persistence
	 */
	public void setProtocolContractsPersistence(
		ProtocolContractsPersistence protocolContractsPersistence) {
		this.protocolContractsPersistence = protocolContractsPersistence;
	}

	/**
	 * Returns the protocol opening local service.
	 *
	 * @return the protocol opening local service
	 */
	public ProtocolOpeningLocalService getProtocolOpeningLocalService() {
		return protocolOpeningLocalService;
	}

	/**
	 * Sets the protocol opening local service.
	 *
	 * @param protocolOpeningLocalService the protocol opening local service
	 */
	public void setProtocolOpeningLocalService(
		ProtocolOpeningLocalService protocolOpeningLocalService) {
		this.protocolOpeningLocalService = protocolOpeningLocalService;
	}

	/**
	 * Returns the protocol opening persistence.
	 *
	 * @return the protocol opening persistence
	 */
	public ProtocolOpeningPersistence getProtocolOpeningPersistence() {
		return protocolOpeningPersistence;
	}

	/**
	 * Sets the protocol opening persistence.
	 *
	 * @param protocolOpeningPersistence the protocol opening persistence
	 */
	public void setProtocolOpeningPersistence(
		ProtocolOpeningPersistence protocolOpeningPersistence) {
		this.protocolOpeningPersistence = protocolOpeningPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("tj.protocol.contracts.model.ProtocolOpening",
			protocolOpeningLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"tj.protocol.contracts.model.ProtocolOpening");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ProtocolOpeningLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ProtocolOpening.class;
	}

	protected String getModelClassName() {
		return ProtocolOpening.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = protocolOpeningPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = tj.protocol.contracts.service.ProtocolContractsLocalService.class)
	protected tj.protocol.contracts.service.ProtocolContractsLocalService protocolContractsLocalService;
	@BeanReference(type = ProtocolContractsPersistence.class)
	protected ProtocolContractsPersistence protocolContractsPersistence;
	@BeanReference(type = ProtocolOpeningLocalService.class)
	protected ProtocolOpeningLocalService protocolOpeningLocalService;
	@BeanReference(type = ProtocolOpeningPersistence.class)
	protected ProtocolOpeningPersistence protocolOpeningPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}